fabric8-ui/fabric8-ui

- cico_build_deploy.sh
This udpates the registry in the cico_build_deploy.sh script so that we push to the right namespace/image:tag to ensure we don't overwrite the almighty stuff
> Update registry to point it at the right namespace

- src/app/profile/spaces/spaces.component.html
- src/app/profile/spaces/spaces.component.ts
Fixes #66. Allows listing of spaces from the REST API backend.
Lists spaces from DummyService.
Lists spaces from the backend API.
Open questions to be addressed before merging:
1. Should the spaces be listed using the infinite scroll view, instead of the current tabular view? The SpacesService in #61 implements pagination, so this requires UI component changes.
2. Please merge this after #61, as this builds on functionality in that PR.
> List spaces from backend in UI

- src/app/profile/spaces/space.service.spec.ts
- src/app/profile/spaces/space.service.ts
Feature - implements functionality to create spaces at the backend.
No functionality to POST a space to create one, as described in #67 
SpaceService now has a method that can be invoked to create spaces in the backend.
> Create new space in backend through SpaceService.

- src/app/models/space.ts
- src/app/profile/spaces/space.service.spec.ts
- src/app/profile/spaces/space.service.ts
- src/app/space-dialog/space-dialog.component.ts
Feature - the new space creation dialog now invokes a method to create spaces in the backend.
Create a space in localstorage.
Creates a space in the backend. Also pushes the space to localstorage, to avoid any issues in rest of the app that uses dummyservice.
Please merge this PR after #73 which contains the REST API integration bits.
> Create spaces - UI task to use new SpaceService

- src/app/app.module.ts
- src/app/header/header.component.html
- src/app/home/home.component.html
- src/app/space-wizard/space-wizard.component.ts
- src/app/space-wizard/space-wizard.module.ts
-adds missing space wizard to drop down context menu
-correct dialog open close behavior :
- closes on escape key
- closes on cancel button
- does NOT close when clicking outside the modal
-missing dialog and incorrect close behavior
- adds missing space wizard dialog from context menu
> missing space wizard with correct open close behavior

- src/app/app-routing.module.ts
- src/app/shared/context.service.ts
This is done as an alternative to: https://github.com/fabric8io/fabric8-ui/pull/166 to demonstrate using route parameters instead of parsing the url.  
The order of the routes is important as well or :entity/settings and :entity/balloonpopgame end up at the same route (this fixes that).
@pmuir @joshuawilson
> Changes context creation to use route parameters

- config/webpack.dev.js
Typescript files for loaded modules can now be debugged in a browser
> Add sourcemap loader so developers can debug included npm libraries

- src/app/public/public.component.ts
Fixes issue 175 [https://github.com/fabric8io/fabric8-ui/issues/175]
Due to the fact that the /public route was already loaded, the ngOnInit function isn't called again.  This ensures that the loggedIn variable is updated based on the external event from the authentication service.
> 175 - Watch for logout event to make sure this.loggedIn is set correctly

- package.json
Revert angular2-tree-component from 3.0.2 to 2.8.2.
> angular2-tree-component version fix

- config/webpack.dev.js
excludes sourcemaps for several libraries that
are not configured correctly
> fix(build): exclude problematic sourcemaps

- src/app/analyze/analyze-overview/analyze-overview.component.html
Set the names in the Analyze page to use the username of the space's creator.
**NOTE:** I haven't use `ngIf` to detect if the creator of the space was resolved. I'd like to know why this was done in atleast one other place.
> fix(navigation): Fixed links in Analyze-Overview

- package.json
- src/app/profile/spaces/spaces.component.ts
- src/app/shared/notifications.service.ts
This ensures that the list of spaces owned by a user is displayed
under /_spaces instead of the global list of spaces.
Please don't merge as this is depends on couple of other PRs. Relies on https://github.com/fabric8-ui/ngx-fabric8-wit/pull/33 to work. An upgrade to ngx-fabric8-wit is also pending.
> feat(spaces): Display list of owned spaces

- package.json
- src/app/create/codebases/codebases-create/codebases-create.component.html
- src/app/create/codebases/codebases-create/codebases-create.component.ts
- src/app/create/codebases/codebases-create/codebases-create.module.ts
- src/app/create/codebases/codebases.component.html
- src/app/create/codebases/codebases.component.scss
- src/app/create/codebases/codebases.component.ts
- src/app/create/codebases/codebases.module.ts
- src/app/create/codebases/services/codebase.ts
- src/app/create/codebases/services/codebases.service.ts
- src/app/toolbar/toolbar-panel.component.html
- src/app/toolbar/toolbar-panel.component.scss
- src/app/toolbar/toolbar-panel.component.ts
- src/app/toolbar/toolbar-panel.module.ts
- src/assets/stylesheets/shared/_overrides-for-patternfly.scss
I'm creating a PR now for the sake of tomorrow's demo. 
The page displays a simple list view of available codebases associated with the space. If there are none, one will be created -- temporary only for the demo. There is also a panel that slides from the side to associate codebases with the space.
Note that the toolbar filter and sort are not functional right now. The expanding list view rows simply display dummy data in addition to a URL.
> Initial codebases page

- src/app/header/header.component.scss
hide the secondary navigation when the active parent does not have any visible child elements
fixes https://github.com/fabric8io/fabric8-ui/issues/454
> fix(nav): hide secondary nav when empty

- src/app/create/codebases/codebases-add/codebases-add.component.ts
This simply adds the ability to enter a URL copied from the browser address bar (e.g. https://github.com/qodfathr/helloworld-msa). That is, without the ".git" at the end.
> fix(codebases): Fixes #502. Support GitHub browser URLs

- package.json
This update takes advantage of Angular 4.
Note that there is a PR for fabric8-ui as well:
https://github.com/fabric8io/fabric8-planner/pull/1505
> fix(treelist) Upgrading angular-tree-component to 3.2.4

- openshift/fabric8-ui.app.yaml
We decided to move OpenShift templates to code repos to enable developer for faster iteration and easier maintainability. Service Delivery team will just keep track of what is deployed where, but all changes will go through this template.
> Add OpenShift template

- src/app/header/header.component.scss
- src/assets/stylesheets/shared/_overrides-for-patternfly.scss
Upgrade the header to match the new specs from the visual design team. Coincides with Planner changes.
[Planner Side-Panel PR](https://github.com/fabric8io/fabric8-planner/pull/1537)
Visual Design here: [Holistic View](https://redhat.invisionapp.com/share/N7B74T4MH#/226261730_A-0400)
Screenshot:
> feat(visuals): upgrade header to match new visual spec

- src/app/create/codebases/codebases-add/codebases-add.component.html
- src/app/create/codebases/codebases-item-actions/codebases-item-actions.component.html
- src/app/create/codebases/codebases-item-actions/codebases-item-actions.component.ts
- src/app/create/codebases/codebases-item/codebases-item.component.scss
- src/app/create/codebases/services/window.service.ts
- src/app/create/codebases/services/workspace.ts
- src/app/create/codebases/services/workspaces.service.ts
This updates the codebases page to launch Che in a new window.
Note: I'm able to launch new Che workspaces, but have not been able to launch an existing Che workspace. Aslak believes this is because Che fails to start them properly.
> fix(codebases): Updated API calls to launch Che

- src/app/create/codebases/codebases-add/codebases-add.component.ts
- src/app/create/codebases/codebases-item-actions/codebases-item-actions.component.html
- src/app/create/codebases/codebases-item-actions/codebases-item-actions.component.ts
- src/app/create/codebases/codebases-item-details/codebases-item-details.component.ts
- src/app/create/codebases/codebases-item/codebases-item.component.ts
- src/app/create/codebases/codebases.component.ts
- src/app/create/codebases/services/window.service.ts
These changes provide the ability to launch an existing Che workspace. If the workspace already exists in an open window, that same window is reused instead of opening multiple new windows. In addition, a window is now only opened if the workspace was created successfully.
Fixes #573, #579, #580, #582
> fix(codebases): Open existing Che workspace

- src/app/create/codebases/codebases-add/codebases-add.component.html
- src/app/create/codebases/codebases-add/codebases-add.component.scss
Aligned buttons right of panel.
Added top border between GitHub repo and details.
Disabled sync button for empty repo string to avoid JS errors.
> fix(codebases): #539 Updated 'add' panel to mimic mockups

- src/app/space-wizard/services/concrete/fabric8-forge.service.ts
we can move back to obsidian/launchpad quickstarts whenever they work again
> fix(quickstarts): switch to upstream fabric8 quickstarts

- src/app/home/home.component.html
- src/app/profile/profile.service.ts
The issue ended up being that any exception thrown in any watcher would cause subsequent listeners to be detached.
https://medium.com/@benlesh/on-the-subject-of-subjects-in-rxjs-2b08b7198b93
@pmuir
> fix(logout): fixes logout when invalid token exists

- package.json
- src/app/header/header.component.ts
This prevents the logout GET from being canceled due to page redirect
> fix(logout): only redirect after logout completes

- src/app/space-wizard/services/concrete/fabric8-forge.service.ts
- src/app/space-wizard/space-wizard.component.html
obsidian is now called launchpad and the 'wizard' is now being removed so we just make quickstarts now - which makes the UI look nicer too ;)
we now have a curated tag of the launchpad stuff so hopefully things won't randomly fail or disappear like when we were stuck on master ;)
> feat(launchpad): moved to the new launchpad quickstarts

- src/app/app-routing.module.ts
- src/app/getting-started/getting-started-routing.module.ts
- src/app/getting-started/getting-started.component.html
- src/app/getting-started/getting-started.component.scss
- src/app/getting-started/getting-started.component.ts
- src/app/getting-started/getting-started.module.ts
- src/app/getting-started/services/getting-started.service.ts
- src/app/getting-started/services/provider.service.ts
- src/app/header/header.component.html
- src/app/header/header.component.ts
- src/app/landing-page/landing-page.component.ts
- src/app/profile/overview/overview.component.html
- src/app/profile/overview/overview.component.ts
- src/app/profile/profile-routing.module.ts
- src/app/profile/update/update-routing.module.ts
- src/app/profile/update/update.component.html
- src/app/profile/update/update.component.scss
- src/app/profile/update/update.component.ts
- src/app/profile/update/update.module.ts
- src/app/shared/login.service.ts
This PR is for the getting started page and an initial update profile page. 
The issues with the linking APIs have been resolved by changing the workflow a bit. The fabric8-ui landing page now redirects to the getting started page instead of home. I also removed the login/authorize?link=true param from the login service URL to allow the getting started page to perform linking instead.
Note that we cannot not redirect to an external URL and provide an authorization header. Therefore, instead of using /login/link, I'm using /login/linksession and parsing the JWT token. The clientSession and sessionState are provided as query params. 
That said, I'm now able to link GitHub and OpenShift together. I can also link GitHub and OpenShift separately.
The username can only be updated once, which is …
> feat(): Getting started page

- src/app/analyze/analyze-overview/analyze-overview.component.scss
- src/app/home/home.component.scss
set the background color to match the card rows in order to give a seamless view.
there is no Issue for this - change came out of UX sync.
> fix(dashboards): set background color to match card rows

- src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html
- src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.scss
- src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.ts
- src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.module.ts
Changes:
1. Introduces Changes in analytical-report-widget.component.html
a. Select boxes for selecting pipelines and builds if present
b. On selecting, show the stack analysis information if any
2. Uses exposed bayesian functions to get recommendations while hitting its API - analytical-report-widget.component.ts
3. Changes in styles to support the HTMLs - analytical-report-widget.component.scss
Fixes #814.
Added a few screenshots to highlight the changes visually. (This is because not everyone can see all the flows, you require build associated to see specific analysis)
> fix(analytics_report): change the look of stack report as per ux

- src/app/getting-started/getting-started.component.html
We recently renamed all template tags to ng-template for Angular 4.
> fix(getting-started): Use ng-template with Angular 4

- src/app/header/menus.service.ts
Removed settings, home, and profile from the home page.
Reviewed with Catherine -- no highlighting of context menu.
> fix(header): Removed settings, home, and profile

- src/app/space-wizard/services/concrete/app-generator-configuration.service.ts
- src/app/space-wizard/services/concrete/fabric8-forge.service.ts
switch to the new fabric8-new-project command which adds validation on the first page for the git repo name
> fix(wizard): fix validation

- src/app/home/developer-poll/developer-poll-routing.module.ts
- src/app/home/developer-poll/developer-poll.component.html
- src/app/home/developer-poll/developer-poll.component.scss
- src/app/home/developer-poll/developer-poll.component.ts
- src/app/home/developer-poll/developer-poll.module.ts
- src/app/home/home.component.html
- src/app/home/home.module.ts
This is a temporary placeholder to help fill in the home page for summit and not intended to be a fully functional poll.
In order to match the mockup provided by @catrobson , the buttons are intentionally taller in height than the "large" type Patternfly buttons.
Before a button has been selected
After any button has been selected:
> feat(home): Added developer poll component

- src/app/getting-started/getting-started.component.html
- src/app/getting-started/getting-started.component.scss
- src/app/getting-started/getting-started.component.ts
The new "Save Username" button prevents the user from inadvertently updating the username when the input field's change event is detected.
It also prevents the username from being changed later, avoiding potential issues with generated URLs that contain an old username.
FYI @jryhanyc @catrobson 
Note: This probably should be merged after the PR below to show fewer changes?
https://github.com/fabric8io/fabric8-ui/pull/985
> fix(getting-started): Added save username button

- src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html
Changes:
2 scenarios
1. 'Stack Report' text becomes a link when there is sufficient bayesian information to show from the build that is selected.
2. 'Stack Report' text appears black (without link) WHEN,
a. There is no bayesian information to be shown from the build that is selected,
b. There are no pipelines,
c. There is no pipeline selected,
d. There is no build selected
> fix(stack_report_link): introduce the stack report link as per ux discussion that opens a bayesian modal on click

- src/app/getting-started/getting-started.component.ts
- Set registration_completed=true if username is saved successfully.
- Added check to prevent subscription from routing to home again prior to onDestroy.
- Ensured registration_complete and tokens are all obtained before checking if we route to home.
Note: I'm not able to test a username change, but believe setting registration_completed=true will cover that.
Unfortunately, a user only gets to update once. When Aslak resets my registrtation_complete property in our db, I'll retest.
> fix(): Set registrationCompleted if username is saved

- cico_build_deploy.sh
lets link the approve UI to the forge API for now until a cleaner fix is made
> fix(approve): add missing env var

- src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.scss
- src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.scss
- src/app/home/work-item-widget/work-item-widget.component.scss
fix the truncation on the list items inside of cards on the dashboards for demo screens
NOTE: This is so the list items inside of the Dashboard cards truncate at 1280px wide screens, without running outside of the cards.
> fix(truncation): fix truncation for cards on smaller screen

- src/app/shared/login.service.ts
Listen for noFederatedToken instead of authenticationError.
Fixes issue: https://github.com/fabric8-ui/ngx-login-client/issues/55
> fix(AuthenticationService): Listen for noFederatedToken

- src/app/getting-started/getting-started.component.html
Disabled username change for summit, but require "Save" to set registration_complete=true.
- This will ensure the getting started page is not shown again. 
- This will also ensure that the username cannot be updated later, avoiding potential issues with a nonexistent username.
> fix(): Getting started username read only

- src/app/getting-started/getting-started.component.html
- src/app/getting-started/getting-started.component.ts
This will save the username automatically when the user visits the getting started page. However, users may jump right to the home page if their tokens are already linked (e.g., via Keycloak).
> fix(): Save username automatically

- src/app/getting-started/getting-started.component.html
Due to recent edits, the form tag is not closed properly. The resulting errors in the page prevent login.
> fix(getting-started): Fix broken form tag

- cico_run_EE_tests.sh
…ker container
The credentials are used in the script `run_EE_tests.sh`. Nut they aren't propagated from the jenkins slave where they are defined
> Propagate end-to-end username and password credentials inside container

- src/app/getting-started/services/getting-started.service.ts
Ensure the createTransientProfile() always has a User object when called and not rely on the constructor’s UserService subscription.
Fixes: https://github.com/fabric8io/fabric8-ui/issues/1202
> fix(GettingStartedService): Ensure User object is obtained

- src/app/app-routing.module.ts
- src/app/error/error-routing.module.ts
- src/app/shared/context-resolver.service.ts
- src/app/shared/context.service.ts
Fixes https://github.com/fabric8io/fabric8-ui/issues/1303
Prior to the fix entering an URL like:
http://localhost:3000/blah/blah will throw:
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
and not properly redirect the `_home`
> fix(routing): when accessing unkown user/space

- config/webpack.dev.js
Fixes https://github.com/fabric8io/fabric8-ui/issues/1390
> fix(webpack): allow webpack-dev-server to serve dot url

- src/app/create/codebases/codebases-item-actions/codebases-item-actions.component.html
- src/app/create/codebases/codebases-item-actions/codebases-item-actions.component.scss
- src/app/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.html
- src/app/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.scss
- src/app/create/codebases/codebases-item-workspaces/codebases-item-workspaces.module.ts
- src/app/create/codebases/codebases-item/codebases-item.component.html
- src/app/create/codebases/codebases-item/codebases-item.component.scss
- src/app/create/codebases/codebases-item/codebases-item.component.spec.ts
- src/app/create/codebases/codebases-item/codebases-item.component.ts
- src/app/create/codebases/codebases-item/codebases-item.module.ts
- src/app/create/codebases/codebases.component.ts
Refactored list view to place column headers on their own row. 
An issue was discovered after adding an info icon to the list view header on the codebases page. When the user hovers over the icon, a tooltip is displayed, but the first row is also unexpectedly highlighted. Moving headers to their own row ensures mouseover/mouseenter events are not fired for the first list view row.
Note: This PR will depend on ngx-widgets:
https://github.com/fabric8-ui/ngx-widgets/pull/76
> fix(codebases): Headers must be on own list view row

- src/app/profile/update/update.component.html
> fix(profile): Spell "tenent" properly as "tenant"

- src/app/shared/api-locator.service.ts
- src/app/shared/runtime-console/pipelines.service.ts
when viewing the pipelines in the dashboard widget which have a space label
lets filter out any pipelines not matching the current space
> fix(space): filter pipelines on space

- environments/openshift-prod-cluster.sh
- src/app/header/header.component.ts
selection should check for sub path matches if no direct match found and
use reverse order to avoid matching 'Codebases' first (or the first tab in
general when a more specific URL matches) fixes
https://github.com/fabric8io/fabric8-ui/issues/870
> fix(navbar): fix pipeline history nav bar

- src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.html
- src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.less
update the pipeline dashboard widget with truncation to prevent overlapping
fixes https://github.com/fabric8io/fabric8-ui/issues/1452
> fix(widget): update pipeline dashboard widget

- src/app/create/codebases/codebases-item/codebases-item.component.html
update the text to read 'Workspaces' rather than 'Che Workspaces'
fixes #1221
> fix(codebases): fix text of Column and Tooltip

- src/app/space-wizard/services/fabric8-app-generator-configurator.service.ts
Fixes https://github.com/fabric8-ui/fabric8-platform/issues/1549 
since https://github.com/fabric8io/fabric8-generator/commit/b2ad1f11db56c42c799ce7606d6f5cff78d8336b has been merge on forge add-on remove UI hack to fix that issue
> fix(wizard): import github organisation with space in the name

- src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.html
- src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.less
- src/app/dashboard-widgets/recent-pipelines-widget/recent-pipelines-widget.component.html
- src/app/dashboard-widgets/recent-pipelines-widget/recent-pipelines-widget.component.less
- src/assets/stylesheets/shared/_custom-components.less
update the Pipeline widgets (all and recent) to keep 3-row config and links to OpenShift Console
closes https://github.com/fabric8-ui/fabric8-ux/issues/514
> fix(widgets): update Pipeline Widgets

- src/app/create/codebases/codebases.component.ts
After the codebases are fetched, an empty object is added to the beginning of the codebases array
for table header display purposes. When sorting happens, the sort function is trying compare
properties on the object and the empty object added at the beginning obviously does not have any
properties. So if the object is empty, skip it and return 0
fixes #1456
> fix(codebase-sort): fixing codebase sorting issue

- src/app/profile/overview/spaces/spaces.component.html
- src/app/space-wizard/components/space-creator/space-creator.component.html
remove the duplicate 'Create Space' title from the Space Wizard when creating a new Space from a user's profile. As the Space Creator component contains the title, it does not need to be passed by the page to the modal itself.
fixes https://github.com/fabric8-ui/fabric8-ui/issues/1627
> fix(title): remove duplicate title in wizard

- src/app/home/work-item-widget/work-item-widget.component.html
remove the Learn More link from the WI widget on the Home dashboard
closes https://github.com/fabric8-ui/fabric8-ux/issues/527
> fix(widget): remove Learn More from WI widget

- src/app/space-wizard/components/app-generator-single-selection-dropdown/app-generator-single-selection-dropdown.component.less
fix the alignment of the dropdown and input boxes after style updates
**Updated Views**
> fix(wizard): fix alignment of dropdown and input

- src/app/header/header.component.html
remove the Help section from the user menu, as it does not direct to OpenShift.io documentation
> fix(user-menu): remove Help from user menu

- src/assets/stylesheets/shared/_animations.less
specify the dropdown animations to only apply to the header, as it prevented other dropdowns (dropdown items, kebabs) from opening.
fixes https://github.com/fabric8-ui/fabric8-ui/issues/1727 and https://github.com/fabric8-ui/fabric8-ui/issues/1726
> fix(dropdowns): specify dropdown animations to only header

- src/app/shared/experimental-feature.resolver.ts
We need to make sure the user's profile is successfully reloaded after this setting is changed within the context.  Had to reorder events in the resolver to ensure this happens.
Tested in planner - enabling in profile and in planner and also when not logged in.
> fix(button): fix context button event handling

- src/app/profile/update/update.component.html
- src/app/profile/update/update.component.ts
There were two issues.
1. There was an undefined user attribute property -- best seen when selecting "Log Out".
2. There were unused component events (tag attributes) copied from an example.
Fixes #1737
> Fixed update profile navigation

- src/app/create/codebases/codebases-item-actions/codebases-item-actions.component.html
- src/app/create/codebases/codebases-item-actions/codebases-item-actions.component.ts
- src/app/create/codebases/codebases-item-actions/codebases-item-actions.module.ts
- src/app/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.html
- src/app/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.less
- src/app/create/codebases/codebases-item-workspaces/codebases-item-workspaces.module.ts
- src/app/create/codebases/services/workspaces.service.ts
Fixes https://github.com/fabric8-ui/fabric8-ui/issues/1745
Since the expected Che starting time is up to 3 minutes, I've set a longer timeout (5 min) for the create/open Che workspace request. This seems to work fine and no longer see the "failed to create workspace" notification -- will retest when Che goes idle again.
Note there are two controls in the codebases page that can create/open a workspace; a "Create workspace" link and a kebab menu option. These controls already become disabled while waiting for Che; however, I added a tooltip to the kebab menu option. Buttons and combo boxes do not show tooltips when disabled. A progress spinner is already shown for the "Create workspace" link while waiting for Che.
> Set longer timeout for Che start

- src/app/space-wizard/services/fabric8-app-generator.service.mock.ts
- src/app/space-wizard/services/fabric8-app-generator.service.spec.ts
- src/app/space-wizard/services/fabric8-app-generator.service.ts
Fixes https://github.com/fabric8-ui/fabric8-ui/issues/1742
Similar to previous PR https://github.com/fabric8-ui/fabric8-ui/pull/1749 but here Forge Add-on API does not return a Results.fail but throw an exception.
Now the UI code can deal with either a Results.fail or throw exception.
> fix(wizard): to display exception when thrown by Forge backend

- src/app/home/work-item-widget/work-item-widget.component.html
- src/app/home/work-item-widget/work-item-widget.component.less
Fixes https://github.com/fabric8-ui/fabric8-ui/issues/1758.
The combobox selector was recently overridden for work-item-widget. This uses the ‘top’ property to position the select element absolutely. As a result, the select element used on the codebases page is incorrectly positioned at the top of its container. 
The codebases select element should appear in each row of the list component, not in the header.
> Fix specificity of .combobox selector override

- src/app/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.html
- src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html
- src/app/home/work-item-widget/work-item-widget.component.html
- src/app/home/work-item-widget/work-item-widget.component.less
- src/app/profile/overview/work-items/work-items.component.html
This PR cleans up the misuse of the .combobox selector. This is used only for Bootstrap comboxes and is not needed for select elements. It adds nothing unless you're using an input element.
> Clean up .combobox selector

- environments/local-kubernetes.sh
- src/app/getting-started/getting-started.component.html
- src/app/getting-started/getting-started.component.ts
- src/app/shared/config/fabric8-ui-config.ts
- src/config/fabric8-ui.env.js
lets poll the fabric8-tenant service until the kubernetes tenant is connected
as the creation of the jenkins external URL is lazy and only then can we register it into KC
so that the user can login to jenkins via KC
> fix(kubernetes): fixed k8s getting started

- src/app/create/codebases/services/workspaces.service.ts
I replaced the timeout in the codebases service with a retry(8) statement. The UI will now error after 4 min. The default request timeout is 30 sec, while the che-starter timeout is 3 min. The previous timeout does not seem to override the router.
For testing purposes, I manually idled Che. Now that I'm able to monitor the Che console, I can see that UI opens the new tab after Che has started -- typically within 4-5 re-tries.
The UI will still show a "Failed to create workspace" notification; for example, if the retries are exhausted.
> Replaced codebases request timeout with retry

- package.json
- src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.ts
1. Change the version of fabric8-stack-analysis-ui package from 0.1.48 to 0.1.49
2. A codefix for reading timestamp properly as the change has been made in npm.
> fix(bug): fix the undefined print on analytics dashboard timestamp, increase the version of fabric8-stack-analysis-ui

- src/app/getting-started/getting-started.component.less
set the size of the logo on the landing page to be 100% of the column that it resides in, rather than left at it's native size
fixes https://github.com/fabric8-ui/fabric8-ui/issues/1765
> fix(landing): set size of logo on landing page

- src/app/profile/update/update.component.html
- src/app/profile/update/update.component.ts
The remaining chars component, used on the update profile page, incorrectly referenced an old import from ngx-widgets.
This should fix the build for https://github.com/fabric8-ui/fabric8-ui/pull/1833
> Wrong import reference

- src/app/app.module.ts
- src/app/shared/notifications.service.ts
NotificationService is using an old import from ngx-widgets and needs to use patternfly-ng.
> NotificationService: replace ngx-widgets import with patternfly-ng

- src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.component.html
Omit the disabled ‘Remove codebase' option from the kebab on the codebases page until an API is available for this functionality.
This resolves issue # https://github.com/fabric8-ui/fabric8-ui/issues/552
> Omit the disabled ‘Remove codebase' option

- src/app/profile/cleanup/cleanup-routing.module.ts
- src/app/profile/cleanup/cleanup.component.html
- src/app/profile/cleanup/cleanup.component.less
- src/app/profile/cleanup/cleanup.component.ts
- src/app/profile/cleanup/cleanup.module.ts
- src/app/profile/profile-routing.module.ts
- src/app/profile/profile.module.ts
- src/app/profile/services/tenent.service.ts
- src/app/profile/update/update.component.html
- src/app/profile/update/update.component.ts
Add a new cleanup component (linked to from the user profile page).  This shows all spaces, deletes them after sufficient warning for the user and calls the new tenant cleanup API (which deletes all openshift objects).  
Upon success, the tenant reset API is called which adds back Jenkins and Che support.
> feat(cleanup): add support for tenant reset/cleanup

- environments/local-kubernetes.sh
- src/app/profile/profile-routing.module.ts
- src/app/profile/tenant/tenant-routing.module.ts
- src/app/profile/tenant/tenant.component.html
- src/app/profile/tenant/tenant.component.less
- src/app/profile/tenant/tenant.component.ts
- src/app/profile/tenant/tenant.module.ts
lets add a (hidden by default) tenant configuration screen that lets the user configure
* the booster catalog ref + URL
* the jenkins, che, maven repo for the tenant version
the idea is this UI will only really be visible for internal/test accounts
if ever & would be used by the E2E tests to test a specific booster PR or a
specific tenant release PR (e.g. jenkins or che) by setting some custom
properties on the user that forge + f8tenant can detect
this PR adds a new `_tenant` tab to the user profile that lets you edit tenant related stuff (booster catalog details + tenant version stuff)
> fix(testing): add a tenant config UI

- src/a-runtime-console/kubernetes/ui/status/status-list.component.ts
"app" label has changed from "jenkins-openshift" to "jenkins"
Fixes openshiftio/openshift.io#665
This fixes the above problem, but unsure if it should be fixed in UI or in the templates?
> fix(status): Update app label used for jenkins

- src/app/profile/update/update.component.html
Fixes https://github.com/fabric8-services/fabric8-auth/issues/63
Related to https://github.com/openshiftio/openshift.io/issues/713
This PR just disable the email field in user's profile page. Eventually we will verify updated emails and will allow updating emails. See https://github.com/fabric8-services/fabric8-auth/issues/62
> Disable email update in profile

- package.json
- src/app/app-routing.module.ts
- src/app/space/plan/detail/detail.module.ts
Now the detail page is a separate module all together and the URL structure has changed. This depends https://github.com/fabric8-ui/fabric8-planner/pull/2126 .
> New planner non-contextual detail page

- README.md
add linter information for running stylelint and htmlhint as either part of the build, or separate from the build process.
> fix(README): add linter information

- src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.component.html
- src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.component.spec.ts
- src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.component.ts
- src/app/space/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.ts
- src/app/space/create/codebases/codebases-item/codebases-item.component.html
- src/app/space/create/codebases/codebases-item/codebases-item.component.less
- src/app/space/create/codebases/codebases-item/codebases-item.component.spec.ts
- src/app/space/create/codebases/codebases-item/codebases-item.component.ts
- src/app/space/create/codebases/codebases-item/codebases-item.module.ts
- src/app/space/create/codebases/codebases.component.ts
- src/app/space/create/codebases/services/che.service.ts
- src/app/space/create/codebases/services/che.ts
- src/app/space/create/codebases/services/workspaces.service.ts
- src/app/space/create/codebases/workspaces-notification/workspaces-notification.component.html
- src/app/space/create/codebases/workspaces-notification/workspaces-notification.component.less
- src/app/space/create/codebases/workspaces-notification/workspaces-notification.component.ts
- src/app/space/create/codebases/workspaces-notification/workspaces-notification.module.ts
The codebases page has been refactored to use the new Che start API. 
When the user enters the codebases page, we test if the Che server is running and start Che if necessary. While waiting for Che to start, the user is prompted with a status message. In the mean time, controls to create and open Che workspaces are hidden from view. Once we detect that the Che server is running, the user is presented with a final message indicating success. At this point, the controls to create and open Che workspaces are now visible. The success message remains visible for 7 seconds, then it's removed from view.
This functionality is based on the UX design located here: https://redhat.invisionapp.com/share/KMD5F2BV4#/screens/249837717
This addresses the following issues:
- …
> Codebases: Implement Che start API

- .htmlhintrc
remove the requirement that tagnames are all lowercase, due to Angular element conflicts
> fix(htmlhint): change tagname case requirements

- src/a-runtime-console/kubernetes/ui/status/status-info-component.ts
- src/a-runtime-console/kubernetes/ui/status/status-list.component.ts
update the pending status icon to be a clock; remove spin from loading icon
related to https://github.com/fabric8-ui/fabric8-ux/issues/648
> fix(status): update pending status icon

- src/assets/stylesheets/shared/_cards.less
remove the padding overrides from cards, returning them to default PatternFly style
related to https://github.com/fabric8-ui/fabric8-ux/issues/661
> fix(cards): remove padding overrides from cards

- src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html
- src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.less
- src/assets/stylesheets/shared/_cards.less
Update the positioning of the blank slate inside of cards. Adjust Stack Report card to account for
new positioning.
closes https://github.com/fabric8-ui/fabric8-ux/issues/661
> fix(cards): update position of blank slate in cards

- src/app/space/create/codebases/codebases.component.ts
Modified the codebases page to reload the codebases list whenever the 'codebaseAdded' event is received. 
fixes  https://github.com/openshiftio/openshift.io/issues/797
This new approach is somewhat less efficient considering we already retrieve a new codebase from the "Add Codebase" slide-out panel. However, this will ensure we only display codebases for the current space, regardless of what forge wizard does.
Currently, the forge wizard is broadcasting the ‘addedCodebase’ event, inadvertently showing a newly created codebase for the wrong space. The forge wizard probably should not broadcast that event, but it will no longer effect the codebases page other than to force the list to reload.
> Reload codebases on ‘addedCodebase’ event

- src/app/space/settings/areas/areas.component.html
- src/app/space/settings/areas/areas.component.less
- src/app/space/settings/collaborators/collaborators.component.html
- src/app/space/settings/collaborators/collaborators.component.less
The purpose of this is to as following:
- Remove the redundant phrase
- Fix the alignment of the add button on Collaborators and Areas pages
- Add "Add Collaborators" and "Add Areas" beside the plus icon
Related to this story:
https://github.com/fabric8-ui/fabric8-ux/issues/654
--------------------------------------------------
@catrobson Please help to review it, thanks.
> fix(setting): update header on Areas/Collaborators

- src/app/space/settings/collaborators/add-collaborators-dialog/add-collaborators-dialog.component.ts
It appears that the searchFilterText property of angular-2-dropdown-multiselect was removed at some point after v1.1.0. However, filterControl.value is available to use instead.
Fixes: https://github.com/openshiftio/openshift.io/issues/1140#issuecomment-337446877
> searchFilterText property no longer supported

- src/app/space/create/codebases/codebases-toolbar/codebases-toolbar.component.ts
When hovering over the '+' button, the tooltip was set to be placed to the right of the icon. With the icon set to the right, there was no room, causing the scroll and jumping. This PR sets the tooltip placement to the left of the icon, preventing the offscreen issues.
fixes https://github.com/openshiftio/openshift.io/issues/1181
> fix(tooltip): update tooltip location to prevent scrollbar

- .stylelintignore
- src/a-runtime-console/header/header.component.less
- src/a-runtime-console/kubernetes/components/pipeline-status/pipeline-status.component.less
- src/a-runtime-console/kubernetes/components/resource-header/resource.header.component.less
- src/a-runtime-console/kubernetes/ui/app/list-toolbar/list-toolbar.app.component.less
- src/a-runtime-console/kubernetes/ui/build/list-toolbar/list-toolbar.build.component.less
- src/a-runtime-console/kubernetes/ui/buildconfig/list-toolbar/list-toolbar.buildconfig.component.less
- src/a-runtime-console/kubernetes/ui/configmap/list-toolbar/list-toolbar.configmap.component.less
- src/a-runtime-console/kubernetes/ui/deployment/list-toolbar/list-toolbar.deployment.component.less
- src/a-runtime-console/kubernetes/ui/deployment/view/view.deployment.component.html
- src/a-runtime-console/kubernetes/ui/environment/list-toolbar/list-toolbar.environment.component.less
- src/a-runtime-console/kubernetes/ui/event/list-toolbar/list-toolbar.event.component.less
- src/a-runtime-console/kubernetes/ui/namespace/list-toolbar/list-toolbar.namespace.component.less
- src/a-runtime-console/kubernetes/ui/pipeline/build-stage-view/build-stage-view.component.html
- src/a-runtime-console/kubernetes/ui/pipeline/build-stage-view/build-stage-view.component.less
- src/a-runtime-console/kubernetes/ui/pipeline/full-history-toolbar/full-history-toolbar.pipeline.component.less
- src/a-runtime-console/kubernetes/ui/pipeline/history-toolbar/history-toolbar.pipeline.component.less
- src/a-runtime-console/kubernetes/ui/pipeline/list-toolbar/list-toolbar.pipeline.component.less
- src/a-runtime-console/kubernetes/ui/pod/list-toolbar/list-toolbar.pod.component.less
- src/a-runtime-console/kubernetes/ui/replicaset/edit-toolbar/edit-toolbar.replicaset.component.less
- src/a-runtime-console/kubernetes/ui/replicaset/list-toolbar/list-toolbar.replicaset.component.less
- src/a-runtime-console/kubernetes/ui/replicaset/view-toolbar/view-toolbar.replicaset.component.less
- src/a-runtime-console/kubernetes/ui/replicaset/view/view.replicaset.component.html
- src/a-runtime-console/kubernetes/ui/service/edit-toolbar/edit-toolbar.service.component.less
- src/a-runtime-console/kubernetes/ui/service/list-toolbar/list-toolbar.service.component.less
- src/a-runtime-console/kubernetes/ui/service/view-toolbar/view-toolbar.service.component.less
- src/a-runtime-console/kubernetes/ui/space/edit-toolbar/edit-toolbar.space.component.less
- src/a-runtime-console/kubernetes/ui/space/list-toolbar/list-toolbar.space.component.less
Remove the runtime-console from the stylelint ignore file. Updated any errors, leaving warnings.
Run htmlhint and fix any errors.
run `htmlhint` or `stylelint "**/*.less"` to check for errors
> fix(linters): Add runtime-console to linter checks

- src/app/layout/header/header.component.html
- src/app/space/create/codebases/codebases-toolbar/codebases-toolbar.component.less
- src/app/space/create/pipelines/pipelines.component.less
- src/assets/stylesheets/shared/_experimental.less
- src/assets/stylesheets/shared/_layout.less
Set the masthead to be 'navbar-fixed-top' and adjust margins and paddings accordingly.
This is in preparation for the addition of the vertical navigation, which will be in subsequent PRs.
Eventually, this masthead will be replaced with the one that is included in PatternFly-ng.
closes https://github.com/fabric8-ui/fabric8-ux/issues/718
> fix(masthead): set masthead to fixed position

- src/app/layout/header/header.component.html
Update the Help link to point to the proper documentation URL
fixes https://github.com/openshiftio/openshift.io/issues/912
> fix(docs): Update Help link

- src/app/space/create/codebases/codebases-toolbar/codebases-toolbar.component.html
- src/app/space/create/codebases/codebases-toolbar/codebases-toolbar.component.less
- src/app/space/create/codebases/codebases-toolbar/codebases-toolbar.component.ts
Align the tooltip to the left, in order to prevent rendering off screen.
fixes https://github.com/openshiftio/openshift.io/issues/1305
> fix(tooltip): fix alignment of tooltip for adding codebases

- README.md
I've added wiki instructions + link on readme for instruction on how to work with a local WIT and a local fabric8-ui
> doc(README): add link to how to wiki instructions

- src/app/layout/header/header.component.html
Add the ability to quickly access chat.openshift.io from the user dropdown menu.
> fix(chat): Add Quick Chat option to user menu

- src/app/space/create/codebases/codebases.component.ts
The empty state should be shown when no codebases are available. Currently, only the column headers of the list are shown
Before:
After:
> Show empty state for no codebases

- src/app/home/home.component.html
Update the documentation link on the empty Space card to point to docs.openshift.io
fixes https://github.com/openshiftio/openshift.io/issues/1339
> fix(link): update link to documentation

- src/app/home/home.component.html
- src/app/home/home.component.less
Change the color of the links on the _home banner to be more readable.
fixes https://github.com/openshiftio/openshift.io/issues/921
closes https://github.com/fabric8-ui/fabric8-ux/issues/749
> fix(color): Update colors on _home banner

- src/app/profile/update/update.component.html
Change placeholder for the Company field on the "Edit Profile" page so it has a relevant placeholder instead of "name@gmail.com".
> Fix placeholder text for Company field

- src/a-runtime-console/kubernetes/ui/status/status-list.component.html
rh-che issue - https://github.com/redhat-developer/rh-che/issues/449
openshift.io issue - https://github.com/openshiftio/openshift.io/issues/1423
> rh-che-449: Temporary removing Che status icon due to multi-tenant migration

- src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html
- src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.less
- src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html
- src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.less
- src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.html
- src/app/home/home.component.html
- src/app/home/home.component.less
- src/app/home/work-item-widget/work-item-widget.component.less
- src/app/space/analyze/analyze-overview/analyze-overview.component.html
- src/assets/stylesheets/shared/_cards.less
- src/assets/stylesheets/shared/_formulas.less
- src/assets/stylesheets/shared/_layout.less
Update the Home and Space dashboards to be responsive. They will now adjust based on viewport size and cards will resize to fit content accordingly.
Padding and Margin variables were also updated, to fix empty classes used for layouts.
This PR is related to https://github.com/fabric8-ui/fabric8-ux/issues/751 and https://github.com/openshiftio/openshift.io/issues/1443, but does not complete the work.
> fix(dashboards): Update Home and Space dashboards to be responsive

- src/app/space/forge-wizard/components/single-selection-dropdown/single-selection-dropdown.component.html
I just remembered that this needed to be done, it is complementary to https://github.com/fabric8io/fabric8-generator/commit/b36f71f6e24fadd036c5b0d4b649f630d1c63bdf and was originally reported at https://github.com/openshiftio/openshift.io/issues/1322
This is the fix:
> fix(forge-wizard): Updated tooltip to use en-US spelling

- src/app/app.module.ts
- src/app/space/create/deployments/components/deployment-card/deployment-card.component.html
- src/app/space/create/deployments/components/deployment-card/deployment-card.component.spec.ts
- src/app/space/create/deployments/components/deployment-card/deployment-card.component.ts
- src/app/space/create/deployments/deployments.module.ts
Our deployment card components no longer use a static message "Detailed
information placeholder", but instead display dummy patternfly charts
that will eventually be used to show real data. Polling mock data will be added in
the charts in a follow up patch.
This patch is a first step towards resolving https://github.com/openshiftio/openshift.io/issues/1366
> enhancement(deployments): add patternfly charts to deployment cards

- src/app/space/create/deployments/apps/deployment-card.component.html
- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.html
- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.less
- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.spec.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.html
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.less
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.spec.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.ts
- src/app/space/create/deployments/deployments.module.ts
This is an initial step to completing: https://github.com/openshiftio/openshift.io/issues/1369
This adds a donut chart with scaling buttons, ported from the openshift web-console version [1] and following the mock [2]. The css styling comes from the web-console code.
This version uses mock data, which will be changed to be acquired from the backend service in a subsequent PR. As well, this version does not have support for HPA (Horizontal Pod Auto-scaling) that the web-console version has. This is also planned for a subsequent PR.
[1] https://github.com/openshift/origin-web-console
[2] https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/260764293
Preview:
> feat(deployments): add deployments donut component

- src/a-runtime-console/kubernetes/ui/status/status-list.component.html
openshift.io issue https://github.com/openshiftio/openshift.io/issues/1495
Currently there is no mechanism for obtaining status for dsaas services like Forge
and default "success" placeholders is used for displaying the status. As a first step status for multi-tenant Che would be also just a default "Success" placeholder:
In the future there should be a mechanism in place for obtaining status of the dsaas services.
WIP status since [1] getting started pdf document must be also updated.
https://github.com/openshiftio/openshift.io/blob/master/src/assets/documents/osiogettingstarted.pdf
> openshift.io #1495: Adding default 'success' icon for multi-tenant Che server

- src/assets/stylesheets/shared/_cards.less
Fixed an issue where scrollbars always appeared inside of card components.
> fix(scrollbar): fix empty scrollbar in cards

- src/app/space/create/deployments/apps/deployment-card.component.html
- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card.component.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.html
- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.spec.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.html
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.spec.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.ts
- src/app/space/create/deployments/deployments.component.spec.ts
- src/app/space/create/deployments/models/pods.ts
- src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts
- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
This updates the donut chart work to use the deployment service providing mock data. The chart code is also updated to better with with Angular's change detection lifecycle. Notable, the chart is initialized in AfterViewInit, and DoCheck is dropped in favor of only using OnChanges. Tests have been updated to fit as well.
Addresses: https://github.com/openshiftio/openshift.io/issues/1653
> refactor(deployments): use mock service for donut chart data

- src/app/space/wizard/space-wizard.component.ts
Removed the “Your new space is created” notification per UXD's request. Since the user is already navigated to the created space, and prompted by the space wizard, another notification to take you to that space is unnecessary.
> Remove create space notification

- src/app/space/create/deployments/apps/deployment-card-container.component.html
- src/app/space/create/deployments/apps/deployment-card-container.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card-container.component.ts
- src/app/space/create/deployments/apps/deployment-card.component.html
- src/app/space/create/deployments/apps/deployment-card.component.less
- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card.component.ts
- src/app/space/create/deployments/apps/deployments-apps.component.html
- src/app/space/create/deployments/apps/deployments-apps.component.spec.ts
- src/app/space/create/deployments/apps/deployments-apps.component.ts
- src/app/space/create/deployments/deployments.component.html
- src/app/space/create/deployments/deployments.component.spec.ts
- src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
https://github.com/openshiftio/openshift.io/issues/1578
This PR adds stub URLs and actions to the menu items in the deployments cards. For the "Open Application", "View Logs" and "View OpenShift Console" items, the mock service simply returns example.com URLs for now. When the backend is ready this can now be switched, transparently to the card component. The "Delete" handler in the service simply returns a fake message immediately which is currently displayed as an alert. We'll need some guidance for a follow-up PR to potentially replace this alert with some other confirmation, or include some progress/working indicator, etc.
Additionally, the service supplies an example.com URL for the "Open Application" item 50% of the time, and the other 50% it supplies an empty string. This is to …
> Apps dropdown menu items should perform actions

- src/app/space/create/deployments/apps/deployment-card.component.html
- src/app/space/create/deployments/apps/deployment-card.component.less
- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card.component.ts
- src/app/space/create/deployments/apps/deployment-graph-label.component.html
- src/app/space/create/deployments/apps/deployment-graph-label.component.less
- src/app/space/create/deployments/apps/deployment-graph-label.component.ts
- src/app/space/create/deployments/deployments.module.ts
This patch adds mock data generated from a subscriber to our patternfly charts so that they update in real time. This will set the template for when we are ready to add real data to them.
> enhancement(deployments): Add generated mock data to patternfly charts

- src/app/space/create/deployments/apps/deployment-card.component.html
- src/app/space/create/deployments/apps/deployment-card.component.less
Design reference: https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/260764295
This PR just contains some style changes to the deployment cards so that the layout of elements (status icon, mini pod donut, version label, and menu kebab) match the design.
> fix(deployments): tweak deployment card styling to match design mock

- src/app/space/forge-wizard/service/forge-config.ts
now that the 'launcher-backend' is going to be used for backend the context path no longer has 'forge'
> context no longer contains 'forge'

- src/app/space/create/codebases/codebases-item-heading/codebases-item-heading.component.ts
Added check for null Che input. This fixes the error below seen on prod-preview -- this is not seen locally, tho.
patternfly.min.css:1 ERROR TypeError: Cannot read property 'multiTenant' of null
at CodebasesItemHeadingComponent.getNotificationMessage ...
FYI, the Che input is now being set to null via the codebases component.
> Add check for null Che input

- src/a-runtime-console/kubernetes/ui/app/list-page/list-page.app.spec.ts
- src/a-runtime-console/kubernetes/ui/app/list/list.app.spec.ts
- src/a-runtime-console/kubernetes/ui/environment/list-page/list-page.environment.spec.ts
- src/a-runtime-console/kubernetes/ui/environment/list/list.environment.spec.ts
This addresses https://github.com/openshiftio/openshift.io/issues/1641
The patch disables the two tests that have error during component cleanup.
```
ERROR: 'Error during cleanup of component', EnvironmentListPageComponent
ERROR: 'Error during cleanup of component', AppListPageComponent
```
It does not disable the tests that intermittently fail.
```
FAILED TESTS:
AppListComponent
✖ should create
PhantomJS 2.1.1 (Linux 0.0.0)
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
EnvironmentListComponent
✖ should create
PhantomJS 2.1.1 (Linux 0.0.0)
Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```
My hope is that the bad cleanup is causing these tests to intermittently …
> fix(runtime-console): disable erroring tests

- src/app/space/create/deployments/apps/deployment-card.component.html
- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card.component.ts
- src/app/space/create/deployments/models/memory-stat.ts
- src/app/space/create/deployments/resource-usage/resource-card.component.html
- src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts
- src/app/space/create/deployments/resource-usage/resource-card.component.ts
- src/app/space/create/deployments/resource-usage/utilization-bar.component.html
- src/app/space/create/deployments/resource-usage/utilization-bar.component.spec.ts
- src/app/space/create/deployments/resource-usage/utilization-bar.component.ts
- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
These commits address https://github.com/openshiftio/openshift.io/issues/1711 . The MemoryStat interface gains a "units" property and this is propagated to the resource usage utilization bar and deployment card sparkline label so that the correct unit is displayed. The mock service currently only sends units as "MB", but this is now easily changed in the future when the service implementation is adapted to pull real data, so that the used/total of the MemoryStat can be scaled down and the units set to match.
> Units scaling

- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
This makes deployment-card.component.spec use fakeAsync rather than sync. This is because of intermittent test failures as seen here:
https://jenkins.cd.test.fabric8.io/blue/organizations/jenkins/fabric8-ui%2Ffabric8-ui/detail/PR-2326/2/pipeline/
which are difficult to reproduce, but look as if they might be caused by:
https://github.com/angular/angular/issues/15486
(or similar).
There are no changed semantics of the tests themselves here, only changes to how the tests deal with async nature.
> test(deployments): use fakeAsync in deployment-card spec

- src/app/space/create/deployments/apps/deployment-card-container.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card.component.html
- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card.component.ts
- src/app/space/create/deployments/apps/deployments-apps.component.spec.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.spec.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.ts
- src/app/space/create/deployments/deployments.component.spec.ts
- src/app/space/create/deployments/models/environment.ts
- src/app/space/create/deployments/models/stat.ts
- src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.html
- src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.spec.ts
- src/app/space/create/deployments/resource-usage/resource-card.component.html
- src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts
- src/app/space/create/deployments/resource-usage/resource-card.component.ts
- src/app/space/create/deployments/resource-usage/utilization-bar.component.spec.ts
- src/app/space/create/deployments/resource-usage/utilization-bar.component.ts
- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
This PR does some cleanup and refactoring to get the Deployments page code in shape so that a future PR can swap the DeploymentsService implementation to performing HTTP requests and returning data as formatted by the backend.
> Deployments Http prep

- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card.component.ts
related to https://github.com/openshiftio/openshift.io/issues/1370
The change to add the cpuMax/memMax properties and the change to rename "total" to "quota" were from two different PRs, so when both were merged, the cpuMax/memMax lines added were out of date wrt the desired stat property. Somehow this was either missed during rebase or did not generate a merge conflict when the two PRs were merged into master.
> fix(deployments): fix missed "total" to "quota" property rename

- src/app/space/create/deployments/resource-usage/utilization-bar.component.html
- src/app/space/create/deployments/resource-usage/utilization-bar.component.less
- src/app/space/create/deployments/resource-usage/utilization-bar.component.spec.ts
- src/app/space/create/deployments/resource-usage/utilization-bar.component.ts
This addresses https://github.com/openshiftio/openshift.io/issues/1535
The usage bars now change to the warning color when usage is 75% or above.
> refactor(deployments): update resource utilization bars to show warning color when usage is high

- src/app/space/create/deployments/apps/deployment-card-container.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card-container.component.ts
- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card.component.ts
- src/app/space/create/deployments/apps/deployments-apps.component.spec.ts
- src/app/space/create/deployments/apps/deployments-apps.component.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.spec.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.spec.ts
- src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.spec.ts
- src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.ts
- src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts
- src/app/space/create/deployments/resource-usage/utilization-bar.component.spec.ts
- src/testing/test-context.ts
This PR uses the createMock and TestContext testing utils and cleans up the specs in the Deployments area. There was a lot of boilerplate and some unused/unnecessary imports - probably copy-pasted in to save time on the boilerplate. Hopefully, using these utils to minimize the amount of test boilerplate will lead to higher-quality and larger quantity (coverage) of tests in the future.
I've also added one additional optional argument to the initContext function, which allows for tests to assign component properties before the first `detectChanges` call (which is when ngOnInit is first invoked). Without this it seems very difficult to get component `@Input` values assigned and used before the lifecycle hooks start.
> Deployments tests cleanup

- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card.component.ts
- src/app/space/create/deployments/services/deployments.service.ts
closes https://github.com/openshiftio/openshift.io/issues/1728
note: doesn't use createMock test util because the tests error with `this._stream` being undefined - I think the util doesn't work well with property getters. I'll look at that separately later on. This test uses a "shallow" mock instead, but the end result is the same if you know exactly which function(s) will and should be used.
> feat(deployments): display toast notification on Delete success/failure

- src/assets/stylesheets/shared/_cards.less
Fix a bug in the card scrolling when cards are structured differently.
See https://github.com/openshiftio/openshift.io/issues/1617 for reference.
> fix(card): fix bug in card scrolling

- src/app/space/create/deployments/apps/deployments-apps.component.html
- src/app/space/create/deployments/apps/deployments-apps.component.spec.ts
- src/app/space/create/deployments/apps/deployments-apps.component.ts
- src/app/space/create/deployments/deployments-toolbar/deployments-toolbar.component.html
- src/app/space/create/deployments/deployments-toolbar/deployments-toolbar.component.spec.ts
- src/app/space/create/deployments/deployments-toolbar/deployments-toolbar.component.ts
- src/app/space/create/deployments/deployments.module.ts
This addresses: https://github.com/openshiftio/openshift.io/issues/1633
A toolbar now appears where users can filter and sort their applications by name.
Filtering:
Sorting:
> feat(deployments): add toolbar to sort and filter deployment cards

- src/app/space/create/codebases/codebases-toolbar/codebases-toolbar.component.spec.ts
- src/app/space/create/codebases/codebases-toolbar/codebases-toolbar.component.ts
This makes the results count show the correct number when users filter codebases via the toolbar. A test is added to verify this.
This addresses https://github.com/openshiftio/openshift.io/issues/1346
The image below shows the fixed version which has a correct Results count.
> fix(codebases): show correct results when filtering codebases

- src/app/space/create/deployments/apps/deployment-card.component.html
- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
- src/app/space/create/deployments/apps/deployment-status-icon.component.html
- src/app/space/create/deployments/apps/deployment-status-icon.component.less
- src/app/space/create/deployments/apps/deployment-status-icon.component.spec.ts
- src/app/space/create/deployments/apps/deployment-status-icon.component.ts
- src/app/space/create/deployments/deployments.module.ts
This patch adds a basic functionality providing changing icon statuses (and tooltips) to our deployment charts. Currently only mock CPU data triggers the changes in what is meant to be a first step towards a more general solution.
> Add icon statuses to deployment charts

- src/app/space/create/deployments/apps/deployment-card.component.ts
A hidden merge conflict between two unrelated PRs caused the cpuStat to be missing and the status component init to fail. This adds the cpuStat back.
> fix(deployments): add missing cpuStat observable to fix status component init

- src/app/space/create/deployments/apps/deployment-details.component.html
From https://github.com/openshiftio/openshift.io/issues/1516 it was found that using ngIf will contribute significantly towards stopping memory from being used (which is the primary goal of this PR). It also helps with https://github.com/openshiftio/openshift.io/issues/1709 as it causes the charts to be resized immediately when expanding the card.
> fix(deployments): destroy sparkline charts if collapsed, save memory

- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.ts
There is a race condition in c3js when destroying the chart. The fields are being set to null but there are timers still running that try to access these fields to render transitions/animations/etc. This small patch reduces the probability of this occurring. However I am confident the race still remains and could be seen in very rare circumstances (slow machines would help). Unfortunately for the time being, I don't have a better solution.
Addresses: https://github.com/openshiftio/openshift.io/issues/1788
> fix(deployments): reduce chance of race condition when destroying donut chart

- package.json
- src/app/shared/context.service.mock.ts
- src/app/space/create/codebases/services/github.service.mock.ts
- src/app/space/wizard/space-wizard.component.ts
There are no changes in the code. The work item group attribute is used only in the planner group type service.
> fix(package): Update ngx-fabric8-wit version to 6.20.1

- src/app/space/create/deployments/resource-usage/resource-card.component.html
- src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts
- src/app/space/create/deployments/resource-usage/resource-card.component.ts
- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
This addresses https://github.com/openshiftio/openshift.io/issues/1714
For testing purposes another environment is added and one of the three environments has no applications deployed. Below is a screenshot showing the result:
> fix(deployments): hide resource cards when there are no deployed applications

- src/app/space/create/deployments/apps/deployment-graph-label.component.less
I believe all less files are supposed to import the osio.less file. This adds it to one that was missing the import.
> fix(deployments): add missing osio.less import

- src/app/space/create/deployments/apps/deployment-details.component.spec.ts
This fixes lint issues in the deployment details spec. Found after running `npm run lint` and fixed by running `npm run lint-fix`.
> fix(deployments): fix linting in deployment details spec

- src/app/space/create/deployments/deployments.component.html
- src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.html
- src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.less
This tweaks the deployments page to fit within the body and not stretch out and require scrolling when it doesn't need to. See before and after screenshots below.
Before:
After:
> fix(deployments): tweak css for deployments page to fit page

- src/app/space/create/deployments/models/memory-stat.ts
- src/app/space/create/deployments/models/scaled-memory-stat.spec.ts
- src/app/space/create/deployments/models/scaled-memory-stat.ts
- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
This PR adds a class "ScaledMemoryStat" which implements the existing MemoryStat interface, which when given a value for the "used" and "quota" values, will automatically scale these values down and increase the "units" through bytes -> KB -> MB -> GB for display (ex. 2048 bytes will become 2 KB). This will be useful when the UI is hooked up to live data, where the memory stat numbers will be very large compared to the current mock data due to being sent in raw bytes.
> feat(deployments): automatically scale memory stats

- src/app/space/create/deployments/apps/deployments-apps.component.ts
This fixes an issue seen when combining the sort and filtering functionality of the toolbar. When a filter operation occurs, a sort now also occurs.
See [1] for a description of a similar issue and [2] for it's respective fix. Though it's for a different component, the same problem occurs here.
[1] https://github.com/openshiftio/openshift.io/issues/1884
[2] https://github.com/fabric8-ui/fabric8-ui/pull/2392
> fix(deployments): fix sorting and filtering toolbar

- src/app/layout/header/menus.service.ts
This makes the deployments tab visible in all environments (production, testing, dev).
Addresses https://github.com/openshiftio/openshift.io/issues/1751
Personally I don't mind waiting for the http integration before merging this. I still can't wrap my head around users seeing an experimental page with mock data that doesn't relate to anything in their project.
> fix(menus): display deployments tab in all environments

- src/app/space/create/deployments/deployments-donut/deployments-donut.component.html
This adds a null check in the deployments donut html that prevents a possible null exception when requests are slow. This was found while artificially slowing all mock http requests down.
> fix(deployments): add null check in deployments donut html

- src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.html
- src/app/home/home.component.html
Keep the Create Space icon in the Card Header for Recent Spaces card, whether the Card is in an empty state or showing Recent Spaces.
> fix(card): Keep Create Space icon in Card Header

- src/app/profile/overview/spaces/spaces.component.html
- src/assets/stylesheets/shared/osio.less
This patch remedies a bug in the profile space's view, in which
two scrollbars are loaded if the list of users' spaces is sufficiently
long. It removes scrolling from a parent div in favour of our
infinite scroll component.
Issue: https://github.com/openshiftio/openshift.io/issues/1885
> fix(profile): Fix double scroll bar in profile

- src/app/space/create/deployments/services/deployments.service.ts
service returns empty responses when HTTP requests fail, rather than allowing the error to bubble up
and break UI subscriptions
> fix(deployments): handle HTTP errors gracefully

- src/app/space/create/codebases/codebases-item/codebases-item.component.html
- src/app/space/create/codebases/codebases-item/codebases-item.component.spec.ts
- src/app/space/create/codebases/codebases-item/codebases-item.component.ts
- src/app/space/create/codebases/codebases.component.ts
- src/app/space/create/codebases/services/codebase.ts
fixes openshiftio/openshift.io#1346
There is an error on filtering codebase details by creation date and last commit:
because the codebase-item.component and codebases.component use different instances on codebase object, thus Github details fetched by one - is not accessed by another. To solve the problem - the GitHub data retrieval was moved to the codebases.component and this also solves that we keep fetching GitHub data each time on filtering.
> fix(codebases): fix filter by creation date and last commit

- src/app/profile/my-spaces/my-spaces.component.ts
This patch resolves a bug in the "view all spaces" view in which sorting preferences are lost after filters are applied and cleared.
> fix(spaces): make sure spaces remain sorted after filtering

- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.ts
This updates the donut chart to have a visible empty state. Otherwise, the donut chart becomes invisible when there are 0 pods deployed, which is a valid state. This follows the implementation in Openshift's Web Console.
> fix(deployments): tweak donut chart with visible empty state

- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card.component.ts
- src/app/space/create/deployments/apps/deployment-details.component.ts
- src/app/space/create/deployments/deployments.component.html
- src/app/space/create/deployments/deployments.component.spec.ts
- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
This set of commits replaces most of the DeploymentsServices functions with implementations that perform queries to the backend WIT endpoint, rather than returning mock data. This brings the UI up to speed with the current state of the API provided by the endpoint as of the time of writing.
Notable bugs:
- network sparkline is still mocked - no backend support
- dropdown menu items (View logs, Open Application, etc.) are still mocked - no backend support
- pods donut does not support all possible pod states, and can incorrectly display legend items for pod states that are not actually represented in the data. The next version of the backend API has a more suitable response format, so I've simply taken a "good enough" shortcut for the time being
- memory sparkline does not seem to respect …
> Deployments Http impls

- src/app/app.component.html
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/feature-flag/banner/feature-banner.component.ts
- src/app/feature-flag/service/feature-acknowledgement.service.ts
- src/app/getting-started/services/getting-started.service.ts
This PR introduces a service to manage the user's acknowledgement when dismissing the warning displayed by the experimental feature banner. This flag is stored the user's contextInformation property, under featureAcknowledgement['feature name']. Placed this service under src/app/feature-flag/service directory in anticipation of upcoming feat flag changes.
Fixes: https://github.com/openshiftio/openshift.io/issues/1557
> Make choice about experimental features persistent

- src/assets/stylesheets/shared/_scrollbars.less
The previous commit resolving the bug in which a double scroll bar
appears in the profile overview was missing some styling code, which
is added back in this patch. The original hash is 205aa0b4d343e2cb3da0c73cf7a19babb7830dd5
> fix(spaces): Add missing code to commit fixing double scrollbar

- src/app/space/create/deployments/deployments-donut/deployments-donut.component.html
This fixes the pod legend to not display statuses that have 0 pods. For example, if data comes back as 1 running, 0 stopped, it no longer shows 0 stopped.
Before:
After:
> fix(deployments): hide empty statuses from pod legend

- src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.html
- src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.ts
- src/app/dashboard-widgets/environment-widget/environment-widget.component.ts
- src/app/shared/runtime-console/fabric8-ui-space-namespace.service.ts
- src/app/shared/runtime-console/space-namespace.service.ts
This adds some null checks to code that accesses space references. The space can become null when Context changes (e.g. in the process of routing to a non-space related page). The code may still run before the component gets cleaned up, so they should be robust against a null space.
The commit `fix(runtime-console-f8ui-space-service): add null check to space references` is the direct fix for the issue [1] of accessing the Profile page from the Environments page. The rest do not fix any known issues (afaik) but should increase safety regardless. I'm open to separating into various PRs if needed. Addressing [1] is a main concern.
[1] https://github.com/openshiftio/openshift.io/issues/1940
Note: Tested with local instance targeting production. I verified this by clicking the Profile button …
> Add null checks before accessing space references

- src/app/space/create/deployments/apps/deployment-details.component.html
- src/app/space/create/deployments/apps/deployment-details.component.spec.ts
- src/app/space/create/deployments/apps/deployment-details.component.ts
- src/app/space/create/deployments/models/scaled-network-stat.spec.ts
- src/app/space/create/deployments/models/scaled-network-stat.ts
- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
This is the UI counterpart to the WIT PR here: https://github.com/fabric8-services/fabric8-wit/pull/1851 . This PR should not be merged until after that one is merged and deployed.
This replaces the mock implementation of DeploymentsService#getDeploymentNetworkStat with a real implementation that pulls timeseries data provided by the backend. The data is also autoscaled similar to the Memory stat chart.
> Deployments chart uses real network stats

- src/app/profile/update/update.component.less
remove the fixed height from the link button, causing text to flow outside of the button area
fixes https://github.com/openshiftio/openshift.io/issues/1877
> fix(button): remove fixed height from button

- src/app/layout/header/header.component.html
- src/app/layout/header/header.component.less
Apply missing truncation to the recent spaces dropdown. Class extensions were not being recognized.
related to https://github.com/openshiftio/openshift.io/issues/1911
> fix(header): apply truncation to recent spaces dropdown

- src/app/feature-flag/banner/feature-banner.component.html
- src/app/feature-flag/banner/feature-banner.component.less
- src/app/feature-flag/warning-page/feature-warning-page.component.html
- src/app/feature-flag/warning-page/feature-warning-page.component.less
Update the Feature Flag styles to include gradient backgrounds for the opt-in button, add hover styles; update class spelling error so that proper styles are applied.
related to:
- https://github.com/fabric8-ui/fabric8-ux/issues/837
- https://github.com/openshiftio/openshift.io/issues/1955
- https://github.com/openshiftio/openshift.io/issues/1956
> fix(flags): Update Feature Flag styles

- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.ts
This tweaks the updating code for the pod donut's `desiredReplicas` property. This addresses an issue [1] with the `desiredReplicas` being misleading when a user uses the OSO console to scale a pod, and views the pod donut in the OSIO Deployments page. The solution is different from the description in [1], but solves the issue of misleading text. There is also some code cleanup as well.
[1] https://github.com/openshiftio/openshift.io/issues/1966
> fix(deployments): refactor pod donut desired replica updating

- src/a-runtime-console/kubernetes/ui/pipeline/list/list.pipeline.component.html
Remove unwanted items from the kabob menu, per https://github.com/fabric8-ui/fabric8-ux/issues/834.
related to:
- https://github.com/fabric8-ui/fabric8-ux/issues/834
- https://github.com/openshiftio/openshift.io/issues/1945
- https://github.com/openshiftio/openshift.io/issues/1678
- https://github.com/openshiftio/openshift.io/issues/981
> fix(pipelines): remove unwanted items from kabob menu

- src/vendor.browser.ts
This PR fixes [osio issue 1798](https://github.com/openshiftio/openshift.io/issues/1798)[0], in which the toast notifications were not displaying correctly on the screen. After some digging and comparing toast notification styling between the pf-ng demo page and f8, I noticed that we have the correct stylesheet content, but it's being applied in an unintended way. This is a side-effect of [a patch to fix ordered imports](https://github.com/fabric8-ui/fabric8-ui/commit/a9be12292445457803d301d47de8b885e65617c7#diff-3185ad9424adad7e8fb4bd4815e81d5d)[1], and this PR simply reverts the order of the PatternFly imports so they apply correctly to components, like so:
[0] https://github.com/openshiftio/openshift.io/issues/1798
[1] https://github.com/fabric8-ui/fabric8-ui/commit/a9be12292445457803d3 …
> fix(stylesheets): fix order of PatternFly stylesheets imports

- src/app/space/create/deployments/apps/deployment-card.component.html
prevent click even propagation on deployment-details child component, so that
the "collapsed" property is not toggled, which causes the details to be hidden
when attempting to select card text or click on charts
closes https://github.com/openshiftio/openshift.io/issues/1967
> fix(deployments): clicking details does not collapse cards

- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.less
Without the `!important` modifier, the c3 css doesn't override the child's css.
This matches the OSO web-console css [1] and addresses [2].
[1] https://github.com/openshift/origin-web-console/blob/f30fb7bf103c4201edbd64a39b05ef1de6653adb/app/styles/_components.less#L70
[2] https://github.com/openshiftio/openshift.io/issues/2059
> fix(deployments): make pod donut c3 css important so it applies

- src/a-runtime-console/kubernetes/model/buildconfig.model.ts
- src/a-runtime-console/kubernetes/ui/buildconfig/list/list.buildconfig.component.html
- src/a-runtime-console/kubernetes/ui/pipeline/full-history/full-history.pipeline.component.html
- src/a-runtime-console/kubernetes/ui/pipeline/history/history.pipeline.component.html
- src/a-runtime-console/kubernetes/ui/pipeline/list/list.pipeline.component.html
This patch removes the user's ability to select "launch IDEA" - a feature which is not supported - from various dropdown menus throughout the pipelines section of the codebase.
issue : https://github.com/openshiftio/openshift.io/issues/510
> fix(pipelines): Remove ability to launch IDEA

- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.ts
This PR addresses [osio issue 1939](https://github.com/openshiftio/openshift.io/issues/1939) [0], in which the donut chart css gets masked due to Angular's stylesheet encapsulation.
This patch changes the ViewEncapsulation of both the deployments donut component and donut chart component to be 'none'. As a result, the stylesheet values for the donut chart are now visible and applied.
For example, here is the current stylesheet applied to the c3 tooltip:
And here it is if only the chart component is given view encapsulation none:
And here is the result of having both the donut and chart components having view encapsulation none:
This allows for the c3 tooltip-container values[1] to be applied.
[0] https://github.com/openshiftio/openshift.io/issues/1939
[1] …
> fix(deployments): fix deployments donut chart to properly apply c3js css

- src/app/space/create/deployments/apps/deployment-card.component.html
- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card.component.ts
- src/app/space/create/deployments/apps/deployment-details.component.html
- src/app/space/create/deployments/apps/deployment-details.component.spec.ts
- src/app/space/create/deployments/apps/deployment-details.component.ts
This addresses https://github.com/openshiftio/openshift.io/issues/2095
The collapsed components linger for 5 seconds before being unloaded if the card is collapsed while remaining loaded if the card is expanded.
> fix(deployments): make collapsed cards linger

- src/app/space/create/deployments/deployments.component.spec.ts
- src/app/space/create/deployments/deployments.component.ts
- src/app/space/create/deployments/deployments.module.ts
DeploymentsService injector scope is that of the DeploymentsComponent so that the service does not
outlive the component
fixes https://github.com/openshiftio/openshift.io/issues/2104
> fix(deployments): reduce DeploymentsService injector scope

- src/app/feature-flag/warning-page/feature-warning-page.component.html
This fixes a typo. Closes https://github.com/openshiftio/openshift.io/issues/1930
> fix(feature-flag): fix typo in warning text

- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.ts
This is a tiny fix. The intention was to not allow null. This now allows 0, which is a valid value for desired replicas. `==` is used to also check for undefined without having to write another or statement.
Sorry for the mistake;
> fix(deployments): use null check instead for desired replicas

- src/app/space/create/deployments/apps/deployment-details.component.html
- src/app/space/create/deployments/apps/deployment-details.component.less
- src/app/space/create/deployments/apps/deployment-graph-label.component.less
related to https://github.com/openshiftio/openshift.io/issues/2176
This adresses the text size and column width for the details graphs/labels as well as adds the "Resource Usage" heading. It does not fix the donut chart scaling label.
> fix(deployments): tweak deployment card detail styling

- src/app/space/settings/areas/areas.component.html
- src/app/space/settings/areas/areas.component.ts
- src/app/space/settings/areas/areas.module.ts
- src/app/space/settings/areas/create-area-dialog/create-area-dialog.component.html
- src/app/space/settings/areas/create-area-dialog/create-area-dialog.component.ts
- src/app/space/settings/areas/create-area-dialog/create-area-dialog.module.ts
This patch sets the focus on the "name" input field of the Create Area Dialogue immediately after the modal displaying the component appears.
Solves issue: https://github.com/openshiftio/openshift.io/issues/1999
> fix(areas): Automatically focus input field when create are modal opened

- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
This is the UI side of https://github.com/fabric8-services/fabric8-wit/pull/1849 . These changes adapt the DeploymentsService to expect the JSON response format received from the WIT backend after that PR is merged.
One changeset is missing from this PR to complete the set and close out the corresponding UI issue (https://github.com/openshiftio/openshift.io/issues/1987), which is to modify the `DeploymentsService#scalePods` implementation to suit whatever changed request/response format occurs in the WIT backend, which has not yet been done. The URL is expected to change as is the method of passing the "podCount" or "desiredReplicas" parameter.
> Deployments page expects JSON-API response format

- src/app/space/settings/areas/areas.component.html
`areas.component.ts` does not have a property `listViewConfig` but it does have the property `listConfig`. This fixes the html to refer to the correct property, which is what I think was intended.
> fix(areas): fix config in html

- src/app/profile/cleanup/cleanup.component.html
- src/app/space/settings/areas/areas.component.html
- src/app/space/settings/collaborators/collaborators.component.html
This replaces uses of the `template` directive with `ng-template` instead.
> fix(app): use ng-template in place of deprecated template directive

- src/app/space/create/codebases/codebases.component.less
reset the styles of the icon in the codebases list to fit according to spec
fixes https://github.com/openshiftio/openshift.io/issues/1867
> fix(codebases): fix alignment of icon in list

- src/app/layout/header/header.component.ts
This PR addresses https://github.com/openshiftio/openshift.io/issues/1708
This issue was caused by the analyze tab not being given an active state then selected. The analyze tab has no children, and should be activated (when selected) by [line 235 of the header component](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/layout/header/header.component.ts#L235)[0]. However, the condition for checking if sub-menu children exist incorrectly passes because subMenus is given the value of [] at [line 193](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/layout/header/header.component.ts#L193)[1].
[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/layout/header/header.component.ts#L235
[1] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/layout/hea …
> fix(header): fix analyze tab not highlighting when selected

- src/app/space/settings/areas/areas.component.html
- src/app/space/settings/areas/areas.component.ts
- src/app/space/settings/areas/create-area-dialog/create-area-dialog.component.html
- src/app/space/settings/areas/create-area-dialog/create-area-dialog.component.less
- src/app/space/settings/areas/create-area-dialog/create-area-dialog.component.ts
This patch resolves a bug in the add areas modal, whereby its header appears outside of the modal. It also solves an issue whereby the modal's input field is not reset when it is closed.
Solves issues: 
https://github.com/openshiftio/openshift.io/issues/2212 
https://github.com/openshiftio/openshift.io/issues/2214
> fix(areas): fix various ui issues in create new area modal

- package.json
Bump Lesscss to 3.0.0, removing alpha tag
> fix(version): bump Lesscss to 3.0.0 release

- src/app/space/create/codebases/codebases-delete/codebase-delete-dialog.component.html
- src/app/space/create/codebases/codebases-delete/codebase-delete-dialog.component.ts
- src/app/space/create/codebases/codebases-delete/codebase-delete-dialog.module.ts
- src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.component.html
- src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.component.spec.ts
- src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.component.ts
- src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.module.ts
- src/app/space/settings/collaborators/add-collaborators-dialog/add-collaborators-dialog.component.html
- src/app/space/settings/collaborators/add-collaborators-dialog/add-collaborators-dialog.component.less
- src/app/space/settings/collaborators/add-collaborators-dialog/add-collaborators-dialog.component.ts
- src/app/space/settings/collaborators/add-collaborators-dialog/add-collaborators-dialog.module.ts
- src/app/space/settings/collaborators/collaborators.component.html
- src/app/space/settings/collaborators/collaborators.component.ts
- src/app/space/settings/collaborators/collaborators.module.ts
These commits convert two components, `codebase-delete-dialog` and `add-collaborators-dialog and codebase-delete-dialog` to use ngx-bootstrap/modal as their modal provider, instead of ngx-modal.
This is part of a larger issue tracked [here](https://github.com/openshiftio/openshift.io/issues/2170) to ultimately drop ngx-modal, which is no longer maintained, from the project. Since there are many references to ngx-modal in the runtime-console, which itself is being dropped, these commits are meant to be put it for now until that is done, at which point the dependency can be dropped altogether.
> Convert uses of ngx-modal to ngx-bootstrap/modal

- src/app/space/settings/areas/areas.component.ts
- src/app/space/settings/areas/create-area-dialog/create-area-dialog.component.ts
This patch fixes a bug in which the warning message for attempting to create a space with a duplicate name persists after the modal is closed.
Solves: https://github.com/openshiftio/openshift.io/issues/2231
> fix(areas): Hide warning message after modal closed

- src/app/space/create/deployments/apps/deployment-card-container.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card-container.component.ts
- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card.component.ts
- src/app/space/create/deployments/apps/deployment-details.component.spec.ts
- src/app/space/create/deployments/apps/deployment-details.component.ts
- src/app/space/create/deployments/apps/deployment-graph-label.component.ts
- src/app/space/create/deployments/apps/deployment-status-icon.component.ts
- src/app/space/create/deployments/apps/deployments-apps.component.spec.ts
- src/app/space/create/deployments/apps/deployments-apps.component.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.spec.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.spec.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.ts
- src/app/space/create/deployments/deployments-linechart/deployments-linechart.component.ts
- src/app/space/create/deployments/deployments-toolbar/deployments-toolbar.component.spec.ts
- src/app/space/create/deployments/deployments-toolbar/deployments-toolbar.component.ts
- src/app/space/create/deployments/models/pod-phase.ts
- src/app/space/create/deployments/models/pods.ts
- src/app/space/create/deployments/models/scaled-memory-stat.ts
- src/app/space/create/deployments/models/scaled-network-stat.ts
- src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.spec.ts
- src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.ts
- src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts
- src/app/space/create/deployments/resource-usage/resource-card.component.ts
- src/app/space/create/deployments/resource-usage/utilization-bar.component.html
- src/app/space/create/deployments/resource-usage/utilization-bar.component.spec.ts
- src/app/space/create/deployments/resource-usage/utilization-bar.component.ts
These commits simply clean up the Deployments area. For the most part it's just simple indentation type fixes, but there are also a fair number of type annotations added where previously either no type was declared or the type was declared as "any". There is also one larger commit ("add PodPhase enum type") that adds a new enum type to encapsulate the running states of deployment pods and reduce duplication of strings that were previously used.
> Deployments code cleanup

- src/app/home/home.component.html
Update the banner on the homepage to include a pointer to the Getting Started guide
related to https://github.com/openshiftio/openshift.io/issues/2215
> fix(home): Update banner items to go to Docs site

- src/app/profile/cleanup/cleanup.component.ts
- src/app/profile/services/tenant.service.ts
- src/app/profile/tenant/tenant.component.ts
- src/app/profile/update/update.component.html
- src/app/profile/update/update.component.spec.ts
- src/app/profile/update/update.component.ts
This PR addresses instances where the word 'tenant' is spelled as 'tenent'.
Looking back through past issues and PRs [0][1], it would appear that the use of 'tenent' is a typo (if it is indeed intentional, then disregard this PR). 
This could be particularly confusing in instances such as https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/profile/update/update.component.html#L182 where the two spellings are used in the same line of html.
[0] https://github.com/fabric8-ui/fabric8-ui/issues/1256
[1] https://github.com/fabric8-ui/fabric8-ui/pull/1420
> fix(spelling): fix spelling of 'tenent' to 'tenant'

- src/app/space/settings/areas/areas.component.html
- src/app/space/settings/areas/areas.component.ts
- src/app/space/settings/areas/create-area-dialog/create-area-dialog.component.ts
This PR accomplishes two goals : It ensures that when the Create Area modal is re-opened (i.e., when creating a second area) that the create button is disabled by default until user input is provided [0]. It also moves all event handler code to the create-area-dialog component, rather than having some there and the rest in the areas component. 
Solves: 
[0] https://github.com/openshiftio/openshift.io/issues/2252
There is discussion in [0] about the desired behaviour regarding which area should be selected on the modal open event. This implementation follows what @catrobson describes in that issue.
> Relock create area's create button and move event handler code

- src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.html
This short PR adjusts the fa-angle icon to change dynamically based on the "resource usage" section of the page being expanded or collapsed.
Currently, the icon is always set to fa-angle-down, regardless of the resources section being collapsed or expanded. Here, an `ngClass` can be introduced to change the icon based on the status of the `resourcesCollapsed` variable that gets toggled when the user expands/collapses the section.
What it looks like currently:
What it looks like after this patch:
> fix(deployments): fix resource usage collapsed icon

- src/app/profile/overview/overview.component.html
- src/app/profile/overview/overview.component.less
This PR addresses https://github.com/openshiftio/openshift.io/issues/2100 [0].
This PR adds some CSS properties to the bio section of the profile page. The word-wrap is used to make text word-wrap, and the hyphens property introduces hyphens when word-wrapping occurs. However, the hyphens property is not currently supported by all browsers [1], and only the 'none' option is supported by Chrome [2]. This results in word-wrapping and hyphenating in many browsers (IE, Firefox, Edge, Safari, etc.), but Chrome will only have word-wrapping. Additionally, for hyphenation to work properly, the html component it applies to has to have the lang option set. I've included some screenshots below to demo the functionality.
Here is what the bio looks like currently:
Here is what the bio looks like with …
> fix(overview): add word-wrap functionality to bio text

- src/app/space/settings/areas/create-area-dialog/create-area-dialog.component.html
- src/app/space/settings/areas/create-area-dialog/create-area-dialog.component.less
- src/app/space/settings/areas/create-area-dialog/create-area-dialog.component.ts
In order, the accompanying commits to this PR achieve three things in the create area modal:
1) Introduce a custom validator directive to the modal, which checks if a duplicate name has been entered. This saves us from the current wasteful implementation whereby a request must be sent, receiving an 409, before an error can be displayed informing the user that they must enter a unique name. 
2) Adds correct error highlighting (in red) as well as a helpful message underneath any infringing fields, as by the [patternfly specification](http://www.patternfly.org/pattern-library/forms-and-controls/errors-and-validation).
3) Adds additional error messages for the situation where a user types a name into the input, and then removes all inputted text, leaving the field blank. 
Solves : …
> Add error highlighting functionality

- src/app/space/create/deployments/apps/deployment-card.component.html
This fixes an issue from a previous commit [1] where the kebab links would no longer work. Sorry for the mistake.
[1] https://github.com/fabric8-ui/fabric8-ui/commit/29936fd3da88a9149528d8e3d9a75775ff9b267d
> fix(deployments): fix kebab links

- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
This fixes the dropdown tests to provide actual Event objects. The event from the handler is now being used by the component and would result in TypeErrors when running the tests. The TypeErrors are no longer seen with this fix. Interestingly, this did not affect the tests ability to run and pass/fail.
This resolves https://github.com/openshiftio/openshift.io/issues/2386
> fix(deployments): fix deployment card dropdown tests

- src/app/dashboard-widgets/environment-widget/environment-widget.component.html
- src/app/dashboard-widgets/environment-widget/environment-widget.component.ts
- src/app/space/create/deployments/services/deployments.service.ts
This patch refactors the component code for the deployments widget on the space dashboard, so that it reflects the actual state of applications that are deployed. It is quite minimal, in that it simply reflects things as they were when we were still using the runtime console.
Solves: https://github.com/openshiftio/openshift.io/issues/2301
Screenshot:
> refactor(dashboard): Reactivate deployments widget

- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
Swallow errors so that application Observable subscriptions are not interfered with by uncaught HTTP
errors, but explicitly send errors to global ErrorHandler to ensure correct error logging. See
https://github.com/openshiftio/openshift.io/issues/2360#issuecomment-368915994
> fix(deployments): report errors to global ErrorHandler and swallow

- src/app/profile/tenant/tenant.component.spec.ts
This PR addresses [issue #923](https://github.com/openshiftio/openshift.io/issues/923)[0], and more specifically, addresses the sub-task of unit tests for the Profile module.
The added unit tests attempt to cover the tenant component code, and checks the behaviour of each public function. I have a branch where I've got some code-coverage reports displaying [1], and have used it to display some metrics regarding the coverage improvements of this PR.
Coverage before this PR:
Coverage after this PR:
Coverage after this PR + the other two PRs in progress:
[1] https://github.com/aptmac/fabric8-ui/commit/d0a4cca0d9bf59f16c4ced70f870546ecb4a5227
> test(tenant): add unit tests for tenant.component

- src/app/dashboard-widgets/recent-pipelines-widget/recent-pipelines-widget.component.html
- src/app/dashboard-widgets/recent-pipelines-widget/recent-pipelines-widget.component.ts
https://github.com/openshiftio/openshift.io/issues/1048
The "Recent Active Pipelines" links are currently constructed from the buildconfig namespace, space label, and path to pipelines page ("/create/pipelines"). This does not work for users whose buildconfig namespace is different from their OSIO username - namely, users who log in with an email address. For example, in my case, my OSIO username is "aazores@redhat.com" and my namespace is "aazores". A correct Pipelines page URL for me is "openshift.io/aazores@redhat.com/test-space/create/pipelines", not "openshift.io/aazores/test-space/create/pipelines". The first commit corrects the router link to use the OSIO username rather than buildconfig namespace. The second commit performs some code cleanup that makes no behaviour change.
> Correct "Recent Active Pipelines" links

- src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.html
- src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.ts
fixes https://github.com/openshiftio/openshift.io/issues/2334
See also https://github.com/fabric8-ui/fabric8-ui/pull/2589 , which is very similar. In this component the `contextPath` already contains the current space, whereas on the homepage for the component in #2589, the buildconfig space label must also be used to construct the path (since there is no active space on the homepage).
> fix(pipelines): correct application pipelines link URL

- src/app/profile/spaces/spaces.component.spec.ts
This PR addresses [issue #923](https://github.com/openshiftio/openshift.io/issues/923)[0], and more specifically, addresses the sub-task of unit tests for the Profile module.
The added unit tests attempt to cover the spaces component code, and checks the behaviour of each public function. I have a branch where I've got some code-coverage reports displaying [1], and have used it to display some metrics regarding the coverage improvements of this PR.
Coverage before this PR:
Coverage after this PR:
Coverage after this PR + the other two PRs in progress:
[1] https://github.com/aptmac/fabric8-ui/commit/d0a4cca0d9bf59f16c4ced70f870546ecb4a5227
> test(spaces): add unit tests for spaces.component

- config/karma.conf.js
- src/app/layout/about-modal/about-modal.component.html
- src/app/layout/about-modal/about-modal.component.spec.ts
This PR addresses [issue #923](https://github.com/openshiftio/openshift.io/issues/923)[0], and more specifically, addresses the sub-task of unit tests for the about-modal.
The unit tests for the about-modal were disabled [1] during an update to the project dependency update [2]. This PR tweaks the .spec file so the unit tests run again, updates the date in the about-modal to be 2018, and proxies the assets folder in the karma.conf so that PhantomJS doesn't crash when it is looking for the image files during the running of the unit tests.
[1] https://github.com/fabric8-ui/fabric8-ui/commit/9a069f83b8146b195bed81841f953cde6527ed09
[2] https://github.com/fabric8-ui/fabric8-ui/pull/2105
> test(about-modal): re-enable tests for about-modal

- src/app/profile/update/update.component.spec.ts
This PR addresses [issue #923](https://github.com/openshiftio/openshift.io/issues/923)[0], and more specifically, addresses the sub-task of unit tests for the Profile module.
The added unit tests attempt to cover the update component code, and checks the behaviour of each public function. I have a branch where I've got some code-coverage reports displaying [1], and have used it to display some metrics regarding the coverage improvements of this PR.
Coverage before this PR:
Coverage after this PR:
Coverage after this PR + the other two PRs in progress:
[1] https://github.com/aptmac/fabric8-ui/commit/d0a4cca0d9bf59f16c4ced70f870546ecb4a5227
> test(update): add additional unit tests for update.component

- src/app/dashboard-widgets/environment-widget/environment-widget.module.ts
- src/app/space/create/deployments/apps/deployment-details.component.spec.ts
- src/app/space/create/deployments/apps/deployment-details.component.ts
- src/app/space/create/deployments/deployments.module.ts
- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
This patch set relates to https://github.com/openshiftio/openshift.io/issues/2253 . The goal of these patches is to simplify the DeploymentsService interface by removing the distinction between historical and streaming series data - consumers should be able to simply ask for series data, and it's the service's responsibility to decide what that data is. In this case, the service will decide to include 15 minutes' worth of stats immediately on the stream, and then continue publishing data on the same stream according to the service's own polling cycle to update the consumer with live results. This "front loading" of 15 minutes' worth of data is done on-demand per <space, app, env> tuple so that multiple consumers do not trigger multiple front-loading requests, and the last 15 data points …
> Deployments service refactor

- src/app/space/wizard/space-wizard.component.ts
This fixes the observable used to create a space in the space-wizard. It now is used once and cleaned up via `first()`. As well, the code is updated to use the latest API from `SpaceServices` as the previous API was deprecated.
This also addresses [1], where logging out would trigger another attempt to create the space because of the long-living observable receiving an event emission when logging out (user changes).
[1] https://github.com/openshiftio/openshift.io/issues/2206
> fix(space-wizard): make request to create space once

- src/app/space/create/pipelines/pipelines.component.spec.ts
- src/app/space/create/pipelines/pipelines.component.ts
BuildConfigs do not contain expected "app" and "codebase" labels, which the Pipelines component
expects to be present and uses for filtering and sorting pipelines by their Application and
Codebase. The "id" and "gitUrl" properties of the BuildConfig are used instead.
fixes https://github.com/openshiftio/openshift.io/issues/2405
Also included are some code cleanup commits for the component.
Working on tests now, but since this is a small wrapper around a runtime-console component, it's taking a lot of time to mock up all of the runtime-console dependencies. I'll probably end up replacing the actual runtime-console child component(s) with mocks, so the only meaningful parts behind the test will have to do with this component's filtering and sorting.
> fix(pipelines): fix pipeline filtering and sorting

- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
This addresses the UI portion for [1] and relies on the backend PR [2] to be merged first.
The deployment card quota information will now be deployment specific instead of the environment quota. See [1] for more information.
[1]
https://github.com/openshiftio/openshift.io/issues/2183
[2]
https://github.com/fabric8-services/fabric8-wit/pull/1922
> fix(deployments): add pod quotas service and use it in deployment cards

- src/app/space/create/deployments/services/deployments.service.spec.ts
Not sure how this didn't get caught on the original PR. This brings the test's expected values in line with the mocked responses.
> test(deployments): correct DeploymentsService test expected values

- package.json
This fixes an issue with the fabric8-ui build running too slow.
The ngx-forge package now uses tree shaking to reduce the ngx-forge.js bundle size by half. Thus, the build no longer appears to hang while Angular resolves duplicates.
> app-launcher: build slow due to ngx-forge.js bundle size

- src/app/profile/cleanup/cleanup.component.spec.ts
This PR addresses [issue #923](https://github.com/openshiftio/openshift.io/issues/923)[0], and more specifically, addresses the sub-task of unit tests for the Cleanup component under the Profile module.
The added unit tests attempt to cover the cleanup component code, and checks the behaviour of each public function. 
> test(cleanup): add unit tests for cleanup.component

- src/app/profile/my-spaces/my-spaces-toolbar/my-spaces-toolbar.component.spec.ts
- src/app/profile/my-spaces/my-spaces-toolbar/my-spaces-toolbar.component.ts
- src/app/profile/my-spaces/my-spaces.component.ts
This fixes the my-spaces toolbar to update results count. Closes https://github.com/openshiftio/openshift.io/issues/2466
The patch also makes a variable used in the html public instead of private as suggested by angular language service. Some more discussion and links to further discussion on it here: https://stackoverflow.com/questions/45520838/identifier-refers-to-a-private-member-of-the-component/45521099#45521099
> fix(my-spaces): fix toolbar result count

- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card.component.ts
- src/app/space/create/deployments/deployments.component.ts
- src/app/space/create/deployments/services/deployment-status.service.spec.ts
- src/app/space/create/deployments/services/deployment-status.service.ts
targeting https://github.com/openshiftio/openshift.io/issues/2519
This PR adds a new service, `DeploymentStatusService`, which provides information about the status of a deployment. Currently this status only reflects resource usage vs quota for CPU and Memory metrics, but the intent is for it to evolve and provide status information for all deployment failure modes (see https://github.com/openshiftio/openshift.io/issues/2086). This is implemented as a separate service building on top of the existing `DeploymentsService` since it's at a higher conceptual abstraction level, and to avoid growing the already very large DeploymentsService any further.
This new DeploymentStatus service incorporates the pre-existing logic that was contained in the DeploymentCardComponent to set the card icon …
> Memory usage warning

- package.json
- Modified ngx-forge package module to use index.js instead of ngx-forge.js bundle
- Module changes (along with tree shaking) should help fabric8-ui build performance because Angular isn’t resolving duplicates.
- Allows fabric8-ui to install its own dependencies instead of packages being duplicated by the ngx-forge.js bundle.
- Eliminates the ‘multiple mobx instances’ error seen with fabric8-ui unit tests, since certain dependencies are duplicated by the ngx-forge.js bundle.
Fixes: https://github.com/openshiftio/openshift.io/issues/2461
Changes to ngx-forge can be seen here: https://github.com/fabric8-launcher/ngx-launcher/pull/96
> fix(app-launcher): modified ngx-forge package module to use index.js

- src/app/profile/overview/overview.component.html
Fixes a bug in [PR](https://github.com/fabric8-ui/fabric8-ui/pull/2489).
- Found a bug in the logic of showing email based on private/public status of user.
- Since we're using conditional ng-template already, *ngIf on ng-template doesn't work. [Refer](https://stackoverflow.com/questions/44837756/why-ngif-doesntwork-with-ng-template)
- So, moved *ngIf to p tag inside of ng-template instead.
- Also, we don't need the condition for addEmail element since that will never be shown if user has an email.
> fix(profile): show email on profile overview page if email is public

- src/app/profile/overview/connected-accounts/connected-accounts.component.html
- src/app/profile/overview/connected-accounts/connected-accounts.component.spec.ts
- src/app/profile/overview/connected-accounts/connected-accounts.component.ts
- src/app/shared/account/provider.service.ts
Related to https://github.com/fabric8-services/fabric8-auth/issues/320
- Adds getOpenShiftStatus()  in providerService to get auth token with new param `force_pull=true`.
- Adds updateOpenShiftStatus() in connected-accounts.component which gets called in ngOnInit()
- Updated test cases for the above changes.
> fix(profile): Verify OSO token status while retrieving OSO token in profile overview

- src/app/space/create/deployments/apps/deployment-details.component.spec.ts
- src/app/space/create/deployments/apps/deployment-details.component.ts
https://github.com/openshiftio/openshift.io/issues/2521
This patch causes the Y axis for the CPU and Memory Sparkline charts to be scaled so that the maximum value of the axis is the largest of the usage and quota values for the metric over the sampling window, rather than simply the largest usage value. The change in behaviour is documented in the linked issue.
> Scale Deployments chart Y axes to quotas

- src/app/space/create/deployments/apps/deployment-card.component.html
- src/app/space/create/deployments/apps/deployment-card.component.less
- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card.component.ts
- src/app/space/create/deployments/apps/deployment-details.component.html
- src/app/space/create/deployments/apps/deployment-details.component.less
- src/app/space/create/deployments/apps/deployment-details.component.spec.ts
- src/app/space/create/deployments/apps/deployment-details.component.ts
- src/app/space/create/deployments/resource-usage/utilization-bar.component.html
- src/app/space/create/deployments/resource-usage/utilization-bar.component.less
- src/app/space/create/deployments/resource-usage/utilization-bar.component.spec.ts
- src/app/space/create/deployments/resource-usage/utilization-bar.component.ts
https://github.com/openshiftio/openshift.io/issues/2520
These patches modify the Deployments page deployment and resource usage cards to show more warning/error indicators when resources are nearing quotas, as shown in the updated designs docs linked in the above issue.
Before, without warning:
Before, with warning (forced by setting warning threshold to 10% in local build):
After (forced warning in local build):
(After without warning looks identical to Before without warning)
One difference in the implemented "After" screenshot vs the design is the size of the warning "ribbon" on a deployment card's left edge. In the design mock this ribbon is the full height of the card component. In the actual implementation, it is only the height of the inner card content component. This is because …
> Deployments warning indicators

- src/app/space/create/deployments/apps/deployment-graph-label.component.html
fixes https://github.com/openshiftio/openshift.io/issues/2541
This uses the Angular "number" pipe (`DecimalPipe`: https://angular.io/api/common/DecimalPipe) to display a maximum number of fraction digits so that numbers like 2.0000001 don't force the text too wide for the card width.
> fix(deployments): truncate graph labels for width constraint

- src/app/profile/my-spaces/my-spaces.component.spec.ts
This PR addresses https://github.com/openshiftio/openshift.io/issues/2552 [0], in which the unit tests that I added for the my-spaces component [1] introduced compilation errors into the project build. 
There are parts of the my-spaces.component code that append values to objects (`Space`, `ExtProfile`) if undefined (`showPins` gets added to a `Space`, `contextInformation` gets added to `ExtProfile`). Some of the tests I wrote attempted to verify this behaviour [2], and use ts-ignore comments to hide errors (which worked in the IDE, but not during the build). 
To amend this issue, the mock returned from `createTransientProfile()` is now an `ExtProfile` instead of `Profile`, which was an oversight I made when writing the .spec file. The types for `Spaces` have now been converted to `any`, …
> fix(my-spaces): fix compiliation errors in my-spaces.component.spec

- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.html
- src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.spec.ts
I need to add some ids to the Deployments page for E2E testing. I've tried to do it myself but I am not sure if it works correctly and/or it is done right. So, any inputs would be appreciated.
> Added ids to pod status entires.

- config/webpack.common.js
- config/webpack.dev.js
- src/index.ejs
This PR addresses the warnings in the console when running a local version of f8-ui. This is resolved in two parts: the `ContextReplacementPlugin` regex needed to be updated [0], and there were 5 dependencies that needed to be excluded in the webpack source-map-loader.
Additionally, there was a an extra comma at the end of the name tag in `index.ejs` which was causing the 
> "The key "" is not recognized and ignored."
warning, and this persists in production so this fix should clean up the console. 
Here are a couple of screen-shots to show what my console looked like before and after this PR:
Before (there were 12 of these warning messages):
After:
[0] https://github.com/angular/angular/issues/11580#issuecomment-367296829
> fix(webpack): resolve webpack sourcemap and dependency warnings

- src/app/space/create/deployments/apps/deployment-card.component.html
Use "x | async as y" syntax rather than "x | async; let y" for better readability
> style(deployments): use "as" template syntax

- package.json
- src/app/space/settings/areas/areas-toolbar/areas-toolbar.component.html
- src/app/space/settings/areas/areas-toolbar/areas-toolbar.component.less
- src/app/space/settings/areas/areas-toolbar/areas-toolbar.component.spec.ts
- src/app/space/settings/areas/areas-toolbar/areas-toolbar.component.ts
- src/app/space/settings/areas/areas-toolbar/areas-toolbar.module.ts
- src/app/space/settings/areas/areas.component.html
- src/app/space/settings/areas/areas.component.less
- src/app/space/settings/areas/areas.component.ts
- src/app/space/settings/areas/areas.module.ts
- src/vendor.browser.ts
Replaced the existing list with pfng-tree-list to better show hierarchical areas. Also added a toolbar with filter/sort/add controls and spec.
Note: This updates patternfly-ng to 3.1.2 since the current version is missing CSS styles.
Fixes: https://github.com/fabric8-ui/fabric8-ux/issues/835
> Hierarchical areas

- src/app/layout/header/header.component.ts
Fixes https://github.com/openshiftio/openshift.io/issues/2698
The header.component is missing the function `onDocumentationListVisible()`[0] which similar to `onStatusListVisible` should toggle a boolean variable when the dropdown is shown. This PR adds the function and associated boolean variable.
[0] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/layout/header/header.component.html#L134
> fix(header): fix onDocumentationListVisible is not a function error

- src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.component.html
- src/app/space/create/codebases/codebases-item-details/codebases-item-details.component.html
- src/app/space/create/codebases/codebases-item-details/codebases-item-details.component.spec.ts
- src/app/space/create/codebases/codebases-item-details/codebases-item-details.component.ts
- src/app/space/create/codebases/codebases-item/codebases-item.component.html
- src/app/space/create/codebases/codebases.component.spec.ts
- src/app/space/create/codebases/codebases.component.ts
- src/app/space/create/codebases/services/github.service.spec.ts
- src/app/space/create/codebases/services/github.service.ts
Handle case where a GitHub repo has been deleted without being removed from a Space by sending a
notification and continuing to process other codebases in the space
fixes https://github.com/openshiftio/openshift.io/issues/2548
The root of the problem is that a Codebase's GitHub repository may disappear, but the existing logic in this component assumes that all Codebases will have a valid GitHub link.
When a repo is deleted the GitHubService `getRepoDetailsByUrl` requests for the repository's URL will fail with a 404. This becomes an error emission on the returned Observable. The component tries to fetch details for all of its known Codebases, which is done sequentially. If any of these requests fail and emits an error then the `Observable.forkJoin` errors out early as well, emitting no …
> fix(codebases): handle missing GitHub repos

- src/app/profile/overview/spaces/spaces.component.spec.ts
This PR addresses [issue #923](https://github.com/openshiftio/openshift.io/issues/923)[0], and specifically address the checkbox of unit tests for the profile overview spaces component.
Here's an image showing the test coverage for the component.
> test(spaces): add unit tests for the profile spaces component

- src/app/space/create/deployments/resource-usage/resource-card.component.html
- src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts
- src/app/space/create/deployments/resource-usage/resource-card.component.ts
Fixes https://github.com/openshiftio/openshift.io/issues/2735
The resource cards are always shown. This was actually the initial behavior and then code was added (I think by me) to hide it if there were 0 deployments. The code is removed.
> fix(deployments): always show resource card

- src/app/profile/overview/overview.component.spec.ts
This PR addresses [issue #923](https://github.com/openshiftio/openshift.io/issues/923)[0], and specifically address the checkbox of unit tests for the overview component.
The spec file covers all lines of code and functions, but misses a couple branches (although I'm not sure why).
> test(overview): add unit tests for the overview component

- src/app/profile/cleanup/cleanup.component.html
On Reset Environment page, changed:
"...reverting your OpenShift.io environment to it's default state."
to:
"...reverting your OpenShift.io environment to its default state."
> fix(cleanup): fixed typo on cleanup page (it's -> its)

- package.json
Introduces ngrx planner. Overall the planner will work much faster.
The board view has **not** been moved to ngrx.
> fix(version): update fabric8-planner to 0.43.5

- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
Fixes https://github.com/openshiftio/openshift.io/issues/2814
This increases the defensiveness of the deployments service by encoding the urls for the requests.
Currently OSIO doesn't seem to have a path that allows users to insert special characters into their application names and I imagine the same would occur if/when environments are user created rather than static names (run/stage). Space id is also a UUID. However on the off-case someone manages to got a special character in, we will be protected.
GitHub also replaces all special characters with '-' character so I haven't been able to recreate a scenario where this affects the service.
> fix(deployments): encode urls

- src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html
- src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.spec.ts
- src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.ts
- src/app/space/forge-wizard/abstract-wizard.component.ts
- src/app/space/forge-wizard/import-wizard.component.ts
- src/app/space/forge-wizard/quickstart-wizard.component.ts
This PR adds a feature to the Codebases widget on the space "Analyze" dashboard so that upon completing the "Add to space" wizard, a newly imported or created codebase will be automatically displayed in the widget rather than requiring the page to be reloaded. This solves the problem of the widget becoming stale whenever the wizard is used and completed by a user within the same Analyze tab, but does not solve the problem of the widget becoming stale if the wizard is completed in a different tab, by a different user, etc., or if a Codebase is added to the Space via some other manner than the wizard.
This required a TODO for adding a Broadcast in the wizard to be completed as well (first commit in the series) - this can be easily removed from this PR so that an owner of the wizard …
> Codebases dashboard widget updates immediately after forge wizard completion

- src/app/space/forge-wizard/components/flow-selector/flow-selector.component.html
Updates anchor text to trigger new Launcher flow.
Issue : https://github.com/openshiftio/openshift.io/issues/2832
> fix(launcher): updated anchor text for launcher experience

- src/app/space/app-launcher/services/app-launcher-gitprovider.service.ts
- removes isPageRedirect method as not needed in app-launcher-gitprovider.service.ts
> fix(launcher): removes isPageRedirect method as not needed

- config/webpack.common.js
- config/webpack.prod.js
- package.json
Fixes https://github.com/openshiftio/openshift.io/issues/2915
Removed `webpack-md5-hash` from prod build as there are outstanding issues with the generated hash not changing when file contents changes.
> fix(cache): update webpack file name hashing strategy

- src/app/space/forge-wizard/components/flow-selector/flow-selector.component.html
- updates text to trigger getting started experience as internal feature
Issue link : https://github.com/openshiftio/openshift.io/issues/2832
> fix(launcher): updates text to trigger getting started experience

- src/app/space/create/pipelines/pipelines.component.html
- src/app/space/create/pipelines/pipelines.component.spec.ts
- src/app/space/create/pipelines/pipelines.component.ts
- src/app/space/create/pipelines/services/pipelines.service.spec.ts
- src/app/space/create/pipelines/services/pipelines.service.ts
Fixes https://github.com/openshiftio/openshift.io/issues/2229
Adds a service to acquire openshift console url from WIT /api/user/services and uses it. Tested with account in 2 and account in 2a.
> Fix pipelines console link to be acquired dynamically

- config/webpack.common.js
- config/webpack.prod.js
Moves the changes made for openshiftio/openshift.io#2915 from `webpack.common.config` to `webpack.prod.config` as to not have any affect on the dev server.
> fix(config): move 2x plugins from webpack common to prod config

- src/app/space/create/deployments/deployments.module.ts
- src/app/space/create/deployments/services/deployment-api.service.spec.ts
- src/app/space/create/deployments/services/deployment-api.service.ts
Add a new DeploymentApiService which simply wraps Deployments WIT endpoints, for non-Deployments
page UI consumers.
fixes https://github.com/openshiftio/openshift.io/issues/2924
> feat(deployment-api): introduce DeploymentApiService

- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/layout/header/header.component.spec.ts
- src/app/layout/header/header.component.ts
fixes https://github.com/openshiftio/openshift.io/issues/2731
This patch adds a small handler to replace the browser's location/state with the attempted URL rather than the path to the _error state, so that the user can more easily see or report what URL they tried to visit and which failed. The approach taken is to replace the browser's location state using the Angular Location service since all other approaches tried using various router functions still resulted in the browser location state being updated for the routed _error state, or resulted in the URL remaining what it was before an invalid link was clicked. Additionally the HeaderComponent is modified to check if the current router state is _error, and if so, to return a falsy (in this case, null) Context, so that the header …
> Preserve visited URL when routing to _error (404) state

- src/app/space/create/deployments/services/deployment-api.service.spec.ts
- src/app/space/create/deployments/services/deployment-api.service.ts
- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
https://github.com/openshiftio/openshift.io/issues/2925
This PR refactors the DeploymentsService to move the scalePods and deleteDeployments functions into DeploymentApiService, removing all direct HTTP knowledge from DeploymentsService so that it is entirely built on top of the generalized and simplified DeploymentApiService and only implements functionality to enable the Deployments page components to be as simple and dumb as possible.
> Refactor DeploymentsService to use DeploymentApiService

- src/app/dashboard-widgets/recent-workspaces-widget/recent-workspaces-widget.component.spec.ts
- src/app/dashboard-widgets/recent-workspaces-widget/recent-workspaces-widget.component.ts
This fixes a TypeError warning generated by the RecentWorkspacesWidgetComponent unit test when the openWorkspace method of WorkspacesService is called.
> Fix TypeError warning generated by unit test

- package.json
There is a jump in the version number as a few PRs related to CI/CD were merged.
> fix(version): update fabric8-planner to 0.43.22

- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/layout/error/error.component.spec.ts
- src/app/layout/error/error.component.ts
- src/app/layout/error/error.service.ts
- src/app/shared/context-resolver.service.ts
- src/app/shared/context.service.spec.ts
- src/app/shared/context.service.ts
https://github.com/openshiftio/openshift.io/issues/2887
https://github.com/openshiftio/openshift.io/issues/2860
~~This is a work in progress for prototyping 404/_error page routing work. The homepage component gains several "error n" links in the banner under "Setup your profile", which exercise various types of failure modes with different sorts of invalid URLs. These can be clicked to manually test the behaviour of the prototype when visiting an invalid URL. Once on that page, the browser can be refreshed to also simulate the behaviour of entering that invalid URL directly into the address bar, as opposed to visiting it from within the running application.~~
This PR modifies the context resolution and routing behaviour so that the behaviour of an invalid application link, including …
> Consistently route to 404 page when visiting invalid links

- src/app/dashboard-widgets/environment-widget/environment-widget.component.ts
- src/app/space/create/deployments/apps/deployment-details.component.spec.ts
- src/app/space/create/deployments/apps/deployment-details.component.ts
- src/app/space/create/deployments/models/cpu-stat.ts
- src/app/space/create/deployments/models/memory-stat.ts
- src/app/space/create/deployments/models/network-stat.ts
- src/app/space/create/deployments/models/pods.ts
- src/app/space/create/deployments/models/scaled-memory-stat.ts
- src/app/space/create/deployments/models/scaled-net-stat.spec.ts
- src/app/space/create/deployments/models/scaled-net-stat.ts
- src/app/space/create/deployments/models/scaled-stat.ts
- src/app/space/create/deployments/models/stat.ts
- src/app/space/create/deployments/services/deployment-api.service.spec.ts
- src/app/space/create/deployments/services/deployment-api.service.ts
- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
See initial commit message or linked issue for more detail, but the gist is that these interfaces should be moved closer to the functions that produce them as return types, for general cleanliness but also to create a clearer separation for "internal to Deployments" (DeploymentsService) and "external for Deployments consumers" (DeploymentApiService and these interfaces).
> Move interfaces out of deployments.service.ts

- src/app/dashboard-widgets/environment-widget/application-overview.service.spec.ts
- src/app/dashboard-widgets/environment-widget/application-overview.service.ts
- src/app/dashboard-widgets/environment-widget/environment-widget.component.ts
- src/app/space/create/deployments/services/deployments.service.ts
This refactors the EnvironmentWidget found on the current Analyze dashboard to remove its dependency on the DeploymentsService, which is intended to be consumed only by Deployments-area components. The function and structures that were previously added to the DeploymentsService to support this widget have been moved into a new, very small service, which is specific to the EnvironmentWidget, and which uses the new DeploymentApiService to handle HTTP requests to the backend Deployments API.
> Refactor EnvironmentWidget to remove DeploymentsService dependency

- src/app/feature-flag/warning-page/feature-warning-page.component.html
- src/app/feature-flag/warning-page/feature-warning-page.component.ts
This patch changes the route used by the feature warning page to redirect users to the feature opt in page under their profile settings, instead of their profile.
Fixes: https://github.com/openshiftio/openshift.io/issues/3260
> fix(settings): Redirect user to appropriate feature opt in page

- src/app/space/create/pipelines/pipelines.component.spec.ts
- src/app/space/create/pipelines/pipelines.component.ts
This is a workaround to fix: https://github.com/openshiftio/openshift.io/issues/2744
The race condition affecting the build configs system is untouched and instead the URLs are injected into the objects to be used throughout the pipelines code.
After many days of investigation and attempts at solutions to the race condition affecting this pipelines component, I opted for this workaround as it fixes the issue of links being wrong while being the least intrusive as possible. This was manually tested against an intentionally delayed ngx-login-client:UserService with:
```
this.loggedInUser = Observable.merge(
broadcaster.on('loggedin')
.map(val => 'loggedIn'),
broadcaster.on('logout')
.map(val => 'loggedOut'),
broadcaster.on('authenticationError')
.map(val => 'authenticationError')
) …
```
> fix(pipelines): inject openshift urls into build configs

- src/a-runtime-console/kubernetes/kubernetes.store.module.ts
- src/a-runtime-console/kubernetes/store/oauth-config-store.spec.ts
- src/a-runtime-console/kubernetes/store/oauth-config-store.ts
- src/app/app.module.ts
- src/app/bootstrap/bootstrap.module.ts
- src/app/bootstrap/bootstrap.service.ts
This adds a bootstrap module which provides an `APP_INITIALIZER` promise that Angular will guarantee to wait for before continuing past initialization.
The oauth-config-store is added such that the oauth-config-store http request must complete before continuing past initialization. This fixes https://github.com/openshiftio/openshift.io/issues/2200
As well, the oauth-config-store is refactored to subscribe to the UserService loggedInUser observable to be robust against https://github.com/openshiftio/openshift.io/issues/3161 Tests are added as well.
Note: This is one solution for https://github.com/openshiftio/openshift.io/issues/2200 It doesn't address the fact that the websocket code is written strangely to repeatedly, and infinitely try to connect to some url, even if it fails. It only …
> feat(bootstrap): add bootstrap module and update OauthConfigStore

- cico_build_deploy.sh
When the build script is executed twice, the clean builder container
directives don't work and it fails on a second attempt.
> Fixes bug in second pass of build script

- src/app/app-routing.module.ts
- src/app/layout/header/menus.service.spec.ts
- src/app/layout/header/menus.service.ts
Board view is removed temporarily till the summit. After that board view is likely to be refactored and added back with a new design and a number of new features. 
Related issue - https://openshift.io/openshiftio/openshiftio/plan/detail/1945
> fix(planner): board view navigation is removed temporarily

- src/app/profile/overview/spaces/spaces.component.less
This one-line fix adjusts the height of the `spaces-list-scroll` on the profile my spaces widget to match the height of the card it's placed in. Currently, if the user has a large number of spaces then some will be not visible on the widget due to overflowing off the bottom of the visible portion of the widget.
Currently, the max-height value for the `spaces-list-scroll` is 675px, but the max-height of a `f8-card` is 375px [0], and the max-height of a `f8-card-list` is 375px [1]. This fix changes the height of the `spaces-list-scroll` to inherit, so that it can properly fill the space it's put into.
Example: the widget isn't showing all of my pages, and the bottom of the scrollbar isn't visible
With this adjusted max-height value, the list now fits the height of the widget and displays …
> fix(profile): fix spaces component height to show all spaces

- Dockerfile.deploy.rhel
- cico_build_deploy.sh
- openshift/fabric8-ui.app.yaml
This commit reapplies the RHEL configuration that was removed in a
previous commit.
**IMPORTANT**: before merging this PR, merge first:
- https://github.com/openshiftio/openshiftio-cico-jobs/pull/631
- https://github.com/openshiftio/saas-openshiftio/pull/831
By merging this PR and the two described above, the RHEL based f8-ui
will be deployed in staging.
> Reapply RHEL enablement

- cico_build_deploy.sh
Reenables semantic-release, but it doesn't stop execution if it fails.
This request is explained in this commit:
9d371c96675a61e8bb7feee9557aee969c1caf83
> Continue execution if semantic-release fails

- src/app/space/add-space-overlay/add-space-overlay.component.less
addresses https://github.com/openshiftio/openshift.io/issues/3341
This small stylesheet fix changes the font colour of the option dropdown in the add-space-overlay. 
Currently in Chrome (on Windows & Fedora) the select dropdown displays white text on a white background, which makes it impossible to read the non-highlighted options.
Here, the option text will be coloured black, and will show up on the white background.
Before:
After:
> fix(add-space-overlay): fix option font colour

- src/app/app-routing.module.ts
- src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html
- src/app/layout/header/header.component.spec.ts
- src/app/layout/header/header.component.ts
This PR stems from the discussion of a previous PR regarding the [add-work-items and add-codebases router outlets](https://github.com/fabric8-ui/fabric8-ui/pull/2794) [0].
This PR accomplishes two things:
1. Fixes the header highlighting when navigating between pages with an active 'add-codebase' router action [1]
- This can currently only occur in feature-level == production because any feature-level above and the slider is replaced with the newer overlay
- If the slider is open on the codebases page and the user switches to the pipelines page, the header doesn't update to display the pipelines page as the active page
2. Removes the Import Codebases button from the codebases widget [2][3]
- The import codebases button is displayed only in feature-level == production, and can cause a 404 …
> fix(add-codebase): fix header highlighting when navigating pages with action, and remove add-codebase button from codebases widget

- src/a-runtime-console/kubernetes/store/oauth-config-store.spec.ts
- src/a-runtime-console/kubernetes/store/oauth-config-store.ts
This addresses the oauth-config-store error reported in https://github.com/openshiftio/openshift.io/issues/3347
The `first()` predicate check now also checks for `undefined` and `null` instead of just `null`.
A test was added, however, in test runs it strangely throws an EmptyError. In actual runs, visiting /openshiftio/openshiftio while not logged in, no error is thrown. Prior to the fix, the test run error would be the stacktrace of 'can't access undefined...' so it's still a valuable test. If anyone has ideas what could be causing the EmptyError, I'd greatly appreciate the input!
> fix(a-runtime-console): also check for undefined user values in oauth-config-store

- src/app/layout/header/header.component.html
Update the text in the user dropdown from 'Chat' to 'Chat with us' in order to match the landing page button.
related to https://github.com/openshiftio/openshift.io/issues/3327
> update chat text to match landing page

- src/app/space/create/pipelines/pipelines.component.less
This short PR addresses some warnings from the linter that were a result of using 4 spaces instead of 2 spaces in `pipelines.component.less` during a recent commit [0].
[0] https://github.com/fabric8-ui/fabric8-ui/commit/8d84c75ff96ead2d5f544887ef7164c02a0ff66c#diff-69a04fcac923bf32cf38f013802660fe
> fix(linting): fix pipelines component less indentation

- src/app/space/create/deployments/apps/deployment-details.component.ts
- src/app/space/create/deployments/deployments.module.ts
- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
This PR modifies the DeploymentsService timeseries Observables' logic so that deployments which "reappear", ex. gaining a deployment in a new environment (promotion to "run") or scaling up from 0 pods, receive timeseries stats updates for CPU, Memory, and Network usage. Prior to these patches there is a bug where the timeseries stats will never be updated in these situations, as documented [here](https://github.com/openshiftio/openshift.io/issues/3454).
This PR also includes a patch to ensure that the correct chart component object is updated when these events occur, otherwise it is possible for the first such updated series may set appearance properties on an outdated and invalid chart object.
> fix(deployments): reappearing deployments continue updates

- src/app/profile/my-spaces/my-spaces.component.html
- src/app/profile/my-spaces/my-spaces.component.spec.ts
- src/app/profile/my-spaces/my-spaces.component.ts
- src/app/profile/my-spaces/my-spaces.module.ts
Enable new Space overlay with feature flag. Previously only displayed old-style Forge wizard.
fixes https://github.com/openshiftio/openshift.io/issues/3576
I wonder if the feature flag directive should be included however, or if the button should simply unconditionally open the new overlay. I believe that overlay is now enabled in production anyway. See also https://github.com/openshiftio/openshift.io/issues/3629 .
> fix(my-spaces): enable new Space overlay

- src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html
- src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.spec.ts
- src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.ts
- src/app/space/analyze/analyze-overview/analyze-overview.component.html
As a follow up to #2898, this patch both hides undesirable functionality from the add-codebase-widget and removes the now outdated app launcher feature flag from its HTML structure. 
Here's a screenshot : 
_In my space_
_In a foreign user space_
> Hide buttons from add-codebase-widget when in a foreign user space. 

- src/app/profile/settings/feature-opt-in/feature-opt-in.component.html
- src/app/profile/settings/feature-opt-in/feature-opt-in.component.spec.ts
- src/app/profile/settings/feature-opt-in/feature-opt-in.component.ts
The first commit in this PR addresses https://github.com/openshiftio/openshift.io/issues/3590 , blocking events that deselect feature levels from the Settings > Feature Opt-In component, adds a test for this behaviour, and does some slight test restructuring. The second commit cleans up the spec file further. The third cleans up a bunch of boilerplate from the template.
> fix(settings): do not allow deselection of feature levels

- package-lock.json
- package.json
NOTE - The changes to package-lock.json are a result of `npm install`. The transitive dependencies have been updated because `rh-ngx-datatable` version is updated in planner.
> fix(version): Update planner version to 0.48.1

- src/app/space/add-space-overlay/add-space-overlay.component.spec.ts
- src/app/space/add-space-overlay/add-space-overlay.component.ts
Fixes https://github.com/openshiftio/openshift.io/issues/3481
Fixes https://github.com/fabric8-services/fabric8-auth/issues/499
This patch fixes errors after creating a space and logging out immediately.
- createSpace() was subscribing to userService.getUser() and then calling spaceService.create() inside it which resulted in an error if user logs out.
- Added loggedInUser var for storing user context in the constructor of the component.
> fix(space-creation): fixes errors after space creation and logout

- src/app/profile/update/update.component.spec.ts
- src/app/profile/update/update.component.ts
Fixes https://github.com/openshiftio/openshift.io/issues/3708
Fixes https://github.com/openshiftio/openshift.io/issues/3701
Fixes https://github.com/fabric8-services/fabric8-auth/issues/508
Fixes https://github.com/fabric8-services/fabric8-auth/issues/509
Fixes a few validations in profile update page.
- Profile Bio cannot be removed or set to empty string.
- Company name cannot be removed.
- URL cannot be removed.
- URL validation is not working correctly. For example i can update URL to http:// and it gets updated.
- Also, removed imageUrlValidation since we don't take user input for that in new design.
> fix(profile-update): form validations fixed.

- config/webpack.dev.js
This PR addresses the (~25) warnings in the console when running a local version of f8-ui.
Additionally there was a duplication of the `ngx-modal` in the exclusion list, so I removed it and ordered the list alphabetically so it will be easier to spot duplication.
> fix(webpack): resolve ngx-forge sourcemap warnings

- src/app/dashboard-widgets/applications-widget/applications-widget.component.spec.ts
- src/app/feature-flag/resolver/feature-flag.resolver.spec.ts
- src/app/shared/owner-guard.service.spec.ts
- src/app/space/app-launcher/services/app-launcher-mission-runtime.service.spec.ts
This PR fixes the linting issues shown below.
```
fabric8-ui> npm run lint
> fabric8-ui@0.0.0-development lint fabric8-ui
> find src -name '*.ts' | xargs tslint -p . -c tslint.json --force
ERROR:fabric8-ui/src/app/dashboard-widgets/applications-widget/applications-widget.component.spec.ts[211, 53]: Spaces before function parens are disallowed
ERROR:fabric8-ui/src/app/dashboard-widgets/applications-widget/applications-widget.component.spec.ts[215, 47]: Spaces before function parens are disallowed
ERROR:fabric8-ui/src/app/dashboard-widgets/applications-widget/applications-widget.component.spec.ts[221, 53]: Spaces before function parens are disallowed
ERROR:fabric8-ui/src/app/dashboard-widgets/applications-widget/applications-widget.component.spec.ts[227, 51]: Spaces before function parens …
```
> Tslint fixes

- package-lock.json
This PR simply regenerates the package-lock.json file.
The continuous-integration build is currently failing due to security vulnerabilities. The master branch also fails to `npm install` locally without removing the package-lock.json.
> package-lock: updated due to security vulnerabilities

- src/app/dashboard-widgets/applications-widget/applications-widget.component.html
- src/app/dashboard-widgets/applications-widget/applications-widget.component.less
- src/app/dashboard-widgets/applications-widget/applications-widget.component.spec.ts
- src/app/dashboard-widgets/applications-widget/applications-widget.component.ts
- src/app/dashboard-widgets/applications-widget/applications-widget.module.ts
- src/app/dashboard-widgets/loading-widget/loading-widget.component.html
- src/app/dashboard-widgets/loading-widget/loading-widget.component.less
- src/app/dashboard-widgets/loading-widget/loading-widget.component.spec.ts
- src/app/dashboard-widgets/loading-widget/loading-widget.component.ts
- src/app/home/home.component.html
Show in-progress message for newly created applications. Also refactored the loading widget to accommodate additional messages and links.
Fixes: https://github.com/openshiftio/openshift.io/issues/3671
With no applications staged/running:
With staged application:
> Applications-widget: in-progress message for newly created apps

- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card.component.ts
- src/app/space/create/deployments/apps/deployment-details.component.spec.ts
- src/app/space/create/deployments/apps/deployment-details.component.ts
- src/app/space/create/deployments/resource-usage/resource-card.component.html
- src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts
- src/app/space/create/deployments/resource-usage/resource-card.component.ts
- src/app/space/create/deployments/resource-usage/utilization-bar.component.spec.ts
- src/app/space/create/deployments/resource-usage/utilization-bar.component.ts
- src/app/space/create/deployments/services/deployment-status.service.spec.ts
- src/app/space/create/deployments/services/deployment-status.service.ts
This PR refactors some logic out of the resource card/utilization bar components into the DeploymentStatusService. This keeps the component as dumb and presentational as possible, and is also useful in preparation for https://github.com/openshiftio/openshift.io/issues/3128 .
> Refactor environment card resource status

- src/app/space/app-launcher/services/app-launcher-dependency-check.service.spec.ts
- src/app/space/app-launcher/services/app-launcher-dependency-check.service.ts
Tracks: https://github.com/openshiftio/openshift.io/issues/2370
> fix(launcher): fails properly for continous hyphens or underscores in the application name.

- src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.module.ts
- src/app/dashboard-widgets/work-item-widget/work-item-widget.module.ts
- src/app/home/work-item-widget/work-item-widget.module.ts
- src/app/profile/overview/work-items/work-items.module.ts
What Does this Pr do?
`WorkItemDetailAddTypeSelectorModule` is removed from planner because we don't use this anymore.
> `WorkItemDetailAddTypeSelectorModule` is Deprecated

- src/app/space/analyze/analyze-overview/analyze-overview.component.html
- src/app/space/analyze/analyze-overview/analyze-overview.component.spec.ts
- src/app/space/analyze/analyze-overview/analyze-overview.component.ts
This patch resolves an issue in which the "create an application" button is mistakenly hidden when users visit their own space. It also introduces a lifecycle hook to ensure that angular re-evaluates whether the button should be shown when navigating immediately from one space to another.
Solves: https://github.com/openshiftio/openshift.io/issues/3702
> fix(analyze-overview): correctly hide create app button

- src/app/space/add-app-overlay/add-app-overlay.component.html
- src/app/space/app-launcher/services/app-launcher-dependency-check.service.spec.ts
- src/app/space/app-launcher/services/app-launcher-dependency-check.service.ts
This makes the front end restrict application names to also
- not have spaces
- not start with a number
This addresses
- https://github.com/openshiftio/openshift.io/issues/3516
- https://github.com/openshiftio/openshift.io/issues/3781
- https://github.com/openshiftio/openshift.io/issues/3784
> fix(app-launcher): disallow starting number and spaces in application name

- src/app/layout/header/header.component.less
- src/assets/stylesheets/shared/_animations.less
This small patch corrects the gradient direction and removes a white underline from the selected link of the principle navbar when viewing a space.
Preview:
> fix(header): correct gradient and underline in navbars

- src/app/space/create/deployments/services/deployment-api.service.spec.ts
- src/app/space/create/deployments/services/deployment-status.service.spec.ts
This PR cleans up the specs for the DeploymentApiService and DeploymentStatusService. The DeploymentsService clean up itself will come later since there's quite a bit more that can be done in there, so the patch series will probably be considerably larger.
> Service test cleanup

- src/app/space/create/pipelines/services/pipelines.service.spec.ts
- src/app/space/create/pipelines/services/pipelines.service.ts
This addresses the error notification that appears if you are not logged in and visit a space. It will not appear if you are not logged in. This makes an assumption that 'logged in' means there is an auth token in local storage (looking at how authentication service actually works). I think this is reasonable. If the auth token is invalid, it will still notify, which is nice.
This fixes https://github.com/openshiftio/openshift.io/issues/3347
Interestingly the auth token service implementation returns the value in local storage or the empty string so in theory it will never be null. I think there's a few http services that do a null check on the getToken function; they should also probably not add the header if the return value is an empty string. Alternatively, the auth service should …
> fix(pipelines): do not emit error if 401 recieved when not logged in

- src/app/space/create/codebases/codebases-toolbar/codebases-toolbar.component.spec.ts
- src/app/space/create/codebases/codebases-toolbar/codebases-toolbar.component.ts
- src/app/space/create/codebases/codebases.component.spec.ts
- src/app/space/create/codebases/codebases.component.ts
This addresses the initial fix for https://github.com/openshiftio/openshift.io/issues/578
The filters relying on dates, createdAt && pushedAt are removed until there is calendar selection support in the patternfly-ng filter.
> fix(codebases): remove createdAt and pushedAt filter

- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
Remove no-longer-necessary filter for "test" environment in data returned from backend, and lightly
refactor surrounding code
> fix(deployments): remove filter for "test" environment

- config/webpack.common.js
fixes https://github.com/openshiftio/openshift.io/issues/2955
fabric8-planner, and other components, were being duplicated in our chunks bloating the application in production. In the before screenshot below fabric8-planner is include in 5 different chunks.
Unfortunately the main chunk is still large. This will be looked at again when we move to webpack 4.
Before total size 9.36 MB:
After total size 5.69 MB:
> fix(webpack): create smaller chunks

- src/app/profile/overview/overview.component.html
- src/app/profile/overview/overview.component.less
- src/app/profile/settings/settings.component.html
- src/app/profile/settings/settings.component.less
Removes custom, non-standard styling of secondary tab navigation elements in the Settings and Profile pages, and applies Patternfly standard styling instead.
https://github.com/openshiftio/openshift.io/issues/3889
> Secondary tab styling

- src/app/profile/overview/work-items/work-items.component.html
- src/app/profile/overview/work-items/work-items.component.less
- src/app/profile/overview/work-items/work-items.component.spec.ts
- src/app/profile/overview/work-items/work-items.component.ts
This short PR addresses [issue 1886](https://github.com/openshiftio/openshift.io/issues/1886), where if the user has a long space name then the combobox will overlap the title of the work item component in the profile view.
To fix, the width of the combobox has been made to be `width: 45%` just like the work items widget on the [home page](https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/home/work-item-widget/work-item-widget.component.less#L7) [1]. Additionally, the number of spaces being retrieved to display in the combobox was hardcoded at 10 spaces, so I've removed the limitation so all spaces should show up in the combobox.
Before:
After:
[0] https://github.com/openshiftio/openshift.io/issues/1886
[1] https://github.com/fabric8-ui/fabric8-ui/blob/master/src/app/home/work-i …
> fix(work-items): fix profile work-items combobox width and display all spaces

- src/app/space/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.html
- src/app/space/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.spec.ts
- src/app/space/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.ts
This PR addresses [issue 3565](https://github.com/openshiftio/openshift.io/issues/3565) [0], in which attempting to open a Che workspace for a codebase with ad-blocker enabled will not work, and an error notification gets displayed to the screen.
After a bit of digging, it seems that in order for a new page to appear with ad-block enabled is to have the window.open functionality called immediately after the component is clicked. Previously, our call to open a new window is nested inside of a subscribe is doesn't execute in time. This causes ad-block to block the new window and the `codebases-item-workspaces` to catch an error. In this PR, the `openWorkspace()` only performs the action of opening a new window based on the eclipse che url that is set when a combobox item is selected. …
> fix(codebases): fix opening workspaces in a new tab

- src/app/profile/my-spaces/my-spaces.component.spec.ts
- src/app/profile/my-spaces/my-spaces.component.ts
…e filtering
fixes https://github.com/openshiftio/openshift.io/issues/3857
This PR tweaks the filtering of spaces in the `my-spaces.component`with regards to combination of filters and case insensitivity. 
The `my-spaces.component` uses `name` as a filter attribute, and based on the PatternFly design explanations [[0]](http://www.patternfly.org/pattern-library/forms-and-controls/filter/#design) should be combined with a logical OR. Instead, patternfly-ng [[1]](http://www.patternfly.org/patternfly-ng/#/filters) seems to use logical AND, but this is an implementation detail and has been changed here. I have spaces numbered 1 through 13, and using the the following filters I would expect the following results:
-  filter '1' = [1, 10, 11, 12, 13]
-  filter '2' = [2, 12]
-  filter '1' with '2' …
> fix(my-spaces): introduce case insensitive filtering

- src/app/profile/overview/overview.component.less
- src/app/profile/settings/settings.component.less
- src/app/profile/update/update.component.less
This PR addresses issue 3986 [[0]](https://github.com/openshiftio/openshift.io/issues/3986) , where the nav-tabs have a noticeable visual stutter when clicking between tabs. This was also referenced in the images of a prior issue [1].
This flicker was due to the nav-tab border that was being briefly displayed when highlighting and/or clicking a tab. Even when hovering a tab there is a noticeable border that appears:
Before: notice the border around "My Spaces"
This PR simply removes the border from the css, and uses a 1px margin bottom to recreate the same visual layout. It also fixes another issue where the `a:hover` isn't turning the text blue.
After:
Here are a couple gifs of the changes in action:
Before (settings nav): notice the flicker when clicking between tabs
After (settings …
> fix(nav-tabs): prevent flickering when navigating between tabs

- src/app/dashboard-widgets/applications-widget/applications-widget.component.html
- src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.html
- src/app/dashboard-widgets/work-item-widget/work-item-widget.component.html
- src/app/space/analyze/analyze-overview/analyze-overview.component.ts
improve feature-flag caching. As per [feature-flag doc](https://github.com/fabric8-ui/ngx-feature-flag/blob/master/README.md), grouping `Analyze.MyWorkItemsCard`, `Analyze.ApplicationsCard`,  `Analyze.WorkItemOverviewCard` under `Analyze` page will avoid 3 http page each time you reach Analyze page (use of cached values instead)
Part of https://openshift.io/openshiftio/Openshift_io/plan/detail/158 
> I've created on prod-review and prod newly name feature-flag to match the rename.
> fix(workitemwidget): group feature flag to use page-cached feature-flag

- src/app/space/settings/collaborators/collaborators.component.less
Fixes https://github.com/openshiftio/openshift.io/issues/4010
Fixes https://github.com/fabric8-services/fabric8-auth/issues/554
- Set `max-height: 680px` and `overflow-y:scroll` to enable vertical scroll for collaborators component which will trigger scroll event for infiniteScroll directive.
> fix(collaborators): fixed component height and vertical scroll enabled for infinite scroll

- src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.component.spec.ts
This PR addresses current unit test failures as a result of a recent PR to the `codebases-item-actions` component [0]. I had overlooked fixing up the method names in the spec file after changing them in the implementation. Thanks to @andrewazores for letting me know about this so quickly.
[0] https://github.com/fabric8-ui/fabric8-ui/pull/3193
[1] https://jenkins.cd.test.fabric8.io/blue/organizations/jenkins/fabric8-ui%2Ffabric8-ui/detail/PR-3193/3/pipeline
> test(codebases-item-actions): fix failing unit tests

- config/webpack.dev.js
- environments/openshift-prod-cluster.sh
- environments/openshift-prod-preview-cluster.sh
- release.groovy
- src/app/shared/api-locator.service.ts
In today's platform meeting, @aslakknutsen requested we change API calls from `https://api.openshift.io/api/` to `https://openshift.io/api/`.
Tested dev with prod and prod-preview environments.
- updated environment scripts
- updated webpack dev fallback
- removed wit prefix from `api-locator.service.ts`
> fix(cors): remove `api` subdomain from wit api url

- src/app/app.module.ts
- src/app/space/create/deployments/services/deployment-api.service.spec.ts
- src/app/space/create/deployments/services/deployment-api.service.ts
- src/app/space/create/deployments/services/deployments.service.ts
This PR upgrades the DeploymentApiService from the old Angular Http to the newer HttpClient, and does some light refactoring on top.
> Deployments upgrade to HttpClient

- package-lock.json
- package.json
- src/app/shared/analytics.service.spec.ts
- src/app/shared/analytics.service.ts
- src/app/space/add-app-overlay/add-app-overlay.component.ts
- src/app/space/add-space-overlay/add-space-overlay.component.ts
- src/app/space/analyze/analyze-overview/analyze-overview.component.ts
- src/app/space/app-launcher/create-app/create-app.component.ts
- src/app/space/app-launcher/import-app/import-app.component.ts
- src/app/space/create/codebases/codebases.component.ts
- src/app/space/create/deployments/apps/deployments-apps.component.ts
- src/app/space/create/pipelines/pipelines.component.ts
- This PR uses a single event name to listen all the analytics tracking events
- Depends on https://github.com/fabric8-ui/fabric8-ui/pull/3130
- Depends on https://github.com/fabric8-launcher/ngx-launcher/pull/335. Before merging this PR the launcher package has to be bumped up
- Version upgrade for launcher to 1.0.8 to address some minor bugs
Addresses issue - https://github.com/openshiftio/openshift.io/issues/3239
> fix(telemetry): Using a single event for analytics tracking

- src/app/dashboard-widgets/edit-space-description-widget-old/edit-space-description-widget-old.component.html
- src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.html
- src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.spec.ts
- src/app/home/recent-spaces-widget/recent-spaces-widget.component.html
- src/app/home/work-item-widget/work-item-widget.component.html
- src/app/profile/my-spaces/my-spaces-item-actions/my-spaces-item-actions.component.spec.ts
- src/app/profile/my-spaces/my-spaces-item/my-spaces-item.component.html
- src/app/profile/overview/spaces/spaces.component.html
- src/app/profile/overview/work-items/work-items.component.html
- src/app/profile/overview/work-items/work-items.component.spec.ts
- src/app/profile/spaces/spaces.component.html
- src/app/shared/context.service.spec.ts
- src/app/shared/context.service.ts
- src/app/space/add-app-overlay/add-app-overlay.component.spec.ts
- src/app/space/add-space-overlay/add-space-overlay.component.html
- src/app/space/add-space-overlay/add-space-overlay.component.spec.ts
- src/app/space/add-space-overlay/add-space-overlay.component.ts
- src/app/space/settings/collaborators/collaborators.component.html
This addresses the recommendations in https://github.com/openshiftio/openshift.io/issues/3793
The usages of spaceName pipe are removed. The error message for space names is updated to not allow spaces in the name in anticipation of https://github.com/fabric8-ui/ngx-fabric8-wit/pull/179
> fix(app): remove spaceName pipe usage

- src/app/space/app-launcher/services/app-launcher-pipeline.service.spec.ts
- src/app/space/app-launcher/services/app-launcher-pipeline.service.ts
`appLauncherPipelineService#getPipelines()` had default filter set to `maven` which made it impossible to fetch all pipelines exposed by Launcher Backend API. 
Part of https://github.com/openshiftio/openshift.io/issues/4140
> fix: getPipelines() returns all pipelines instead of defaulting to maven

- src/app/space/app-launcher/services/app-launcher-pipeline.service.spec.ts
- src/app/space/app-launcher/services/app-launcher-pipeline.service.ts
There is a regression introduced in #3242 for enabling runtime-based pipeline selection for "create app" flow. 
As a side effect "import flow" shows the user all pipelines available in https://github.com/fabric8io/fabric8-jenkinsfile-library.
This PR brings back the old behaviour until https://github.com/openshiftio/openshift.io/issues/4154 is fixed.
> fix(import-flow): makes maven the only pipeline choice again

- src/app/app-routing.module.ts
- src/app/layout/header/header.component.spec.ts
- src/app/layout/header/header.component.ts
This PR removes a now unused function in the `app-routing.module`, and cleans up (add missing type definitions, remove unused imports) the code in the header component. 
Router actions were previously used when adding codebases to a space, but have been deprecated and later removed [0][1]. The `app-routing.module` exports a function that chops the trailing router action from the URL and is used in a couple of unit tests, but outside of that it is no longer needed. While removing the tests from the `header.component.spec` I figured it would be a good opportunity to clean up a bit of the code, so I added missing type definitions and removed unused imports/variables.
[0] https://github.com/fabric8-ui/fabric8-ui/pull/2980
[1] https://github.com/fabric8-ui/fabric8-ui/pull/2980/commits/f6ad12192 …
> chore(routing): remove unused removeAction function

- package-lock.json
- package.json
- src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.spec.ts
- src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.ts
- src/app/dashboard-widgets/work-item-widget/work-item-widget.component.spec.ts
- src/app/dashboard-widgets/work-item-widget/work-item-widget.component.ts
- src/app/home/work-item-widget/work-item-widget.component.spec.ts
- src/app/home/work-item-widget/work-item-widget.component.ts
- src/app/profile/overview/work-items/work-items.component.spec.ts
- src/app/profile/overview/work-items/work-items.component.ts
The work item service in planner has changed. Now it takes a formatted filter expression which can be constructed by the filter service in planner.
In this PR fabric8-ui is updated to use the new work item service. The old get work item end point is deprecated and will be discontinued from backend services.
> Upgrade use of new work item service from planner

- src/app/profile/my-spaces/my-spaces-search-dialog/my-spaces-search-spaces-dialog-space-item/my-spaces-search-spaces-dialog-space-item.component.html
- src/app/profile/my-spaces/my-spaces-search-dialog/my-spaces-search-spaces-dialog-space-item/my-spaces-search-spaces-dialog-space-item.component.less
- src/app/profile/my-spaces/my-spaces-search-dialog/my-spaces-search-spaces-dialog-space-item/my-spaces-search-spaces-dialog-space-item.component.spec.ts
- src/app/profile/my-spaces/my-spaces-search-dialog/my-spaces-search-spaces-dialog-space-item/my-spaces-search-spaces-dialog-space-item.component.ts
- src/app/profile/my-spaces/my-spaces-search-dialog/my-spaces-search-spaces-dialog-space-item/my-spaces-search-spaces-dialog-space-item.module.ts
- src/app/profile/my-spaces/my-spaces-search-dialog/my-spaces-search-spaces-dialog.component.html
- src/app/profile/my-spaces/my-spaces-search-dialog/my-spaces-search-spaces-dialog.component.less
- src/app/profile/my-spaces/my-spaces-search-dialog/my-spaces-search-spaces-dialog.component.spec.ts
- src/app/profile/my-spaces/my-spaces-search-dialog/my-spaces-search-spaces-dialog.component.ts
- src/app/profile/my-spaces/my-spaces-search-dialog/my-spaces-search-spaces-dialog.module.ts
- src/app/profile/my-spaces/my-spaces-toolbar/my-spaces-toolbar.component.html
- src/app/profile/my-spaces/my-spaces-toolbar/my-spaces-toolbar.component.less
- src/app/profile/my-spaces/my-spaces-toolbar/my-spaces-toolbar.component.ts
- src/app/profile/my-spaces/my-spaces.component.html
- src/app/profile/my-spaces/my-spaces.component.ts
- src/app/profile/my-spaces/my-spaces.module.ts
This PR introduces initial support for a search feature on the My Spaces page, as described in the relevant design issue [0]. A button is added to the My Spaces toolbar which summons a search dialog, containing a simple search term text field and submission button above an infinite scroll results list. Other features described in the design issue, such as search typeahead, the ability to request to join spaces, and the ability to sort the results list, are left implemented for future enhancements, since these will require additional enabling backend support features.
The invision designs for the feature are here: https://redhat.invisionapp.com/share/P7LNZNZUZ9Y#/screens
And this GIF is a quick demo of what the feature looks like as proposed in this PR:
Below are some more screenshots …
> "My Spaces" search

- src/app/profile/my-spaces/my-spaces-toolbar/my-spaces-toolbar.component.html
- src/app/profile/my-spaces/my-spaces-toolbar/my-spaces-toolbar.component.spec.ts
- src/app/profile/my-spaces/my-spaces-toolbar/my-spaces-toolbar.module.ts
related to https://github.com/openshiftio/openshift.io/issues/3655
The MySpaces.SearchSpaces feature toggle level has been defined on both prod and preview as 'experimental'. This PR hides the new search button for users on production or beta feature opt-in levels and shows it for users on experimental or internal.
> feat(my-spaces): add feature toggle for search feature

- src/app/profile/settings/settings-routing.module.ts
- src/app/profile/settings/settings.component.html
- src/app/profile/settings/settings.module.ts
Fixes https://github.com/openshiftio/openshift.io/issues/4235
Fixes https://github.com/fabric8-services/fabric8-auth/issues/619
- Adds feature flag with `internal` level to notifications tab under settings section.
> feat(notifications-settings): add internal feature flag for notifications tab

- src/app/profile/overview/spaces/spaces.component.html
- src/app/profile/overview/spaces/spaces.component.spec.ts
- src/app/profile/overview/spaces/spaces.component.ts
- src/app/profile/overview/spaces/spaces.module.ts
This PR addresses the loading state of the profile spaces component, and it's current lack of the loading widget while retrieving spaces. Currently, an empty state screen appears initially, and then gets updated once the list of spaces returns. This PR uses the loading widget similar to other components in OSIO to display a spinner while the list of spaces is being retrieved.
Before:
After:
> fix(spaces): add loading widget to profile spaces component

- src/app/profile/tenant/tenant.component.spec.ts
This fixes the tenant component spec to properly init and destroy, so the following no longer occurs.
```
ERROR: 'Error during cleanup of component', TenantComponent [...]
```
> fix(profile): fix init and destroy in tenant component tests

- src/app/profile/my-spaces/my-spaces.component.ts
- src/app/profile/spaces/spaces.component.ts
- src/app/shared/spaces.service.spec.ts
- src/app/shared/spaces.service.ts
- src/app/space/add-app-overlay/add-app-overlay.component.spec.ts
- src/app/space/add-space-overlay/add-space-overlay.component.spec.ts
- src/app/space/add-space-overlay/add-space-overlay.component.ts
Note: the last commit (regarding tests) in this PR will need to be refactored when https://github.com/fabric8-ui/fabric8-ui/pull/3201 is merged
This PR addresses OSIO defect #157 [0], in which the updating of 'recent space' causes a large number of PATCH calls to /api/users. Note that refactoring the SpacesService isn't enough to remove all the redundant calls, it appears that the ContextService is operating in a similar fashion and is responsible for most of the PATCH calls.
Currently, the _recent variable is a merge of the broadcaster 'spaceChanged' and addRecent (which gets updated for each space returned from `loadRecent()`) [1]. The problem lies with the `scan()` [2], which gets triggered for each space; loading 8 spaces via `loadRecent()` results in the subsequent block of code …
> fix(SpacesService): reduce number of calls to /api/users regarding recent spaces

- src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.spec.ts
- src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.ts
- src/app/dashboard-widgets/work-item-widget/work-item-widget.component.spec.ts
- src/app/dashboard-widgets/work-item-widget/work-item-widget.component.ts
- src/app/home/work-item-widget/work-item-widget.component.spec.ts
- src/app/home/work-item-widget/work-item-widget.component.ts
- src/app/profile/overview/work-items/work-items.component.spec.ts
- src/app/profile/overview/work-items/work-items.component.ts
- src/app/shared/workitem-utils.ts
This PR addresses https://github.com/openshiftio/openshift.io/issues/4303, where the dashboard work item widget can display an incorrect number of total work items. This occurs because it seems the workitemservice will return at most 500 work items, and the total count is obtained by getting the length of the array of work items. However, the workitemservice also returns an actual number with the total number of work items that we can use here.
> fix(work-item-widget): fix incorrect total of work items

- src/app/shared/interceptors/cache.interceptor.spec.ts
- src/app/shared/interceptors/cache.interceptor.ts
Related to: https://github.com/fabric8-ui/fabric8-ui/pull/3285#issuecomment-420281716
The cache interceptor wasn't returning the correct observable.
Observed the Recent Workspaces widget was stuck on loading even though the network request went through.
I was able to reproduce this in dev environment and with the fix, the widget loaded correctly.
> fix(cache): fix cache interceptor to return the proper observable

- src/app/space/create/deployments/apps/deployment-card-container.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card-container.component.ts
- src/app/space/create/deployments/apps/deployment-card.component.spec.ts
- src/app/space/create/deployments/apps/deployment-card.component.ts
- src/app/space/create/deployments/apps/deployment-details.component.spec.ts
- src/app/space/create/deployments/apps/deployment-details.component.ts
- src/app/space/create/deployments/apps/deployments-apps.component.spec.ts
- src/app/space/create/deployments/apps/deployments-apps.component.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.spec.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.ts
- src/app/space/create/deployments/deployments.component.spec.ts
- src/app/space/create/deployments/deployments.component.ts
- src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.spec.ts
- src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts
- src/app/space/create/deployments/resource-usage/resource-card.component.ts
- src/app/space/create/deployments/resource-usage/utilization-bar.component.spec.ts
- src/app/space/create/deployments/services/deployment-api.service.spec.ts
- src/app/space/create/deployments/services/deployment-api.service.ts
- src/app/space/create/deployments/services/deployment-status.service.spec.ts
- src/app/space/create/deployments/services/deployment-status.service.ts
- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
These commits make Deployments-area code use the new RxJS `pipe` syntax and Observable factories such as `Observable.of() -> of()`, updating imports as needed.
https://openshift.io/openshiftio/Openshift_io/plan/detail/579
> Deployments RxJS syntax upgrade

- src/app/space/create/pipelines/pipelines.component.spec.ts
- src/app/space/create/pipelines/pipelines.component.ts
This fixes the pipelines page to have a correct initial sort. The sorting code called at the start uses this immediately, but the initial state of the toolbar is ascending, not descending, so it would be in the wrong order.
> fix(pipelines): initialize sort with default value

- src/app/profile/cleanup/cleanup.component.spec.ts
- src/app/profile/cleanup/cleanup.component.ts
This updates the reset environment code to also broadcast the appropriate event when it deletes spaces. This should help to keep other widgets in the application updated appropriately.
> fix(cleanup): broadcast event when deleting space

- config/webpack.common.js
- package-lock.json
- src/a-runtime-console/kubernetes/service/kubernetes.restangular.ts
- src/a-runtime-console/kubernetes/store/oauth-config-store.spec.ts
- src/a-runtime-console/kubernetes/support/abstract-watch.component.ts
- src/app/base/config.store.ts
- src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.ts
- src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.ts
- src/app/dashboard-widgets/recent-workspaces-widget/recent-workspaces-widget.component.ts
- src/app/dashboard-widgets/work-item-widget/work-item-widget.component.ts
- src/app/environment.ts
- src/app/getting-started/services/getting-started.service.ts
- src/app/home/work-item-widget/work-item-widget.component.ts
- src/app/profile/profile.service.ts
- src/app/profile/settings/feature-opt-in/feature-opt-in.component.spec.ts
- src/app/profile/settings/feature-opt-in/feature-opt-in.component.ts
- src/app/profile/settings/feature-opt-in/feature-opt-in.module.ts
- src/app/profile/tenant/tenant.module.ts
- src/app/profile/update/update.component.ts
- src/app/profile/update/update.module.ts
- src/app/shared/context.service.ts
- src/app/shared/interceptors/cache.interceptor.ts
- src/app/space/analyze/analyze-overview/analyze-overview.component.ts
- src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.component.ts
- src/app/space/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.ts
- src/app/space/create/codebases/codebases-item/codebases-item.component.spec.ts
- src/app/space/create/codebases/codebases-item/codebases-item.module.ts
- src/app/space/create/codebases/codebases.component.ts
List of fixes:
- TS2322: Type 'Observable<any>' is not assignable to type 'ConnectableObservable<User>'
https://stackoverflow.com/questions/50166366/multicast-operator-with-pipe-in-rxjs-5-5/50166414#50166414
Removed     "angular2-oauth2": “1.3.10” is replaced by "angular-oauth2-oidc": “4.0.3", therefore new import: `import { OAuthService } from angular-oauth2-oidc`;
- TS2415: Class 'CachingSubject<T>' incorrectly extends base class 'Subject<T>'.
Property '_subscribe' is protected in type 'CachingSubject<T>' but public in type ‘Subject<T>'.
=> remove protected
- TS2339: Property 'connect' does not exist on type ‘Observable<ValWrapper<T>>'. See https://github.com/ReactiveX/rxjs/issues/2972 => fixed it by casting return type of publish: publishReplay(1)) as …
> Upgrade.compile.test

- src/app/space/app-launcher/services/app-launcher-gitprovider.service.spec.ts
- src/app/space/app-launcher/services/app-launcher-gitprovider.service.ts
Fixes https://github.com/openshiftio/openshift.io/issues/4333
Fixes https://github.com/fabric8-services/fabric8-auth/issues/653
- Due to extra headers being added in github linking request, the request was failing in CORS preflight request.
- Uses `ProviderService` for linking github account instead of custom implementation.
> fix(app-launcher): fix github linking due to extra headers

- package-lock.json
- package.json
This PR
- Updates fabric8-planner to version 0.55.11 (https://github.com/fabric8-ui/fabric8-planner/releases/tag/v0.55.11)
> fix(version): update fabric8-planner to 0.55.11

- src/app/shared/context.service.ts
- src/app/shared/recent-utils.ts
- src/app/shared/spaces.service.spec.ts
- src/app/shared/spaces.service.ts
~~Note: this PR is meant to be on top of https://github.com/fabric8-ui/fabric8-ui/pull/3320 [[0]](https://github.com/fabric8-ui/fabric8-ui/pull/3320), so I'll keep it a WIP for the time being. Only the last commit in this PR is relevant here.~~
This PR addresses a comment [[1]](https://github.com/fabric8-ui/fabric8-ui/pull/3320#issuecomment-421436050) on [[0]](https://github.com/fabric8-ui/fabric8-ui/pull/3320) regarding extracting common "recent" logic to an extendable common class. Here, `recent-utils.ts` is introduced and takes care of the:
1. declaration and return of `_recent`
2. logic as a result of broadcaster events `'spaceChanged', 'contextChanged', 'spaceDeleted'`
3. saving the patch to the profile
The loading of recent contexts and spaces happen in similar functionality, but …
> feat(recent): introduce recent-utils to be extended by context and spaces service for "recent" logic

- package.json
`--runInBand` is suggested for debugging as it runs all tests in series rather than spawning workers to run tests.
> fix(jest): add --runInBand for jest:debug

- src/app/profile/services/tenant.service.spec.ts
- src/app/profile/services/tenant.service.ts
- src/app/profile/settings/connected-accounts/connected-accounts.component.html
- src/app/profile/settings/connected-accounts/connected-accounts.component.less
- src/app/profile/settings/connected-accounts/connected-accounts.component.ts
- src/app/profile/settings/connected-accounts/connected-accounts.module.ts
- src/app/profile/settings/connected-accounts/connected-accounts.spec.ts
- src/app/profile/settings/settings.component.html
Fixes https://github.com/openshiftio/openshift.io/issues/4304
Fixes https://github.com/fabric8-services/fabric8-auth/issues/656
- Changes `Connected Accounts` -> `Connected Services`.
- Adds cluster URL to connected account section.
> feat(settings): show openshift cluster url in connected account section

- src/app/space/create/deployments/deployments-donut/deployments-donut.component.html
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.spec.ts
- src/app/space/create/deployments/deployments-donut/deployments-donut.component.ts
- src/app/space/create/deployments/services/deployment-api.service.spec.ts
- src/app/space/create/deployments/services/deployment-api.service.ts
- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
~~WIP: DeploymentApiService currently returns a mocked data structure. This needs to be replaced with an actual HTTP request once the backend support (https://github.com/fabric8-services/fabric8-wit/pull/2286) is merged and deployed. Additionally, there should be another piece of logic added on top to only allow a scale-up attempt for the maximum number of pods that can be supported in the remaining quota, so the user cannot over-request (ie attempt to scale 0->3 when there is only quota for 2).~~
Allow users to scale up deployments only if the remaining quota is sufficient to support an
additional pod. Previously, if any free quota remained a scale operation would always be permitted,
even if the amount of remaining quota was too small to support an additional pod.
related to …
> feat(deployments): allow scaling only if remaining quota is sufficient

- src/app/space/create/deployments/services/deployment-api.service.spec.ts
- src/app/space/create/deployments/services/deployment-api.service.ts
- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
Cache pod quota requirement values to avoid spurious query when
expanding Deployments card rows. Also refactor error handling logic from
DeploymentApiService to DeploymentsService to be more consistent with
other service logic.
This is a follow-up enhancement to https://github.com/fabric8-ui/fabric8-ui/pull/3336 .
> fix(deployments): cache pod quota requirements

- config/webpack.dev.js
- config/webpack.prod.js
The existing sourcemap file mappings remap paths to local file system although it can make browsing more difficult. Removing to return to webpack defaults.
> fix(webpack): remove sourcemap file mappings

- src/vendor.browser.ts
Fixes https://openshift.io/openshiftio/Openshift_io/plan/detail/548
In ng6 upgrade, we missed the css therefore the ability to expand the treelist was removed.
> fix(tree-view): Fix missing expand toggle in area components

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/profile/overview/overview.component.ts
- src/app/profile/update/update.component.ts
- src/app/shared/auth-api.provider.ts
Fixes https://github.com/fabric8-services/fabric8-auth/issues/680
- Version upgrade `ngx-login-client`
- Update response type of `sendEmailVerificationLink`. `Response` - > `HttpResponse`
- Explicitly provide value for `InjectionToken` `WIT_API_PROXY`
> fix(ngx-login-client): upgrade ngx-login-client and provide value for WIT_API_PROXY

- src/app/layout/header/header.component.html
This PR addresses https://github.com/openshiftio/openshift.io/issues/4188 & https://openshift.io/openshiftio/Openshift_io/plan/detail/784, which adds a link to the help menu to direct users to the OSIO issues page.
Here's a shot of the drop down:
And here's what it looks like in action:
> feat(header): add 'Create Issue' help menu item to open GitHub issues

- src/app/space/create/codebases/codebases.component.less
This one-liner addresses https://github.com/openshiftio/openshift.io/issues/4408.
After the f8-ui updates the spacing of the `pfng-list-heading` has been out of sync with the list itself. This is because the `pfng-list-heading` is now given a `display: flex` by the patternfly-ng stylesheets, whereas before it used to be `display: block`. Adding this display type to the `codebases.component.less` will amend the spacing.
Before:
After:
> fix(less): fix pfng list header text spacing

- src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.html
- src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.spec.ts
- src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.ts
- src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.module.ts
- src/app/home/work-item-widget/work-item-widget.component.ts
- src/app/shared/workitem-utils.ts
- src/app/space/analyze/analyze-overview/analyze-overview.component.html
fixes https://github.com/openshiftio/openshift.io/issues/4381
In create work-item widget work-item filter query was not using space id to get the work-items for that particular space only, so in this PR I have-
- created filter query using space id to solve the above issue
- removed deprecated functions form home work-item-widget
> fix(space-dashboard): fix work-item filter query in create work-item widget

- src/app/space/create/deployments/models/resource-utilization.ts
- src/app/space/create/deployments/resource-usage/resource-card.component.html
- src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts
- src/app/space/create/deployments/resource-usage/resource-card.component.ts
- src/app/space/create/deployments/resource-usage/utilization-bar.component.html
- src/app/space/create/deployments/resource-usage/utilization-bar.component.less
- src/app/space/create/deployments/resource-usage/utilization-bar.component.spec.ts
- src/app/space/create/deployments/resource-usage/utilization-bar.component.ts
- src/app/space/create/deployments/services/deployment-api.service.spec.ts
- src/app/space/create/deployments/services/deployment-api.service.ts
- src/app/space/create/deployments/services/deployments.service.spec.ts
- src/app/space/create/deployments/services/deployments.service.ts
~~~This PR is a basic rough prototype for https://github.com/openshiftio/openshift.io/issues/3128 . This requires backend support from https://github.com/openshiftio/openshift.io/issues/3129 . It looks unlikely that I will be following through with the final implementation of this feature, so I leave it here as a WIP so someone else can easily pick it up.~~~
This PR implements https://github.com/openshiftio/openshift.io/issues/3128 , allowing the Deployments page resource cards to indicate how much of the taken quota is used in the currently viewed Space context and how much is taken elsewhere (by deployments in different spaces). See the above screenshots depicting a scenario where two spaces are splitting quota in the Stage environment, and only one has a deployment in the Run …
> Deployments utilization bar component can display "other spaces" utilization

- src/app/layout/header/header.component.html
This one-liner fixes https://github.com/openshiftio/openshift.io/issues/4420, in which the capitalization of `Create space` to `Create Space` in the user menu is fixed.
Before:
After:
> fix(header): fix capitalization of 'Create Space' in the user dropdown

- src/app/home/home.component.spec.ts
- src/app/home/home.component.ts
- src/app/profile/my-spaces/my-spaces-toolbar/my-spaces-toolbar.component.html
- src/app/profile/my-spaces/my-spaces-toolbar/my-spaces-toolbar.component.less
- src/app/profile/my-spaces/my-spaces-toolbar/my-spaces-toolbar.component.spec.ts
- src/app/profile/my-spaces/my-spaces-toolbar/my-spaces-toolbar.component.ts
- src/app/profile/my-spaces/my-spaces.component.html
- src/app/profile/my-spaces/my-spaces.component.spec.ts
- src/app/profile/my-spaces/my-spaces.component.ts
- src/app/profile/my-spaces/my-spaces.module.ts
- src/app/shared/user-spaces.service.spec.ts
- src/app/shared/user-spaces.service.ts
This PR addresses OSIO task [Add filter button/ability to Spaces page header](https://openshift.io/openshiftio/Openshift_io/plan/detail/844) [0], which is a sub-task of [Improve the My Spaces page](https://openshift.io/openshiftio/Openshift_io/plan/detail/786) on OSIO [1] and [Improve the My Spaces page](https://github.com/openshiftio/openshift.io/issues/4326) on GitHub [2].
~~I'll be waiting to rebase this on top of https://github.com/fabric8-ui/fabric8-ui/pull/3378, so the function that requests information from `/api/user/spaces` can be included in the new `user-spaces.service.ts`.~~
Additionally, there were a couple of unit tests in the `my-spaces.component.spec.ts` that weren't performing as expected, so I'll be continuing to update the unit tests and add more tests for the new …
> fix(spaces): improve the spaces page to display owned and shared spaces

- src/a-runtime-console/kubernetes/store/build.store.ts
- src/a-runtime-console/kubernetes/store/buildconfig.store.ts
- src/a-runtime-console/kubernetes/store/configmap.store.ts
- src/a-runtime-console/kubernetes/store/deployment.store.ts
- src/a-runtime-console/kubernetes/store/deploymentconfig.store.ts
- src/a-runtime-console/kubernetes/store/event.store.ts
- src/a-runtime-console/kubernetes/store/namespace.store.ts
- src/a-runtime-console/kubernetes/store/pod.store.ts
- src/a-runtime-console/kubernetes/store/replicaset.store.ts
- src/a-runtime-console/kubernetes/store/replicationcontroller.store.ts
- src/a-runtime-console/kubernetes/store/route.store.ts
- src/a-runtime-console/kubernetes/store/service.store.ts
- src/a-runtime-console/kubernetes/ui/pipeline/build-stage-view/build-stage-view.spec.ts
- src/a-runtime-console/kubernetes/ui/pipeline/input-action-dialog/input-action-dialog.spec.ts
- src/app/environment.ts
- src/app/layout/header/menus.service.ts
- src/app/space/add-app-overlay/add-app-overlay.component.spec.ts
- src/app/space/add-space-overlay/add-space-overlay.component.ts
- src/app/space/app-launcher/services/app-launcher-dependency-check.service.spec.ts
- src/app/space/wizard/common/utilities.ts
Switched all usage of `<>` type casting to use `as` since `<>` is not supported alongside jsx in tsx files.
This is needed to support compiling react jsx going forward.
> fix(format): change all type casts to use `as`

- talamer/.idea/inspectionProfiles/Project_Default.xml
- talamer/.idea/runConfigurations/Debug_All_Tests.xml
- talamer/package.json
- talamer/packages/eslint-plugin-osio/lib/config/react.js
- talamer/packages/scripts/lib/rewire-scripts.js
Part of https://openshift.io/openshiftio/Openshift_io/plan/detail/650
* add launch configuration for debugging jest tests
* add project settings to enable eslint
* Cannot enable eslint fix on save since intellij auto saves frequently. Intellij users can use the context menu `Fix ESLint Problems`
* fix other setting issues found while testing intellij support
> add intellij settings to monorepo

- src/app/shared/interceptors/index.ts
- src/app/shared/interceptors/x-app.interceptor.spec.ts
- src/app/shared/interceptors/x-app.interceptor.ts
Planner Story - https://openshift.io/openshiftio/Openshift_io/plan/detail/884
- Adds an interceptor for `X-App` headers in launcher API calls
> feat(interceptors): add interceptor for `X-App` headers in launcher API calls

- src/app/space/create/codebases/services/workspaces.service.ts
openshift.io issue - https://github.com/openshiftio/openshift.io/issues/4416
`retry` calls should be removed completely from open / create workspace methods since those have been added back to the time when Che server used to be single-tenant and it was required to unidle it, which might caused timeouts. Currently, Che server is multi-tenant and is running on osd so those retries not needed anymore.
> fix(workspaces): removing retry calls from open / create workspace methods (#4416)

- package-lock.json
- package.json
- src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.html
- src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.less
- src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.spec.ts
- src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.ts
- src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.module.ts
Display the list of space collaborators in a popover component upon click of the collaborator count
label when viewing the Analyze Dashboard for any given space
related to https://openshift.io/openshiftio/Openshift_io/plan/detail/847
~~Still TODO: add search widget in popover~~
> feat(analyze-dashboard): display collaborators list in popover

- Dockerfile.builder
I want to create PR checks for this repository that would run e2e test. I need to expose port 3000 so that e2e test can access the locally-build app.
> fix(build) expose port in dockerfile

- src/app/space/settings/collaborators/collaborators.component.less
Fixes https://github.com/openshiftio/openshift.io/issues/4437
- Adds a `margin-bottom: 50px` to the last item in the list so that the kebab menu is visible easily.
Screenshot -
> fix(collaborators): fix scrolling issue for last item in the list

- src/app/space/settings/collaborators/collaborators.component.less
Based on the comment https://github.com/fabric8-ui/fabric8-ui/pull/3399#issuecomment-435052596.
- Increases the `margin-bottom` by 10px.
- Encapsulates the CSS rules within the parent component scope.
>  fix(collaborators): increase margin bottom and encapsulate css rule within parent component

- talamer/packages/fabric8-ui/tsconfig.json
- talamer/packages/scripts/config/jest/transforms/angularComponentTransform.js
- talamer/packages/scripts/config/jest/transforms/htmlTransform.js
- talamer/packages/scripts/config/jest/transforms/typescriptTransform.js
- talamer/packages/scripts/config/tsconfig/tsconfig.json
- talamer/packages/scripts/lib/rewire-scripts.js
While attempting to run babel typescript instead of ts-loader, I made the following changes.
Need to separate out HTML and angular component transforms for jest so that it is easier to switch out the typescript transform portion only later.
Also update tsconfigs as noted by suggestions while attempting to use create-react-app typescript support.
Added suppprt to jest to read a `.ts` test setup file.
> update monorepo tsconfig and jest

- src/app/shared/context.service.ts
- src/app/shared/recent-utils.spec.ts
- src/app/shared/recent-utils.ts
- src/app/shared/spaces.service.ts
Fixes the signature of `recent-utils#compareElements` which causes test failures in the monorepo. The abstract function should not be typed as the generic comes from the class and not should not come from the function.
This function is implemented in `spaces.service` and `context.service` as follows:
```
compareElements(s1: Space, s2: Space): boolean {
return s1.id === s2.id;
}
```
```
compareElements(c1: Context, c2: Context): boolean {
return c1.name === c2.name;
}
```
> Fix(recent-utils): fix signature of recent-utils#compareElements

- package-lock.json
- package.json
- talamer/package.json
https://github.com/dominictarr/event-stream/issues/116
npm-run-all@4.1.3 used to depend on package ps-tree which in turn used event-stream
in its dependencies. npm-run-all@4.1.5 removed ps-tree from its dependencies.
The event-stream package depends on flatmap-stream which was removed from npmjs because it 
contains a crypto-coin stealing malware.
> fix(package): upgrade npm-run-all to v4.1.5

- src/app/shared/branding.service.ts
Update all OSIO page titles to CodeReady Toolchain - [OSIO-1118](https://openshift.io/openshiftio/Openshift_io/plan/detail/1118)
Reference: https://github.com/openshiftio/openshift.io/issues/4364
> Update OSIO page titles to CodeReady Toolchain

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.html
- src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.less
- src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.spec.ts
- src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.ts
- src/app/layout/header/header.component.spec.ts
- src/app/layout/header/header.component.ts
- src/app/space/analyze/analyze-overview/analyze-overview.component.html
- src/app/space/analyze/analyze-overview/analyze-overview.component.spec.ts
- src/app/space/analyze/analyze-overview/analyze-overview.component.ts
- src/app/space/settings/areas/areas-toolbar/areas-toolbar.component.html
- src/app/space/settings/areas/areas-toolbar/areas-toolbar.component.ts
- src/app/space/settings/areas/areas.component.html
- src/app/space/settings/areas/areas.component.ts
- src/app/space/settings/collaborators/collaborators.component.html
- src/app/space/settings/collaborators/collaborators.component.less
- src/app/space/settings/collaborators/collaborators.component.spec.ts
- src/app/space/settings/collaborators/collaborators.component.ts
- src/app/space/settings/space-settings-routing.module.ts
Related Planner Stories -
- Add support for adding admins from the Collaborators UI. [Link](https://openshift.io/openshiftio/Openshift_io/plan/detail/889)
- Make collaborators page visible to all admins. [Link](https://openshift.io/openshiftio/Openshift_io/plan/detail/890)
Fixes https://github.com/fabric8-services/fabric8-auth/issues/700
Fixes https://github.com/fabric8-services/fabric8-auth/issues/699
This feature implements user role permission management using RPT workflow. `PermissionService` is added in `ngx-login-client` which gives ability to assign roles, check for scopes and audit RPT token for permission management.
Following changes are introduced as part of the feature - 
- On the collaborators page there will be option from action menu to assign `admin` role to any …
> feat(roles): add role management using permission service

- src/app/getting-started/getting-started.component.html
- src/app/layout/redirect-status/redirect-status.component.ts
- src/app/layout/redirect-status/status/status.component.spec.ts
- src/app/profile/cleanup/cleanup.component.html
- src/app/profile/cleanup/cleanup.component.ts
- src/app/profile/settings/feature-opt-in/feature-opt-in.component.ts
- src/app/space/add-app-overlay/add-app-overlay.component.html
- src/app/space/add-space-overlay/add-space-overlay.component.html
- src/app/space/app-launcher/services/app-launcher-target-environment.service.ts
- src/app/space/create/codebases/codebases-delete/codebase-delete-dialog.component.html
Update all static text references to CodeReady Toolchain on OSIO - [OSIO-1180](https://openshift.io/openshiftio/Openshift_io/plan/detail/1180)
Attaching screenshots for some of the code changes:
Feature Opt In
Context text during space creation
Context text during app creation
Remove codebase modal
Reference: https://github.com/openshiftio/openshift.io/issues/4364
> fix(rebranding): Update all static text references to CodeReady Toolchain

- src/app/layout/header/header.component.spec.ts
- src/app/layout/header/header.component.ts
- src/app/layout/header/menus.service.ts
- src/app/models/menu-item.ts
- src/app/space/settings/collaborators/collaborators.component.html
- src/app/space/settings/collaborators/collaborators.module.ts
Planner Story - https://openshift.io/openshiftio/Openshift_io/plan/detail/1211
This PR adds feature flag to the logic to hiding settings icon in the header and on the collaborators page inside settings.
- The header component is rendered by using `MenusService` to determine if the menu item needs to be rendered or not.
- `MenusService` checks for feature enabled menu items and send it to component level where the logic to hide something based on user is owner or admin is decided.
- This is why its tricky to introduce feature flag at the header level based on the user permission as well as the feature enablement.
- For achieving this we had to introduce on more property called `subFeature` in the `MenuItem` type interface. Based on the `feature` property menu item is deleted from the list …
> feat(roles): add feature flags on settings icon and collaborators page

- config/webpack.prod.js
Fix for build error:
```
/home/fabric8/fabric8-ui/node_modules/webpack-cli/bin/cli.js:244
throw err;
^
TypeError: Cannot read property 'path' of undefined
at module.exports (/home/fabric8/fabric8-ui/config/webpack.prod.js:289:65)
at handleFunction (/home/fabric8/fabric8-ui/node_modules/webpack-cli/bin/prepareOptions.js:23:13)
at prepareOptions (/home/fabric8/fabric8-ui/node_modules/webpack-cli/bin/prepareOptions.js:9:5)
at requireConfig (/home/fabric8/fabric8-ui/node_modules/webpack-cli/bin/convert-argv.js:136:14)
at /home/fabric8/fabric8-ui/node_modules/webpack-cli/bin/convert-argv.js:142:17
```
Rebranding removed the branding favicon which caused the build to fail with an `undefined` error.
Comment out the favicon plugin as we are no longer generating a favicon until a new brand image …
> fix(build): remove favicon

- packages/fabric8-ui/package.json
semantic-release was failing on the build because it was set to run in the build dir which did not include a package.json file. Updated package.json to specify `pkgRoot` to be the root dir and set the `files` array to include the `build` dir.
dry run:
```
21:30:52] [semantic-release] › ℹ  Running semantic-release version 15.12.0
[21:30:53] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[21:30:53] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[21:30:53] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[21:30:53] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[21:30:53] [semantic-release] › ✔  Loaded plugin …
```
> fix(build): run semantic-release from root and only include build dir

- packages/planner/src/app/components_ngrx/label-selector/label-selector.component.less
- packages/planner/src/app/components_ngrx/planner-list/planner-list.component.less
- packages/planner/src/app/components_ngrx/planner-query/planner-query.component.less
- packages/planner/src/app/components_ngrx/work-item-cell/work-item-cell.component.less
- packages/planner/src/app/widgets/inlineinput/inlineinput.component.less
Fix: https://github.com/openshiftio/openshift.io/issues/4645
**Before:**
Long title is broken in planner
**After:**
Add truncate for long 
**Before:**
Input field width is not 100%
**After:**
Input field width is 100%
> fix(style): width of the elements

- packages/planner/src/app/components_ngrx/work-item-cell/work-item-cell.component.html
- Added slash for root iteration
Issue: https://github.com/openshiftio/openshift.io/issues/2997
Issue: https://github.com/openshiftio/openshift.io/issues/4665
Issue: https://github.com/openshiftio/openshift.io/issues/4666
> fix(planner): Iteration labels not used consistently

- packages/planner/src/app/components_ngrx/planner-list/planner-list.component.html
- packages/planner/src/app/components_ngrx/work-item-quick-add/work-item-quick-add.component.ts
Fixes https://github.com/fabric8-ui/fabric8-ui/pull/3464
Added Inheritance of iteration from parent
> fix(planner): Child work item inherits iteration

- openshift/fabric8-ui.app.yaml
- openshift/fabric8-ui.config.yaml
Use `BUILD_TOOL_DETECTOR` env value from config map instead of template params.
> fix(deployment): Use Build Tool Detector URL from config map

- packages/toolchain/env.js
After this PR - https://github.com/fabric8-ui/fabric8-ui/pull/3492, `getFeaturesUrl` was referencing to `FEATURE_TOGGLES_API_URL` which comes as undefined in dev environment since it was not set in env.js.
This is why in local env `getFeaturesUrl()` was returning `localhost:3000/api/features?strategy=enableByLevel`
> fix(nav): set feature toggle api url in env to wit url

- packages/planner/src/app/components_ngrx/work-item-detail/work-item-detail.component.html
Issue: https://github.com/openshiftio/openshift.io/issues/4542
- Remove method closeClick on deactivateEditor
> fix(planner): description does not change when selecting a new one

- packages/toolchain/src/app/api/internal/__tests__/api.config.spec.ts
- packages/toolchain/src/app/api/internal/api.config.ts
- packages/toolchain/webpack.config.js
The `api-locator.service.ts` in the angular app does not expose any URL which uses the `FABRIC8_FEATURE_TOGGLES_API_URL` env variable. The `toggles.api.provider.ts` provides the wit api url for feature toggles.
Using `FABRIC8_FEATURE_TOGGLES_API_URL` breaks the react app in prod preview today because the URL is incorrect. Furthermore, in production, the `fabric8-ui.env.js` file doesn't even include a value for the feature toggles. Most URLs are empty. Which means we need to add a default fallback to `/api/` just like the `api-locator.service.ts` does.
The result of not having this fix is that on prod-preview, the react app queries for features at `https://api.prod-preview.openshift.io/api/features?strategy=enableByLevel` while the angular app queries …
> fix(env): assign wit url to feature toggles and add fallback to /api/

- packages/fabric8-ui/src/app/shared/login.service.spec.ts
- packages/fabric8-ui/src/app/shared/login.service.ts
- packages/toolchain/src/app/api/__mocks__/jsonapi.client.ts
- packages/toolchain/src/app/api/__tests__/api-urls.spec.ts
- packages/toolchain/src/app/api/api-urls.ts
- packages/toolchain/src/app/api/http.client.ts
- packages/toolchain/src/app/redux/authentication/__tests__/actions.spec.ts
- packages/toolchain/src/app/redux/authentication/actions.ts
- packages/toolchain/src/app/redux/jsonapi/actions.ts
Fixes https://github.com/openshiftio/openshift.io/issues/4742
- Implements new logout using `/logout/v2` endpoint.
- Instead of redirecting to the logout endpoint, now we make http request to `logout/v2` with redirect param. the response then sends a `redirect_location` and we redirect to that url.
- Renamed `jsonapi.client` to `http.client` and added simple fetch method for axios get.
- Added tests for logout action in react app and login service in angular.
> feat(logout): new logout implementation using /logout/v2 API

- packages/fabric8-ui/src/app/profile/settings/settings.component.html
fixes issue https://github.com/openshiftio/openshift.io/issues/4748
Removed the sub-nav link to the `Resources` page which no longer exists.
> fix(deployment): `resources` user settings link returns 404 error page

- packages/ngx-widgets/src/app/area-size/area-size.directive.spec.ts
- packages/ngx-widgets/src/app/area-size/area-size.directive.ts
- packages/ngx-widgets/src/app/area-size/area-size.module.ts
- packages/ngx-widgets/src/app/markdown/markdown.component.html
- packages/ngx-widgets/src/app/markdown/markdown.component.less
- packages/ngx-widgets/src/app/markdown/markdown.component.ts
- packages/ngx-widgets/src/app/markdown/markdown.module.ts
fixes: https://github.com/openshiftio/openshift.io/issues/3972
- Made the textarea instead of a contenteditable element
> fix(preview): Markdown component layout breaks on copy-paste

- openshift/fabric8-ui.app.yaml
Fixes https://github.com/openshiftio/openshift.io/issues/4757
- Adds a config map in the openshift deployment config for `FABRIC8_AUTH_API_URL`.
- Currently i have updated prod-preview config maps. So this issue is solved but before pushing new navigation to prod we need this issue - https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2560 closed so that logout works from new navigation as well.
> fix(api-url): add auth api url in openshift config map
