src/app/analyze/analyze.component.html, src/app/analyze/analyze.component.scss, src/app/analyze/analyze.component.ts, src/app/header/header.component.html, src/app/profile/overview/overview.component.html
=> Adip analyze

.htmlhintrc, src/app/dummy/dummy.service.ts, src/app/header/header.component.html, src/app/header/header.component.ts, src/app/models/context-menu-item-type.ts, src/app/models/context-menu-item.ts
=> Context menu

src/app/dummy/dummy.service.ts, src/app/home/home.component.html, src/app/models/process-templates.ts, src/app/space-dialog/space-dialog.component.html, src/app/space-dialog/space-dialog.component.ts
=> Dummy process templates

config/webpack.test.js, src/app/shared-component/dialog/dialog.component.spec.ts, src/app/shared-component/dropdown/dropdown.component.spec.ts
=> Web pack config for test fixed

src/app/dummy/dummy.service.ts, src/app/header/header.component.html, src/app/header/header.component.ts, src/app/models/context-menu-item.ts
=> Context menu redux

src/app/dummy/dummy.service.ts, src/app/models/email.ts, src/app/models/profile.ts, src/app/profile/profile.service.ts, src/app/settings/emails/emails.component.html, src/app/settings/emails/emails.component.ts, src/app/settings/notifications/notifications.component.html, src/app/settings/profile/profile.component.html, src/app/settings/profile/profile.component.ts
After discussion with Todd, make emails a bit simpler
=> Fix the way emails work

src/app/dummy/dummy.service.ts, src/app/profile/profile.service.ts, src/app/public/public.component.ts, src/app/signup/signup.component.html, src/app/signup/signup.component.ts, src/app/signup/signup.module.ts
This adds a screen to the social login which requests additional data if it's not supplied.
=> Implement signup screen

src/app/signup/signup.component.ts
=> allow user to add profile details on first login

src/app/header/header.component.html, src/app/header/header.component.scss, src/assets/stylesheets/_layout-debug.scss, src/assets/stylesheets/_layout.scss
Neatens up and improved responsive behavior of the the menu bar. The menu bar is smaller in height to make more space for content as originally requested. The size of the menu text is driven by patternfly/bootstrap $font-size-large , automatically and correctly scaling around this font size.
Also the collapsed menu (mobile) correctly fills the view width and moves to the left. The html structure is also more in line with patternfly (hav-header now included), and the drop down menu icons are correctly aligned.
-The menu bar is too large for the type of application being built ... taking up to much real estate
-The responsive …
=> improved menu responsive behavior and neaten up

src/app/space-wizard/space-wizard.component.ts, src/app/space-wizard/wizard.ts
duplicates the space creation code in space dialog
space dialog was updated to create spaces using api ... this was missing in space-wizard but this pulls the two on par
space creation behavior duplicated in space-wizard
one of several pending pr to refine space wizard
=> space-dialog space creation code replicated in space wizard

src/app/app-routing.module.ts, src/app/header/header.component.html, src/app/header/header.component.ts
Remove the alpha/beta routes from the router and toggle support in the header component
This was not being used
No behavior change...
@joshuawilson 
=> Remove alpha/beta routes and feature toggle logic from the header

src/app/shared/context.service.ts, src/app/shared/dummy.service.ts
=> Fixes #104

src/app/header/header.component.html, src/app/header/header.component.ts, src/app/profile/profile.service.ts, src/app/public/public.component.ts, src/app/shared/authentication.service.ts, src/app/shared/dummy.service.ts, src/app/shared/user.service.ts, src/app/signup/signup.component.ts
=> Fixes #112 by obtaining username from keycloak

src/app/home/home.component.html
=> Fixes #130

src/app/analyze/stack/stack-details/add-work-flow.service.ts, src/app/analyze/stack/stack-details/stack-details.component.spec.ts
Change in the auth token usage. 
Hardcoded bearer token was used
Hard coded token was replaced by Auth Services for the same.
The issue id: #132
=> Change the service to use auth service instead of the hard coded token.

config/webpack.dev.js, src/app/analyze/stack/stack-details/stack-details.component.html, src/app/analyze/stack/stack-details/stack-details.component.ts, src/app/shared/dummy.service.ts
#133. Changes in the public facing API url and code refactoring
1. Changes in the public facing API url
2. Code refactor
URL change
URL change
The issue for that is : #133
=> #133. Changes in the public facing API url and code refactoring

src/app/analyze/analyze-overview/analyze-overview.component.html, src/app/header/header.component.ts, src/app/shared/context.service.ts, src/app/team-membership-dialog/team-membership-dialog.component.html
This ensures the space pages can be reloaded and the UI loads the header consistently.
=> Context service - modify to use url from router parameters

src/app/header/header.component.ts, src/app/home/home.component.html
Also fixes href with no href attribute on the home screen
@joshuawilson
=> Fix for navigation items in context menu

README.md, config/webpack.prod.js
#143 Updated API reference in webpack.prod.js for STACK/Recommender
=> added env variables for API in webpack.prod and updated readme 

src/app/analyze/stack/stack-details/stack-details.component.ts
1. Moved the setStackAnalysisRawData function below the public declarations
2. Added private modifiers for the functions handleNext, handlePrevious, processForm, openModal, closeModal, addWorkItem, getRecommendation, getComponents as they all are being accessed only in this component.
3. Corrected the lint error for a JSON ‘:’
4. Corrected the lines that had more than 100 character in a single line
=> Fixes #146. Addresses lint error changes. 

src/app/analyze/stack/stack-details/stack-details.component.html, src/app/analyze/stack/stack-details/stack-details.component.ts, src/app/analyze/stack/stack-recommendation/stack-recommendation.component.ts, src/app/analyze/stack/stack-recommendation/stack-recommendation.html
fixes #158 
- Made API Call for creation of work item for multiple recommendation
- Corrected variable binding for template literal
=> integrated api call for work item with multiple recommendation

src/app/analyze/stack/stack-details/add-work-flow.service.ts
Have corrected work-item API endpoints
=> corrected api endpoint

config/webpack.common.js, package.json, src/main.browser.ts
Offline plugin uses a service worker to fetch updates to the app in the background
=> chore(build): add offline plugin

config/webpack.common.js, config/webpack.prod.js, src/app/shared-component/modal/modal.ts, src/app/shared-component/wizard/wizard-navigator.ts, src/app/shared-component/wizard/wizard-step-config.ts, src/app/shared-component/wizard/wizard-step.ts, src/app/shared-component/wizard/wizard-steps.ts, src/app/shared-component/wizard/wizard.ts, src/app/shared/entity.service.ts, src/app/space-wizard/space-wizard.component.html, src/app/space-wizard/space-wizard.component.scss, src/app/space-wizard/space-wizard.component.ts, src/app/space-wizard/wizard.ts, src/main.browser.ts
* Fixes #110
* Fixes #177
* Fixes #93
=> fix(space): Improve space wizard

src/app/app.module.ts, src/app/plan/backlog/backlog.component.ts, src/app/plan/backlog/backlog.module.ts, src/app/plan/plan.module.ts
Backlog module was missing the necessary work-item module dependency
=> fix(workitemcomponent): Added work item module dependency  to backlog

package.json, src/app/app.module.ts, src/app/header/header.component.ts, src/app/plan/backlog/backlog-routing.module.ts, src/app/plan/backlog/backlog.component.ts, src/app/shared/common.resolver.ts
Populates spaces on load and adds plan routing which loads work-item/list from the planner module
Also adds context resolver to make sure necessary data is present for work-item component
=> feat(plannerintegration): adds space service to module and fixes routes

src/app/app.component.html, src/app/header/header.component.scss, src/app/plan/backlog/backlog.component.ts, src/assets/stylesheets/_custom.scss, src/assets/stylesheets/_layout.scss, src/assets/stylesheets/_overrides-for-patternfly.scss
updated styles for planner integration style tweaks to cause content to fit page
=> Planner integration style tweaks

package.json, src/app/header/header.component.ts, src/app/profile/spaces/spaces.component.html, src/app/profile/spaces/spaces.component.ts, src/app/shared/dummy.service.ts, src/app/space-wizard/space-wizard.component.ts
Also updated ngx-fabric8-wit to 6.5.0.
Updated use of description attribute of spaces.
=> Update the UI to use SpacesService to search for spaces

package.json, src/app/profile/spaces/spaces.component.ts, src/app/space-wizard/space-wizard.component.ts
Updated fabric8-ui to use the version of SpaceService that uses Observables.
=> fix(spaces): Upgrade to use Observables instead of Promises.

config/helpers.js, config/webpack.dev.js
* Add sourcemaps for dependencies
* Increase watch aggregate timeout
=> chore(build): sourcemaps

src/app/header/header.component.ts
work detail page was missing the submenus 
on click
Fixes #255
=> fix(menus): sub menu load fix on work detail

src/app/header/header.component.html
Fixed the username references in context menu and in dropdown.
**NOTE**: Like in the other PR, I haven't used `ngIf`. Maybe a router guard makes sense to verify that the user object for the currently logged in user is available from UserService.
=> fix(links): Fixed links in Header

package.json, src/app/app-routing.module.ts, src/app/app.component.ts, src/app/header/header.component.html, src/app/header/header.component.ts, src/app/home/home.component.html, src/app/home/home.component.ts, src/app/shared/auth-guard.service.ts, src/app/shared/context-current-user-auth-guard.service.ts, src/app/shared/context-resolver.service.ts, src/app/shared/context.service.ts, src/app/shared/dummy.service.ts, src/app/shared/login.service.ts, src/app/shared/spaces.service.ts, src/app/space-wizard/space-wizard.component.ts
We need to merge https://github.com/fabric8io/fabric8-ui/pull/267 then I can rebase this one and https://github.com/fabric8io/fabric8-ui/pull/268
=> Contexts edge cases5

src/app/shared/login.service.ts, src/app/space-wizard/space-wizard.component.ts
* This avoids double encoding problems
Fixes #274
=> fix(urls): use navigateByUrl

package.json
=> fix(login): use ngx-login-client 0.6.1

src/app/shared/login.service.ts
This should stop circular redirects
Fixes #275
=> fix(login): ban certain urls from redirection

cico_build_deploy.sh
using a proper registry, to work around issues with the xip stuff and also allow us to scale / manage better.
=> move registry to a more reliable host

src/app/app-routing.module.ts, src/app/header/header.component.html, src/app/header/header.component.ts, src/app/header/menus.service.ts, src/app/home/home.component.ts, src/app/shared/context-resolver.service.ts, src/app/shared/dummy.service.ts, src/app/shared/login.service.ts
* Also redirect to a page by default to avoid a confusing local development experience
=> fix(home): Change url of home to _home

src/assets/stylesheets/shared/_custom-variables.scss, src/assets/stylesheets/shared/_layout.scss, src/assets/stylesheets/shared/_overrides-for-patternfly.scss, src/assets/stylesheets/shared/main.scss
DO NOT MERGE
this PR updates the base font to 14 pixels.
=> fix(fonts): update base font to 14px

environments/devshift-cluster.sh, src/app/run/pipelines/pipelines.component.ts, src/app/run/pipelines/pipelines.module.ts
loads oauth config from config json file on disk
before initializing component data
@pmuir @joshuawilson
=> fix(pipelines): fixes pipelines oauth load

src/app/shared/runtime-console/space-namespace.service.ts, src/app/space-wizard/space-wizard.component.html, src/app/space-wizard/space-wizard.component.ts
=> fix: better errors from space wizard

src/app/app-routing.module.ts, src/app/landing-page/landing-page-routing.module.ts, src/app/landing-page/landing-page.component.html, src/app/landing-page/landing-page.component.ts, src/app/landing-page/landing-page.module.ts
Add a local landing page so that you can login from /
Fixes #311
=> fix(login): Add local landing page

package.json, src/app/header/header.component.html, src/app/header/header.component.ts, src/app/shared/fabric8-ui-http.service.ts, src/app/shared/login.service.ts
* Uses uuidv4 to genreate a unique id per request
Fixes #348
=> fix: add x-request-id to all http requests

environments/freeint-cluster.sh, src/app/shared/runtime-console/space-namespace.service.ts
this fix requires the new fabric8-runtime-console version upgrade PR merged first though
=> fix(label-space): fixed creating new ConfigMap

src/app/header/header.component.html
add the status indicator (static) to the header so that it carries over from the log in page
pertains to PR https://github.com/fabric8io/fabric8-ui/issues/349
=> feature(status): add status indicator to header

package.json, src/app/profile/spaces/spaces.component.html, src/app/profile/spaces/spaces.component.scss, src/app/profile/spaces/spaces.component.ts, src/app/profile/spaces/spaces.module.ts
This ensures the spaces listing is not limited to
only first 20 results, or something thereof. Further spaces are
displayed on scroll. Fixes #290
=> fix(spaces): Display using infinite scroll

config/webpack.common.js, src/app/analyze/analyze-overview/analyze-overview.component.html, src/app/analyze/analyze-overview/analyze-overview.component.scss, src/app/analyze/analyze-overview/analyze-overview.component.ts, src/assets/stylesheets/shared/_layout.scss
This adds the basic layout for the Spaces Overview page.
Refer to the [visual design](https://redhat.invisionapp.com/share/TNAXIS9UW#/224156598_Space_Homepage_-empty-option1-001) for state changes.
=> Spaces overview

src/app/header/header.component.html, src/app/header/header.component.scss, src/assets/stylesheets/shared/_overrides-for-patternfly.scss
remove PatternFly overrides from the navigation to better match the visual designs and PatternFly component guidelines.
=> fix(nav): remove PatternFly overrides

src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.ts, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.html
Fixes #393 on platform - space can be null when going back home
=> fix(nullref): fixes null space when navigating home

src/app/analyze/analyze-overview/analyze-overview.component.scss, src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html, src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.scss, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.html, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.scss, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.html, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.scss, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.html, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.scss
update the Spaces page to have scrolling description, even sizes cards and proper button links
=> fix(spaces): update Spaces page layout

src/app/settings/profile/profile.component.html
fixes #453 - temporarily disable editing of e-mail
=> fix(email): prevent editing of email

src/app/profile/profile.service.ts
=> fix: change type from identities to users

package.json
Update fabric8 planner version
=> fix(version): Version update

package.json
Update planner version to 0.21.6
=> fix(version): Update planner version

src/app/home/home.component.html
=> fix: add non-owning username to space list

src/app/space-wizard/common/logger.ts, src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.html, src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.scss, src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.ts, src/app/space-wizard/components/forge-app-generator/forge-app-generator.ts, src/app/space-wizard/models/app-generator.ts, src/app/space-wizard/models/concrete/field-set.ts, src/app/space-wizard/models/concrete/workflow-factory.ts, src/app/space-wizard/models/concrete/workflow.ts, src/app/space-wizard/models/contracts/app-generator-command-parameters.ts, src/app/space-wizard/models/contracts/app-generator-command.ts, src/app/space-wizard/models/contracts/app-generator-forge-command-parameters.ts, src/app/space-wizard/models/contracts/app-generator-forge-command.ts, src/app/space-wizard/models/contracts/app-generator-request.ts, src/app/space-wizard/models/contracts/app-generator-response-context.ts, src/app/space-wizard/models/contracts/app-generator-response.ts, src/app/space-wizard/models/contracts/app-generator-state.ts, src/app/space-wizard/models/contracts/field-info.ts, src/app/space-wizard/models/contracts/field-set.ts, src/app/space-wizard/models/contracts/field-value-option.ts, src/app/space-wizard/models/contracts/forge-command-parameters.ts, src/app/space-wizard/models/contracts/forge-command-pipeline.ts, src/app/space-wizard/services/app-generator.service.ts, src/app/space-wizard/services/concrete/fabric8-app-generator.service.ts, src/app/space-wizard/services/concrete/fabric8-forge.service.ts, src/app/space-wizard/services/contracts/app-generator-service.ts, src/app/space-wizard/services/contracts/forge-service.ts, src/app/space-wizard/services/forge.service.ts, src/app/space-wizard/services/mocks/mock-app-generator.service.ts
Several integration tweaks and fixes related to interfacing with the forge api service. Some refactoring was helpful to simplify the interactions with the server.
- Remaining issues
-turn off / on of browser logging
-http error formatting/handling and display of server side errors needs work
-field descriptions are missing
-multi select control needs some revision
-validation roundtrip time sometimes cause a validation failure to not disable the next button
-api data rewording of titles
-redirect to the spaces or code base page after completion
-user interaction/notification on success
=> Space wizard forge ui 2

src/app/profile/overview/overview.component.html, src/app/profile/overview/overview.component.scss, src/app/profile/overview/overview.component.ts, src/app/profile/overview/overview.module.ts
Update HTML/CSS for profile page
Closes: #535
=> refactor(profile): Update profile page

package.json, src/app/app.module.ts, src/app/space-settings/areas/areas.component.html, src/app/space-settings/areas/areas.component.scss, src/app/space-settings/areas/areas.component.ts, src/app/space-settings/areas/areas.module.ts, src/app/space-settings/areas/create-area-dialog/create-area-dialog.component.html, src/app/space-settings/areas/create-area-dialog/create-area-dialog.component.scss, src/app/space-settings/areas/create-area-dialog/create-area-dialog.component.ts, src/app/space-settings/areas/create-area-dialog/create-area-dialog.module.ts
Includes area list with listing of areas
and create modal for selecting a parent area and name
=> Create Area list and Modal

package.json, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.html, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.module.ts, src/app/home/home.component.html, src/app/home/home.module.ts, src/app/profile/spaces/spaces.component.html, src/app/profile/spaces/spaces.module.ts, src/app/shared/context.service.ts, src/app/space-settings/areas/areas.component.html, src/app/space-settings/areas/areas.module.ts, src/app/space-wizard/space-wizard.component.html, src/app/space-wizard/space-wizard.component.ts, src/app/space-wizard/space-wizard.module.ts
* Uses a pipe to convert space names
* Needs https://github.com/fabric8-ui/ngx-fabric8-wit/pull/67
Fixes #353 Fixes #324 Fixes #323
=> Fix: Adds spaces to space names

src/app/header/header.component.html, src/app/header/header.component.scss, src/app/header/menus.service.ts
update the navigation to match the newest visual design with new layout, icons and interactions
fixes https://github.com/fabric8io/fabric8-ui/issues/540
requires https://github.com/fabric8-ui/ngx-fabric8-wit/pull/72
=> fix(navigation): update navigation to match visual design

src/app/home/home.component.html, src/app/home/home.component.scss, src/app/home/home.component.ts
Update HTML for home dashboard
Wireframes: https://redhat.invisionapp.com/share/XZAOBAOPB#/screens/221480596
Screenshots:
=> feat(Home): Update HTML for home dashboard

src/app/header/header.component.html, src/app/header/header.component.scss
update the space picker and dropdown to be a set width. for longer space names, it will truncate.
=> fix(navigation): update space picker to fixed width

src/app/analyze/analyze-overview/analyze-overview.module.ts, src/app/analyze/analyze.module.ts, src/app/control/control.module.ts, src/app/create/codebases/codebases-add/codebases-add.module.ts, src/app/create/codebases/codebases-item-actions/codebases-item-actions.module.ts, src/app/create/codebases/codebases-item-details/codebases-item-details.module.ts, src/app/create/codebases/codebases-item/codebases-item.module.ts, src/app/create/codebases/codebases.module.ts, src/app/create/create.module.ts, src/app/create/environments/create-environments.module.ts, src/app/create/pipelines/pipelines.module.ts, src/app/home/home.module.ts, src/app/landing-page/landing-page.module.ts, src/app/plan/board/board.module.ts, src/app/plan/plan.module.ts, src/app/profile/overview/overview.module.ts, src/app/profile/profile.module.ts, src/app/profile/resources/resources.module.ts, src/app/profile/spaces/spaces.module.ts, src/app/settings/profile/profile.module.ts, src/app/settings/settings.module.ts, src/app/space-settings/alerts/alerts.module.ts, src/app/space-settings/areas/areas.module.ts, src/app/space-settings/security/security.module.ts, src/app/space-settings/settings-overview/settings-overview.module.ts, src/app/space-settings/space-settings.module.ts, src/app/space-settings/work/work.module.ts
Remove httpmodule from all downstream modules
this fixes 400 errors when refreshing the page or
logging in.
=> fix(httpmodule): remove duplicate http module

src/app/analyze/analyze-overview/analyze-overview.component.html, src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.scss, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.html, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.scss, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.scss, src/app/dashboard-widgets/environment-widget/environment-widget.component.html, src/app/dashboard-widgets/environment-widget/environment-widget.component.scss, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.html, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.scss, src/assets/stylesheets/_base.scss, src/assets/stylesheets/shared/_custom-components.scss
update the Spaces dashboard with new framing to eliminate scrolling and set fixed heights for all cards. New f8-card component created.
=> fix(spaces): updated Dashboard with new framing

src/app/home/home.component.html, src/app/home/home.component.scss
update the Home Dashboard with the new card-f8 framing and cleanup layout
=> fix(home): update Home Dashboard with new framing

src/app/space-settings/areas/create-area-dialog/create-area-dialog.component.html, src/app/space-wizard/space-wizard.component.html
update buttons to use the btn-primary style where appropriate
=> fix(buttons): update button styles

src/app/getting-started/getting-started.component.html, src/app/profile/update/update.component.html
Fixed missing a space before "class".
Added *ngIf else statement for cleaner code.
Cleaned up text copied from mockups -- will get updated text from UXD team.
=> fix(getting-started): Code review changes

src/assets/stylesheets/shared/_overrides-for-patternfly.scss
update the navbar border from blue to red
**this is a priority PR**
=> fix(navbar): update navbar border to red

src/app/getting-started/getting-started.component.ts
Added check for 409 status, where username already exists.
=> fix(getting-started): Fixes issue #804

src/app/analyze/analyze-overview/analyze-overview.component.html, src/app/analyze/analyze-overview/analyze-overview.component.ts, src/app/analyze/analyze-overview/analyze-overview.module.ts, src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html, src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.ts, src/app/dashboard-widgets/environment-widget/environment-widget.component.html, src/app/dashboard-widgets/environment-widget/environment-widget.component.ts
launch forge wizard and set to correct page
=> fix(addtospace): adds add to space from space page

src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.html, src/app/dashboard-widgets/environment-widget/environment-widget.component.html, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.html, src/app/home/home.component.html, src/assets/stylesheets/shared/_custom-components.scss
updates cards to reflect new UX and align 'create' links with headers
=> fix(cards): update cards for new UX

src/app/header/header.component.html, src/app/space-wizard/space-wizard.component.html, src/app/space-wizard/space-wizard.component.scss, src/assets/stylesheets/shared/_layout.scss
closes #589
fixes some styling issues on create space and fixes close button
=> fix(space-wizard): create space ux improvements fixes

src/app/home/home.component.html, src/app/home/home.component.scss
Catherine asked that the logo be centered vertically and to remove some text.
=> fix(home): Updated per review with Catherine

src/app/getting-started/getting-started.component.ts
The Rxjs Observable.combineLatest is not obtaining both GitHub and OpenShift tokens reliably. We need to test both tokens in order to navigate to home page or show the getting started page.
=> fix(getting-started): Rxjs is not obtaining tokens reliably

src/app/header/header.component.html
update to show the static status as OK
fixes https://github.com/fabric8io/fabric8-ui/issues/826
=> fix(status): update default status

src/app/home/home.component.html
Catherine provided a URL for the see more info about OpenShift link.
=> fix(home): Added OpenShift URL for see more info

src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.html, src/app/space-wizard/components/forge-app-generator/forge-app-generator.ts, src/app/space-wizard/space-wizard.component.html, src/app/space-wizard/space-wizard.component.scss, src/assets/stylesheets/shared/_layout.scss
- Refined some of the forge layout page html and styles to better comply with ux design
- also fixed another close button issues
- on forge wizard finish (only if successful) closes dialog
=> Space wizard forge ux improvements and refinements

src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html
bug fix: remove the horizontal card scroll from the Stack Report card on the Spaces dashboard
=> fix(card): remove horizontal card scroll

src/app/analyze/analyze-overview/analyze-overview.component.html, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.html, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.ts
=> fix(pipeline_widget): change the condition to handle no pipeline scenario

src/app/about-modal/about-modal.component.html, src/app/about-modal/about-modal.component.ts, src/app/about-modal/about-modal.module.ts, src/app/app.module.ts, src/app/header/header.component.html, src/app/home/home.component.scss, src/assets/stylesheets/shared/main.scss
Add about modal with build number and timestamp
Closes: #740
=> Add about modal with build number and timestamp

src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.scss, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.ts, src/assets/stylesheets/shared/_custom-components.scss
Changes:
1. HTML changes to bring in loader and overlay
2. Component changes to condition loader
3. Styles to handle scroll overflow issue, loader style
Fixes #877.
=> fix(ux): handle scroll problem, introduce loader with overlay

src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.html, src/app/space-wizard/components/forge-app-generator/forge-app-generator.ts, src/app/space-wizard/services/app-generator.service.ts, src/app/space-wizard/services/concrete/fabric8-app-generator.service.ts, src/app/space-wizard/services/concrete/field-lookup.service.ts, src/app/space-wizard/services/providers/app-generator-service.provider.ts, src/app/space-wizard/space-wizard.component.ts, src/app/space-wizard/space-wizard.module.ts
Fix
- Synchronize default repo name to be the space name ... for new space only
- Update fields to reflect project name id repo name
- Added field mapping for cleanup and ux changes for other fields
- calling text validation on change and not just enter
=> Space wizard repo fixes

Dockerfile.builder, package.json, protractorEE.config.js, src/tests/work-item/work-item-list/EE/openshift-io-poc.spec.js, src/tests/work-item/work-item-list/page-objects/openshift-io-dashboard.page.js, src/tests/work-item/work-item-list/page-objects/openshift-io-spacehome.page.js
Cleaned up test - minimal test at this point - will expand each day.
=> Poc ee test

src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.html, src/app/space-wizard/models/codebase.ts, src/app/space-wizard/services/concrete/field-lookup.service.ts, src/app/space-wizard/space-wizard.component.ts
-modify wizard titles
-remove back button
- few type fixes
=> chore(space-wizard): modify titles

src/app/header/header.component.html, src/app/header/header.component.scss, src/app/header/header.component.ts
set fixed width of the user menu and dropdown
=> fix(usermenu): set fixed width of user menu

src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.html, src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.scss, src/app/space-wizard/services/concrete/app-generator-configuration.service.ts
- improved wizard single select drop down to conform to patternfly and also show descriptions
=> fix(space-wizard): improved pf dropdown with descriptions

src/app/header/header.component.html, src/app/header/header.component.ts
ISSUE : https://github.com/fabric8io/fabric8-planner/issues/1712
=> fix(router): Sticking to iteration filter on view change in planner

src/app/home/developer-poll/developer-poll-routing.module.ts
Home page was inadvertently routed to the poll component because its child route path is empty.
Fixes issue #983
=> fix(home): Developer poll fix

src/app/create/codebases/codebases-add/codebases-add.component.ts, src/app/create/codebases/codebases-item-actions/codebases-item-actions.component.ts, src/app/create/codebases/codebases-item-details/codebases-item-details.component.ts, src/app/create/codebases/codebases-item/codebases-item.component.ts, src/app/create/codebases/codebases.component.ts, src/app/create/codebases/services/github.service.ts
Added code unsubscribe all subscriptions on destroy.
=> fix(codebases): Unsubscribe on destroy

src/app/getting-started/getting-started.component.ts, src/app/getting-started/services/getting-started.service.ts
Added code unsubscribe all subscriptions on destroy.
=> fix(getting-started): Unsubscribe on destroy

src/app/getting-started/getting-started-routing.module.ts
Added AuthGuard to enforce login.
Fixes: https://github.com/fabric8io/fabric8-ui/issues/956
=> fix(getting-started): Added AuthGuard to enforce login

src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html
Fixes issue #553 -- malformed codebase URL
=> fix(analyze): Malformed codebase URL

openshift/fabric8-ui.app.yaml
Please, let me know if you don't think these limits are reasonable.
=> Add resource requests/limits

src/app/getting-started/getting-started.component.html
Added ok icons and read only text after username is updated to match latest mockups.
=> fix(getting-started): Added ok icons and read only text

src/app/home/developer-poll/developer-poll-routing.module.ts, src/app/home/home.component.html, src/app/home/home.component.scss, src/app/home/home.module.ts, src/app/home/work-item-widget/work-item-widget-routing.module.ts, src/app/home/work-item-widget/work-item-widget.component.html, src/app/home/work-item-widget/work-item-widget.component.scss, src/app/home/work-item-widget/work-item-widget.component.ts, src/app/home/work-item-widget/work-item-widget.module.ts
This work item component displays work items assigned to the user.
The select menu allows the user to select from the latest 10 spaces.
By default, the component will select a recent space which is populated with work items.
Reviewed with Catherine.
=> feat(home): Added work item widget to home page

src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.scss, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.ts
Changes:
1. HTML - to introduce the stack name as a part of recommendation
2. SCSS - to handle stylings for recommendations list item and stack name
3. Component - to remove supporting text for no recommendations
=> fix(ux): change the description style of recommendations and added stack name for recommendations

src/app/home/developer-poll/developer-poll.component.html, src/app/home/developer-poll/developer-poll.component.scss
The padding used for the large dev-poll button effects buttons on other pages. This should be limited to the home page, but using a specific style solves the problem.
=> fix(dev-poll): Button style is effects other pages

src/app/home/work-item-widget/work-item-widget.component.html, src/app/home/work-item-widget/work-item-widget.component.scss, src/app/home/work-item-widget/work-item-widget.component.ts
Added work item links and CSS to Work Item widget shown on home page.
=> fix(home): Added work item links and CSS

src/app/profile/services/tenent.service.ts, src/app/profile/update/update.component.html, src/app/profile/update/update.component.ts
Added a temporary update tenant feature to the update profile page per Alask's request
=> feat(tenent): Added update tenent

src/app/space-wizard/common/utilities.ts, src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.html, src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.scss, src/app/space-wizard/components/forge-app-generator/forge-app-generator.ts, src/app/space-wizard/models/app-generator.ts, src/app/space-wizard/models/codebase.ts, src/app/space-wizard/models/contracts/app-generator-error.ts, src/app/space-wizard/models/contracts/app-generator-message.ts, src/app/space-wizard/models/contracts/app-generator-result.ts, src/app/space-wizard/models/contracts/field-info.ts, src/app/space-wizard/models/contracts/field-value-option.ts, src/app/space-wizard/services/app-generator.service.ts, src/app/space-wizard/services/concrete/app-generator-configuration.service.ts, src/app/space-wizard/services/concrete/fabric8-app-generator.service.ts, src/app/space-wizard/services/concrete/fabric8-forge.service.ts, src/app/space-wizard/services/contracts/app-generator-service.ts, src/app/space-wizard/space-wizard.component.html, src/app/space-wizard/space-wizard.component.scss, src/app/space-wizard/space-wizard.component.ts, src/assets/stylesheets/shared/_layout.scss
- augment stack dropdown text and order
- augment pipeline drop down text
- progress indicators
- validation improvements
- ux style improvements  as per ux feedback
=> fix(space-wizard): add stack augmented text and several ux updates 

src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html
Changes:
1. Adds the input [repoInfo] to the stack-details tag
=> fix(repo_info): add the repository information fetched from the build

src/app/space-wizard/space-wizard.component.ts
See also https://github.com/fabric8-ui/ngx-fabric8-wit/pull/89
=> fix: needs a global replace

openshift/fabric8-ui.app.yaml
@joshuawilson I haven't found anything more appropriate than `/` for health checks, if there is any other URL that you'd like to see there, let me know.
=> Add healthchecks

src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.html, src/app/space-wizard/models/contracts/field-value-option.ts, src/app/space-wizard/services/concrete/app-generator-configuration.service.ts, src/app/space-wizard/services/concrete/fabric8-app-generator.service.ts
- allows forge result augmentation to set drop down defaults and text
=> fix(space-wizard): add drop down defaults

src/app/header/menus.service.ts, src/config/fabric8-ui.config.json
this adds a link to the openshift console on the pipelines page
=> feat(openshift-console): ladd a link to the openshift console

src/app/create/pipelines/pipelines.component.ts
=> fix(logging): remove logging

src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.html, src/app/space-wizard/components/forge-app-generator/forge-app-generator.ts, src/app/space-wizard/models/contracts/field-info.ts, src/app/space-wizard/services/concrete/app-generator-configuration.service.ts, src/app/space-wizard/services/concrete/fabric8-app-generator.service.ts
- add more details for validation message
- force name to be lower case, replace spaces with dashes , replace underscores with dashes, trim input
=> fix(space-wizard): improved input data scrubbing and fixing

src/app/space-wizard/common/utilities.ts, src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.html, src/app/space-wizard/components/forge-app-generator/forge-app-generator.ts, src/app/space-wizard/models/contracts/field-info.ts, src/app/space-wizard/services/concrete/app-generator-configuration.service.ts, src/app/space-wizard/services/concrete/fabric8-app-generator.service.ts, src/app/space-wizard/services/concrete/fabric8-forge.service.ts, src/app/space-wizard/services/mocks/mock-app-generator.service.ts
-the specified repo is now propagated through the wizard
- added spinners between  steps due to higher latency caused by more server side validation
- all fields are now sent to forge service on each step
=> fix(space-wizard): fix default demo github failure dependency

src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.html, src/app/space-wizard/components/forge-app-generator/forge-app-generator.ts, src/assets/stylesheets/shared/_layout.scss
- add generated results formatting to make it easy to read
=> fix(space-wizard): ux format of generator results

src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.ts
Replaced UserService.getAllUsers with getUser per Alexey's request.
=> fix(dashboard): Remove call to UserService.getAllUsers

src/app/analyze/analyze-overview/analyze-overview.component.html, src/app/analyze/analyze-overview/analyze-overview.component.scss, src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html, src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.scss, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.html, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.scss, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.html, src/app/home/developer-poll/developer-poll.component.html, src/app/home/home.component.html, src/app/home/home.component.scss, src/app/home/work-item-widget/work-item-widget.component.html, src/app/home/work-item-widget/work-item-widget.component.scss, src/assets/stylesheets/shared/_custom-variables.scss
This PR cleans up the Dashboards for Home and Space. Updates layouts for the cards with embedded lists, adds truncation for extra long Work Item titles and Space names and visual updates.
=> UX cleanup of Dashboards

src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.scss, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.scss, src/app/home/work-item-widget/work-item-widget.component.scss
fixes the truncation and overflow issues when viewing on different resolutions
=> fix(cards): fix truncation and overflow

package.json, src/app/space-settings/collaborators/add-collaborators-dialog/add-collaborators-dialog.component.html, src/app/space-settings/collaborators/add-collaborators-dialog/add-collaborators-dialog.component.ts
This can't be merged until ngx-login-client 0.6.27 is released
=> fix(collaborators): dynamically search users instead of using open api

cico_run_EE_tests.sh, local_run_EE_tests.sh, run_EE_tests.sh
We have to store the screenshots and logs in case the functional tests fail.
=> WIP Store screenshots and log in a volume

cico_run_EE_tests.sh, local_run_EE_tests.sh, run_EE_tests.sh
Reverts fabric8io/fabric8-ui#1165
oops I merged to early
=> Revert "WIP Store screenshots and log in a volume"

src/app/getting-started/getting-started.component.html, src/app/getting-started/getting-started.component.ts
- Removed extra home and profile links.
- Removed setTimeout code to route to home -- no longer needed.
=> fix(getting-started): Removed extra links

src/app/dashboard-widgets/environment-widget/environment-widget.component.html
Update the Environments card to be called Applications and adjust text.
=> fix(card): update Environments card

src/app/space-wizard/services/concrete/app-generator-configuration.service.ts
- updates import github repo header text
=> fix(space-wizard): ux fix import git repo header text

src/app/space-wizard/services/concrete/app-generator-configuration.service.ts
=> fix(space-wizard): ux disable dropdown icons for now

src/app/create/apps/create-apps.module.ts, src/app/create/create-routing.module.ts, src/app/create/pipelines/pipelines.component.html, src/app/create/pipelines/pipelines.component.scss, src/app/create/pipelines/pipelines.component.ts, src/app/create/pipelines/pipelines.module.ts, src/app/dashboard-widgets/environment-widget/environment-widget.component.html, src/app/header/menus.service.ts
see https://github.com/fabric8-ui/fabric8-runtime-console/issues/454
=> feat(apps page): adds the Apps page

src/app/header/menus.service.ts
lets bring the environments page back again as its all lazily loaded now so doesn't perform too many network requests on startup any more
=> fix(environments): add environments page

protractor.config.js, src/tests/work-item/work-item-list/page-objects/common.page.js
This PR contains Page object model for URL tests
=> fix(tests): Add page object model for URL tests

src/app/create/codebases/codebases-add/codebases-add.component.ts
=> fix(codebases): Ensure repo UrlRLs are trimmed

src/app/create/codebases/codebases-routing.module.ts
Fixes https://github.com/fabric8io/fabric8-ui/issues/1246
=> fix(codebases) routing forward to login page when not logged in

package.json, src/app/getting-started/services/provider.service.ts
Added the jwt-decode package to ensure auth token is decoded with UTF-8 support.
Fixes: https://github.com/fabric8io/fabric8-ui/issues/1285
=> fix(providerService): Decode tokens using UTF-8

cico_run_EE_tests.sh, local_cico_run_EE_tests.sh, local_cleanup.sh, local_run_EE_tests.sh, package.json, run_EE_tests.sh, src/tests/work-item/work-item-list/EE/openshift-io-poc.spec.js, src/tests/work-item/work-item-list/page-objects/openshift-io-RHD-login.page.js, src/tests/work-item/work-item-list/page-objects/openshift-io-dashboard.page.js, src/tests/work-item/work-item-list/page-objects/openshift-io-github-login.page.js, src/tests/work-item/work-item-list/page-objects/openshift-io-spacehome.page.js, src/tests/work-item/work-item-list/page-objects/openshift-io-start.page.js
This PR can wait until May 5 - thx!
=> fix (test): update EE test to run on production openshift.io

package.json, src/app/header/header.component.html, src/app/space-wizard/space-wizard.component.html
These changes will make the EE tests easier to write and maintain.
=> IDs for EE tests

src/index.ejs
implement the cache controls from the OSIO marketing page
=> fix(cache): implement cache control from OSIO marketing page

cico_run_EE_tests.sh, run_EE_tests.sh
I guess we can log the EE_TEST_USERNAME. I want to see if the env variables is set in any moment as as ENV variable in the jenkins slave
=> Test if the env variable is propagated to the test container

cico_run_EE_tests.sh, run_EE_tests.sh
I reverted the previous changes and added the EE variables for username and password to the jenkins-env
=> Revert 1379 troubleshooting empty var values

cico_run_EE_tests.sh, protractorEE.config.js, src/tests/work-item/work-item-list/EE/urlTests.spec.js, src/tests/work-item/work-item-list/page-objects/common.page.js, src/tests/work-item/work-item-list/page-objects/openshift-io-dashboard.page.js, src/tests/work-item/work-item-list/page-objects/openshift-io-spacehome.page.js, src/tests/work-item/work-item-list/page-objects/openshift-io-start.page.js, src/tests/work-item/work-item-list/page-objects/resources.page.js, src/tests/work-item/work-item-list/page-objects/settings.page.js
This is the Part 1 of URL tests 
This PR is only hitting the URLS and checking results (positive cases only ).
Part 2 is in progress!
=> Poc URL tests

package.json, src/app/create/codebases/services/github.service.ts, src/app/create/codebases/services/github.ts, src/app/getting-started/services/getting-started.service.ts, src/app/profile/services/copy.service.ts, src/app/profile/update/update.component.html, src/app/profile/update/update.component.scss, src/app/profile/update/update.component.ts, src/app/profile/update/update.module.ts, src/app/shared/login.service.ts
Added functionality to link GitHub and OpenShift accounts.
Added a button to fetch/link the user's GitHub avatar image URL.
Added a new ngx-widgets component to count remaining characters for user's bio.
Added Bootstrap switch (jw-bootstrap-switch-ng2) component to toggle profile properties.
Added collapsible panel to display user's token.
Added CopyService to copy the user's token to system clipboard.
Added company field not shown in screenshot.
Layout and features are based on latest mockup from @jryhanyc:
https://redhat.invisionapp.com/share/3ZBFATW28#/screens
Reviewed with @catrobson
Notes:
1. This PR depends on ngx-widgets https://github.com/fabric8-ui/ngx-widgets/pull/77
2. This PR depends on ngx-login-client https://github.com/fabric8-ui/ngx-login-client/issues/27
3. The user's …
=> feat(): Added functionality to update profile page

src/app/space-wizard/services/concrete/fabric8-app-generator-configurator.service.ts, src/app/space-wizard/services/concrete/fabric8-app-generator.service.ts
=> fix(space-wizard): append labelSpace on execute

src/app/getting-started/services/getting-started.service.ts, src/app/profile/update/update.component.html, src/app/profile/update/update.component.ts
Marked email input field as required.
Trimmed email string value to ensure it’s not removed when profile is updated.
Removed empty profile object properties.
=> fix(edit profile): Email must be required

src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.scss, src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.ts, src/app/space-wizard/components/forge-app-generator/forge-app-generator.ts, src/app/space-wizard/components/forge-panel/forge-panel.component.html, src/app/space-wizard/models/concrete/workflow-step.ts, src/app/space-wizard/models/concrete/workflow-transition.ts, src/app/space-wizard/models/concrete/workflow.ts, src/app/space-wizard/models/contracts/workflow-action.ts, src/app/space-wizard/models/contracts/workflow-direction.ts, src/app/space-wizard/models/contracts/workflow-transition-action.ts, src/app/space-wizard/models/contracts/workflow-transition-direction.ts, src/app/space-wizard/models/contracts/workflow-transition.ts, src/app/space-wizard/models/workflow.ts, src/app/space-wizard/services/concrete/fabric8-app-generator-configurator.service.ts, src/app/space-wizard/services/concrete/fabric8-app-generator.service.ts
- add notification on successful codebase add to space
- tech debt removal : more refactoring into smaller components
- fix forge panel navigate to space
=> chore(space-wizard): tech debt removal and fixes

src/app/analyze/analyze-overview/analyze-overview.component.ts, src/app/create/pipelines/pipelines.component.ts, src/app/space-wizard/components/create-space/create-space.component.html, src/app/space-wizard/components/create-space/create-space.component.ts, src/app/space-wizard/models/modal-host.ts, src/app/space-wizard/services/concrete/fabric8-app-generator-configurator.service.ts, src/app/space-wizard/space-wizard.component.ts
When opening the space wizard component in a dialog, it is no longer neccesay to set the current space or set starting step. You can now pass starting step as parameter of IHostdialog open
=> chore(space-wizard): simplify dlg.open prerequisites

src/app/space-wizard/components/forge-app-generator/forge-app-generator-service-client.ts, src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.html, src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.ts, src/app/space-wizard/space-wizard.module.ts
- refactors forge service client to have correct dependency injection non singleton semantics and is now injected into component instead of being explicitly instantiated.
=> chore(space-wizard): refactor forge client

src/app/profile/overview/activity/activity.component.ts, src/app/profile/overview/overview.component.ts
Fixes https://github.com/fabric8io/fabric8-ui/issues/1258
=> fix(profile): Activity button should nav to home

src/app/app.module.ts, src/app/shared/api-locator.service.ts, src/app/shared/config/fabric8-ui-config.service.ts, src/app/shared/config/fabric8-ui-config.ts, src/app/shared/login.service.ts, src/config/fabric8-ui.env.js, src/index.ejs
lets try another approach to #1316 by loading eagerly a blob of JSON on startup so that the env vars can be injected without blocking via @Inject which simplifies the code changes to all the fabric8-ui modules
=> fix(runtime env vars): lets load env vars

package.json, src/app/dashboard-widgets/create-work-item-widget/create-work-item-overlay/create-work-item-overlay.component.html, src/app/dashboard-widgets/create-work-item-widget/create-work-item-overlay/create-work-item-overlay.component.ts
Applies changes to the Platform code to get it working with the new Planner source layout.
Please do not merge until the Planner CI/CD is working again. I'll let you know when we have that in place.
=> fix(planner): refactored to use the new Planner library layout.

src/app/space-wizard/components/app-generator-single-selection-list/app-generator-single-selection-list.component.html, src/app/space-wizard/components/app-generator-single-selection-list/app-generator-single-selection-list.component.scss, src/app/space-wizard/components/app-generator-single-selection-list/app-generator-single-selection-list.component.ts, src/app/space-wizard/components/forge-app-generator/forge-app-generator-service-client.ts, src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.html, src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.scss, src/app/space-wizard/components/forge-panel/forge-panel.component.html, src/app/space-wizard/components/forge-step-view/forge-step-view.component.html, src/app/space-wizard/components/forge-step-view/forge-step-view.component.ts, src/app/space-wizard/services/concrete/fabric8-app-generator-configurator.service.ts, src/app/space-wizard/space-wizard.module.ts
- refactor wizard single select into separate component in which the selections also have collapsible selections as per ux designs
- required field indicator is now red as per ux spec
- tooltip fixes
fixes #862 
improves fidelity to designs #541
=> feat(space-wizard): add collapsible single select widget

package.json, src/app/space-settings/collaborators/collaborators.component.html, src/app/space-settings/collaborators/collaborators.component.scss, src/app/space-settings/collaborators/collaborators.component.ts, src/app/space-settings/collaborators/collaborators.module.ts
=> fix(collaborators): add infinite scroll to collaborators view

src/app/profile/overview/activity/activity.component.html
fixes https://github.com/openshiftio/openshift.io/issues/190
=> fix(typo): change Openshift to OpenShift

src/app/space-wizard/components/app-generator-step-view/app-generator-step-view.component.html, src/app/space-wizard/components/app-generator-step-view/app-generator-step-view.component.scss, src/app/space-wizard/components/app-generator-step-view/app-generator-step-view.component.ts, src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.html, src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.ts, src/app/space-wizard/components/space-configurator/space-configurator.component.html, src/app/space-wizard/services/concrete/fabric8-app-generator-configurator.service.ts, src/app/space-wizard/services/concrete/fabric8-app-generator.service.ts, src/app/space-wizard/space-wizard.component.html
- adds titles to the steps as per ux request
-adds a label to the pipeline selector
- adds starter project to as candidate  for 'code from scratch'. 
know issues:
==========
- still has a few responsive challenges with long pipeline step titles
Closes #1441
=> feat(space-wizard): add wizard step titles

environments/openshift-prod-cluster.sh, src/app/create/pipelines/pipelines.component.ts
when viewing pipelines which have a space label lets filter out any
pipelines not matching the current space
=> fix(space): filter pipelines on space

src/app/app.module.ts, src/app/profile/spaces/spaces.component.ts, src/app/shared/context.service.mock.ts, src/app/shared/context.service.spec.ts, src/app/shared/context.service.ts, src/app/shared/event.service.ts
Fixes https://github.com/fabric8io/fabric8-ui/issues/1351
=> Notify.space.deletion

src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.scss, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.ts
1. dashboard is now loading with the latest valid pipeline
2. added the message for no recommendations
=> fix(analytic-dash-widget): load fix

README.md, environments/local-cluster.sh, src/app/space-wizard/services/fabric8-app-generator-configurator.service.ts, src/config/fabric8-ui.env.js, src/config/oauth.json
lets add the new status list widget
=> polish docs

src/app/dashboard-widgets/environment-widget/environment-widget.component.html, src/app/dashboard-widgets/environment-widget/environment-widget.component.ts
Fixes 1475 - environments code has been ported in from the runtime console
=> fix(widget): fix environments widget on space page

src/app/space-wizard/services/fabric8-app-generator-configurator.service.ts
@mitchharpur we need to pre-process and remove space in the input we send to forge.
WIP do not merge yet
Fixes https://github.com/fabric8io/fabric8-ui/issues/1549
=> fix(space-wizard): remove space in github organisation sent to forge

src/app/dashboard-widgets/environment-widget/environment-widget.component.ts
=> fix(spacenav): fix navigating from space on first click

src/app/header/header.component.html, src/app/header/header.component.less, src/app/header/header.component.ts
Update the navigation to support responsive views, in accordance with PatternFly breakpoints. This PR closes #1529.
=> fix(nav): update nav for responsive views

README.md, src/assets/stylesheets/shared/main.less
update the README for the Less conversion work and add a proper shared file for multiple components.
closes https://github.com/fabric8io/fabric8-ui/issues/1564
=> fix(README): update for Less conversion

src/app/space-wizard/components/app-generator-build-pipeline-view/app-generator-build-pipeline-view.component.less, src/app/space-wizard/components/app-generator-multiple-selection-label-list/app-generator-multiple-selection-label-list.component.less, src/app/space-wizard/components/app-generator-single-selection-dropdown/app-generator-single-selection-dropdown.component.less, src/app/space-wizard/components/app-generator-single-selection-list/app-generator-single-selection-list.component.less, src/app/space-wizard/components/app-generator-step-view/app-generator-step-view.component.less, src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.html, src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.less, src/app/space-wizard/components/space-configurator/space-configurator.component.less, src/app/space-wizard/components/space-creator/space-creator.component.html, src/app/space-wizard/components/space-creator/space-creator.component.less, src/app/space-wizard/space-wizard.component.less
update the styles of the wizard to use variables where necessary, as well as overall code cleanup
closes #588
=> fix(wizard): update styles of wizard

src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.html, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.less, src/app/profile/spaces/spaces.component.html, src/app/settings/profile/profile.component.html, src/app/space-settings/collaborators/collaborators.component.html, src/app/team-membership-dialog/team-membership-dialog.component.html
add consistency to the buttons in fabric8-ui, according to PatternFly guidelines.
closes #1572
=> fix(buttons): add consistency to button styling

src/app/analyze/analyze-overview/analyze-overview.component.html, src/app/create/codebases/codebases-item/codebases-item.component.less, src/app/create/codebases/codebases-toolbar/codebases-toolbar.component.less
update a few pages for responsive usage. first of many updates.
closes https://github.com/fabric8io/fabric8-ui/issues/1346
=> fix(responsive): update pages for responsive

src/app/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.less
fix the overlap in the codebase list due to adding a new element once a che workspace is created
=> fix(list): fix overlap in codebase list

src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.html, src/app/space-wizard/services/fabric8-app-generator.client.ts, src/app/space-wizard/space-wizard.component.less
Fix the message styling to match the form layouts. Also sets a minimum height for the wizard panels for consistency.
fixes https://github.com/fabric8io/fabric8-ui/issues/1558 and https://github.com/fabric8io/fabric8-ui/issues/1561
=> fix(wizard): fix message styling

src/app/space-wizard/components/space-configurator/space-configurator.component.html, src/app/space-wizard/components/space-configurator/space-configurator.component.less, src/app/space-wizard/services/fabric8-app-generator-configurator.service.ts, src/app/space-wizard/space-wizard.component.ts
Fixes https://github.com/fabric8io/fabric8-ui/issues/1487
Fixes https://github.com/fabric8io/fabric8-ui/issues/1578
fixes #1417
=> fix(wizard): simplify steps

src/app/profile/overview/activity/activity.component.html, src/app/profile/overview/overview.component.html, src/app/profile/overview/overview.component.less, src/app/profile/overview/spaces/spaces.component.html, src/app/profile/overview/spaces/spaces.component.less, src/app/profile/overview/work-items/work-items.component.html, src/app/profile/update/update.component.html, src/app/profile/update/update.component.less
update the user profile for responsive use and guidelines
=> fix(profile): update user profile

src/app/shared/dummy.service.ts, src/tests/work-item/work-item-list/page-objects/openshift-io-registration.page.js
This addresses @qodfathr 's comment on not having things in the UI that are not functional.
=> Remove not existing space templates from space creation drop down

src/app/space-settings/areas/create-area-dialog/create-area-dialog.component.html, src/app/space-settings/areas/create-area-dialog/create-area-dialog.component.less, src/app/space-settings/areas/create-area-dialog/create-area-dialog.component.ts, src/app/space-settings/collaborators/add-collaborators-dialog/add-collaborators-dialog.component.html, src/app/space-settings/collaborators/add-collaborators-dialog/add-collaborators-dialog.component.less, src/app/space-settings/collaborators/add-collaborators-dialog/add-collaborators-dialog.component.ts
update modal styles to properly position Title and other elements
closes https://github.com/fabric8io/fabric8-ux/issues/507
=> fix(modals): update modal styles

src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html
add a selector placeholder for the Stack Recommendations widget
=> fix(placeholder): add selector placeholder

src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.html, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.less, src/app/dashboard-widgets/recent-pipelines-widget/recent-pipelines-widget.component.html, src/app/dashboard-widgets/recent-pipelines-widget/recent-pipelines-widget.component.less
Match the recent pipelines widget with the space pipelines widget. Updated custom classes to be reusable across multiple widgets. Renamed class to match Code Guidelines regarding BEM.
=> fix(widget): match recent pipelines widget

src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.html, src/app/space-wizard/components/forge-app-generator/forge-app-generator.component.less, src/app/space-wizard/components/space-configurator/space-configurator.component.html, src/app/space-wizard/components/space-configurator/space-configurator.component.less, src/app/space-wizard/components/space-creator/space-creator.component.html, src/app/space-wizard/components/space-creator/space-creator.component.less, src/app/space-wizard/space-wizard.component.html
remove various title tooltips, update styles for consistency and clean up error messages
=> fix(wizard): update ux styles for wizard

src/app/profile/spaces/spaces.component.html, src/app/profile/spaces/spaces.component.ts
Fixes - https://github.com/fabric8-ui/fabric8-ux/issues/505
=> fix(spacedelete): only allow creator to delete space

src/app/space-wizard/common/utilities.spec.ts, src/app/space-wizard/common/utilities.ts, src/app/space-wizard/components/app-generator-multiple-selection-label-list/app-generator-multiple-selection-label-list.component.ts, src/app/space-wizard/services/fabric8-app-generator-configurator.service.ts, src/app/space-wizard/services/fabric8-app-generator.client.mock.ts, src/app/space-wizard/services/fabric8-app-generator.client.spec.ts, src/app/space-wizard/services/fabric8-app-generator.client.ts
Fixes https://github.com/fabric8-ui/fabric8-ui/issues/1613
=> Import.wizard.multi.repos

src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.html, src/app/home/work-item-widget/work-item-widget.component.html
fixes the Work Item ID string to pull the proper Work Item Number by the context of the Space it resides in.
fixes https://github.com/fabric8-ui/fabric8-ui/issues/1630
=> fix(WI-ID): fix ID string to pull by Space

src/app/space-wizard/services/fabric8-app-generator.client.ts
Fixes https://github.com/fabric8-ui/fabric8-ui/issues/1613 regression introduced by multi repo selection
=> fix(quickstart): wizard should display codebase repo

config/webpack.dev.js, environments/local-kubernetes.sh, package.json, src/app/shared/config/fabric8-ui-config.ts, src/config/fabric8-ui.env.js, src/config/oauth.json
to swizzle the kubernetes friendly URLs when running the console on
kubernetes
=> fix(kubernetes): enable kubernetes mode

src/app/about-modal/about-modal.component.html, src/app/about-modal/about-modal.component.less, src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.html, src/app/dashboard-widgets/environment-widget/environment-widget.component.html, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.html, src/app/dashboard-widgets/recent-pipelines-widget/recent-pipelines-widget.component.html, src/app/home/home.component.html, src/app/home/work-item-widget/work-item-widget.component.html, src/app/home/work-item-widget/work-item-widget.component.less, src/app/profile/overview/spaces/spaces.component.html, src/app/profile/overview/spaces/spaces.component.less, src/assets/stylesheets/shared/_cards.less
change the class prefixes from `io` to `f8` to match the organization.
=> fix(prefix): change class prefix from `io` to `f8`

README.md
Update the Readme in order to document the new style structure and proper methods for adding new styles. Also updates various spelling errors.
=> fix(readme): Update Readme for new style structure

src/app/profile/update/update.component.html, src/app/profile/update/update.component.ts
This adds the basic checkbox to the profile page for feature toggles.
=> feature-toggle setup profile

src/app/app-routing.module.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/create/create-routing.module.ts, src/app/profile/profile-routing.module.ts, src/app/settings/settings-routing.module.ts, src/app/shared/branding.service.ts, src/app/space-settings/space-settings-routing.module.ts
When a page finishes loading, update the title tag of the app to reflect the title of the current
page. If no title is found, just show the default branding name
fixes #1377
=> feat(dynamic page titles): Updating the title tag based on the page

src/app/exp-feature-page/exp-feature-page-routing.module.ts, src/app/exp-feature-page/exp-feature-page.component.html, src/app/exp-feature-page/exp-feature-page.component.less, src/app/exp-feature-page/exp-feature-page.component.ts, src/app/exp-feature-page/exp-feature-page.module.ts, src/app/exp-feature-page/exp-feature-page.service.ts
This still needs wiring but I wanted to get it in so that we could have UX/UI collaboration on it.
=> add an experimental feature page

src/app/profile/update/update.component.html, src/app/profile/update/update.component.less
update the Update Profile page to reflect the new layout design
closes https://github.com/fabric8-ui/fabric8-ui/issues/1691 and https://github.com/fabric8-ui/fabric8-ux/issues/534
Note: The "Update Tenant" button will be removed at a later date.
=> fix(profile): update layout for Update Profile page

src/app/profile/update/update.component.ts
=> fix(profileflag): profile save of experimental feature flag value

src/app/profile/overview/overview.component.less, src/app/profile/update/update.component.less
fixes the profile picture resizing issue when a user updated their profile picture in the Update area
=> fix(image): fix resizing of image on update

src/app/shared/api-locator.service.ts
=> [WIP] remove references to 'api.prod-preview' and change to use 'prod-preview'

src/app/exp-feature-page/exp-feature-page.component.html, src/app/exp-feature-page/exp-feature-page.component.less, src/assets/stylesheets/shared/_experimental.less, src/assets/stylesheets/shared/osio.less
Adds the styles and layout for the Experimental Feature Flag.
=> fix(exp): update experimental feature layout and styles

src/app/app.component.ts, src/app/exp-feature-page/exp-feature-banner.component.html, src/app/exp-feature-page/exp-feature-banner.component.ts, src/app/shared/experimental-feature.resolver.ts
=> fix(offline): add support to view workitems offline when exp mode is enabled

src/app/profile/update/update.component.html, src/app/profile/update/update.component.less, src/assets/stylesheets/shared/_forms.less, src/assets/stylesheets/shared/osio.less
Update the Edit Profile page layout, styles and content. Set buttons as fixed elements.
closes https://github.com/fabric8-ui/fabric8-ux/issues/538
=> fix(profile): update Edit Profile page

src/app/exp-feature-page/exp-feature-banner.component.html, src/app/exp-feature-page/exp-feature-page.component.html, src/assets/stylesheets/shared/_experimental.less
update the layout of the experimental blank state page, as well as styles for the page bar
=> fix(experimental): update styles for experimental styles

src/app/error/error.component.html, src/app/error/error.component.ts
Remove items that are not available, hook up links and update routing
closes https://github.com/fabric8-ui/fabric8-ui/issues/1724
=> fix(error): update layout and links for error page

src/app/space-wizard/components/app-generator-single-input/app-generator-single-input.component.html, src/app/space-wizard/components/app-generator-single-selection-dropdown/app-generator-single-selection-dropdown.component.html, src/app/space-wizard/components/app-generator-single-selection-list/app-generator-single-selection-list.component.html, src/app/space-wizard/services/fabric8-app-generator.client.ts
Fixes https://github.com/fabric8-ui/fabric8-ui/issues/1725
Fixes https://github.com/fabric8-ui/fabric8-ui/issues/1440
Fixes https://github.com/fabric8-ui/fabric8-ui/issues/1743
=> fix(validation): wizard should display input validation errors

src/app/space-wizard/services/fabric8-app-generator.client.spec.ts, src/app/space-wizard/services/fabric8-app-generator.service.mock.ts, src/app/space-wizard/services/fabric8-app-generator.service.spec.ts, src/app/space-wizard/services/fabric8-app-generator.service.ts
Fixes https://github.com/fabric8-ui/fabric8-ui/issues/1742
=> fix(wizard): display forge root cause of error

src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html, src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.less, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.html, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.less, src/app/dashboard-widgets/environment-widget/environment-widget.component.html, src/app/dashboard-widgets/environment-widget/environment-widget.component.less, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.html, src/app/dashboard-widgets/recent-pipelines-widget/recent-pipelines-widget.component.html, src/app/home/home.component.html, src/app/home/home.component.less, src/app/home/work-item-widget/work-item-widget.component.html, src/app/home/work-item-widget/work-item-widget.component.less, src/assets/stylesheets/shared/_cards.less
update the card styles to take into account the updated layouts from the patternfly-ng library
closes https://github.com/fabric8-ui/fabric8-ux/issues/549
=> fix(cards): update card styles after patternfly-ng integration

src/app/create/create-routing.module.ts, src/app/shared/runtime-console/pipelines.service.ts
Fixes https://github.com/fabric8-ui/fabric8-ui/issues/1746
=> feat(dashboard): to display only pipeline belonging to the current space

src/app/space-wizard/components/app-generator-multiple-selection-label-list/app-generator-multiple-selection-label-list.component.ts, src/app/space-wizard/components/app-generator-single-input/app-generator-single-input.component.html
Fixes https://github.com/fabric8-ui/fabric8-ui/issues/1751
=> fix(import.wizard): multiple-selection should display valiadation error

src/app/header/header.component.less
update the mobile navigation to fit properly and stack list elements in an expected method
closes https://github.com/fabric8-ui/fabric8-ux/issues/550
=> fix(header): update mobile navigation

src/app/create/pipelines/pipelines.component.less, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.html, src/app/delete-account-dialog/delete-account-dialog.component.less, src/app/home/home.component.less, src/app/profile/update/update.component.less, src/app/team-membership-dialog/team-membership-dialog.component.less, src/assets/stylesheets/shared/_variables.less
update the various font declarations to use either em or predefined variables
closes https://github.com/fabric8-ui/fabric8-ux/issues/551
=> fix(typography): update fonts to use em and variables

README.md
update the link to the HTML/CSS Guidelines; improve brief explanation
closes https://github.com/fabric8-ui/fabric8-ui/issues/1777
=> fix(readme): update HTML/CSS guidelines section

src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html, src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.ts
Restructure the widget code so the api is only called a single time
=> fix(widget): only call codebase api one time

src/app/shared/context.service.ts, src/app/space-wizard/services/fabric8-app-generator-configurator.service.ts
see https://github.com/openshiftio/openshift.io/issues/383
=> fix(pipelines): avoid the missing space label

src/app/getting-started/getting-started.component.html, src/app/getting-started/getting-started.component.less, src/app/layout/header/header.component.html, src/app/layout/header/header.component.less
update the getting started page
closes https://github.com/fabric8-ui/fabric8-ui/issues/1815
=> fix(gettingstarted): update Getting Started page

src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.ts
=> fix(issue): replace update with change

README.md
This is just to force a build to test the build system.
cc @vpavlin
=> fix(docs): update README

package.json
upgrade PatternFly to 3.26.1 with bug fixes and 11 new icons
closes https://github.com/fabric8-ui/fabric8-ui/issues/1823
=> fix(patternfly): upgrade PatternFly version

cico_build_deploy.sh
Reverts fabric8-ui/fabric8-ui#1844
The build is failing.
=> Revert "Use push.registry.devshift.net"

src/app/space/wizard/services/fabric8-app-generator.client.ts
Fixes https://github.com/fabric8-ui/fabric8-ui/issues/1857
=> fix(wizard): display results according to forge API change

Dockerfile.deploy, protractor.config.js, run_functional_tests.sh
We are getting an error in chromedriver https://ci.centos.org/job/devtools-fabric8-ui/1969/console
=> Fix func tests: stick to one chromedriver version

src/app/space/wizard/components/app-generator-single-input/app-generator-single-input.component.html
Fixes https://github.com/fabric8-ui/fabric8-ui/issues/1850
=> fix(validation): clear error validation on change

src/a-runtime-console/kubernetes/ui/pipeline/build-stage-view/build-stage-view.component.html, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html
=> fix(issue): modify html input structure to take in information about build number and application name in both dashboard and pipelines view

src/a-runtime-console/kubernetes/store/space.store.ts, src/app/dashboard-widgets/environment-widget/environment-widget.component.ts, src/app/profile/cleanup/cleanup.component.html, src/app/profile/cleanup/cleanup.component.ts, src/app/profile/services/tenent.service.ts, src/app/profile/update/update.component.html
Remove spaces from recent spaces list
Fix button text on profile page
Fix minor code issues in template
=> fix(cleanup): fix ui issues with tenant cleanup

src/app/profile/cleanup/cleanup.component.html, src/app/profile/cleanup/cleanup.component.less, src/app/profile/cleanup/cleanup.component.ts
Update the CSS/HTML for the cleanup process. This includes alignments, headings and colors.
=> fix(cleanup): update CSS/HTML for cleanup process

src/app/profile/tenant/tenant.component.html, src/app/profile/tenant/tenant.component.ts
lets add a team version too so we can configure that in addition to jenkins & che versions in the acceptance tests in PRs
=> fix(acceptancetests): add teamVersion

src/app/profile/tenant/tenant.component.html, src/app/profile/tenant/tenant.component.ts
so that we can link the tenant page from PR comments so folks can try out PRs via 2 clicks from a PR comment
also `Update Tenant` on save
polished names
=> fix(testing): allow versions to be passed in via query arguments

package.json
=> fix(version): update fabric8-stack-analysis-ui to 0.3.2

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/shared/profile-resolver.service.ts
Fixes https://github.com/openshiftio/openshift.io/issues/662
@jstrachan
=> fix(profile): add canonical link to profile

src/app/getting-started/getting-started.component.html, src/app/landing-page/landing-page.component.html, src/app/profile/tenant/tenant.component.html
lets make it easier to reuse the E2E tests on fabric8 and OSIO
use the same IDs for the fabric8 login page as we use on OSIO to simplify testing
=> fix(testing): simplify E2E on fabric8

src/app/dashboard-widgets/create-work-item-widget/create-work-item-overlay/create-work-item-overlay.component.ts, src/app/landing-page/landing-page.component.ts, src/app/layout/footer/footer.component.ts, src/app/layout/header/header.component.less, src/app/profile/overview/activity/activity.component.ts, src/app/profile/profile.component.ts, src/app/profile/tenant/tenant.component.html, src/app/profile/update/update.component.less, src/app/space/analyze/analyze.component.ts, src/app/space/create/codebases/codebases-item-details/codebases-item-details.component.ts, src/app/space/create/create.component.ts, src/app/space/settings/alerts/alerts.component.ts, src/app/space/settings/security/security.component.ts, src/app/space/settings/settings-overview/settings-overview.component.ts, src/app/space/settings/space-settings.component.ts, src/app/space/settings/work/work.component.ts, src/assets/stylesheets/shared/_layout.less, src/assets/stylesheets/shared/_mixins.less, src/assets/stylesheets/shared/_overrides.less, src/assets/stylesheets/shared/_typography.less, src/assets/stylesheets/shared/_variables.less
clean up the styles to verify code conditions; remove extra on unnecessary files.
* As part of this PR, empty `.less` files were removed so that they are not added to the header as an empty `<style>` block.
* The _tenant page was updated to be centered on the screen.
* Old variables removed.
=> fix(styles): clean styles and extra files

.htmlhintrc, .stylelintignore, .stylelintrc, config/webpack.common.js, package.json, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.less, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.less, src/app/layout/header/header.component.less, src/app/profile/cleanup/cleanup.component.less, src/app/profile/update/update.component.html, src/assets/stylesheets/shared/_experimental.less, src/assets/stylesheets/shared/_layout.less, src/assets/stylesheets/shared/_overrides.less, src/assets/stylesheets/shared/_utilities.less, src/assets/stylesheets/shared/_variables.less
This PR adds a proper stylelint configuration file and a proper htmlhint configuration file to fabric8-ui. These files are run as part of the build process.
Any failures to meet the various criteria as defined in the configuration files will fail the build.
**Note:** The runtime-console and wizard are not included as part of the linting/hint checks. A separate PR is needed to fix the multitude of issues in those folders.
=> fix(code): add code quality checks to build process

src/app/space/wizard/space-wizard.component.ts
Fixes https://github.com/fabric8-ui/fabric8-ui/issues/1912
@jstrachan / @corinnekrych
=> fix(redirect): fix space redirect when already in context

src/app/profile/cleanup/cleanup.component.html, src/app/profile/cleanup/cleanup.component.ts, src/app/profile/profile-routing.module.ts
Fixes https://github.com/fabric8-ui/fabric8-ux/issues/649 
Fixes https://github.com/openshiftio/openshift.io/issues/651 
Fixes https://github.com/fabric8-ui/fabric8-ui/issues/1948
=> fix(reset): display warning if spaces can't be deleted

src/app/space/wizard/components/forge-app-generator/forge-app-generator.component.ts
Fixed https://github.com/openshiftio/openshift.io/issues/479
=> fix(wizard): rename forge Wizard to application Wizard

src/app/space/wizard/services/fabric8-app-generator-configurator.service.ts
Fixes https://github.com/openshiftio/openshift.io/issues/671
=> fix(import.wizard): display warning for overriden files

src/app/dashboard-widgets/recent-pipelines-widget/recent-pipelines-widget.component.html, src/app/home/home.component.html, src/app/home/work-item-widget/work-item-widget.component.html
The purpose of this is to as following:
- fix work item empty state font
- update text on the "recent active pipelines"
- update the capitalization to be same with[ PatternFly Capitalization Guideline](https://www.patternfly.org/styles/terminology-and-wording/#capitalization)
Related to this story:
https://github.com/fabric8-ui/fabric8-ux/issues/653
@catrobson Please help to review about this one, thanks.
=> fix(accounthome): update font and text for Acount Home page

package.json
update the PatternFly dependency to match other repos
=> fix(patternfly): update PatternFly dependency to 3.27.1

src/a-runtime-console/kubernetes/ui/app/list/list.app.component.html, src/app/home/home.component.less, src/app/profile/overview/spaces/spaces.component.less, src/app/space/analyze/analyze-overview/analyze-overview.component.less, src/app/space/create/codebases/codebases.component.less, src/app/space/create/pipelines/pipelines.component.less, src/app/space/settings/areas/areas.component.less, src/app/space/settings/collaborators/collaborators.component.html, src/assets/stylesheets/shared/_layout.less, src/assets/stylesheets/shared/_overrides.less
- Update the background color for various pages to be a lighter shade of grey
- Adjust various areas due to new grey background
closes https://github.com/fabric8-ui/fabric8-ux/issues/640
=> fix(backgrounds): update background color for various pages

src/app/space/wizard/common/utilities.spec.ts
Trying out a PR with a couple of simple tests on the clone function.
=> added unit tests in utilities package

src/a-runtime-console/kubernetes/model/kubernetesresource.model.ts
lets import the icons so that the URLs work when using webpack image resources with dynamic file names
=> fix(applications): import icons

src/app/layout/header/header.component.html
fixes https://github.com/openshiftio/openshift.io/issues/1035
=> Add logout button in "Getting Started" page

src/app/space/forge-wizard/abstract-wizard.component.ts
fixes https://github.com/openshiftio/openshift.io/issues/1137
=> fix(quickstart): wizard stack id

src/app/space/forge-wizard/abstract-wizard.component.ts, src/app/space/forge-wizard/import-pages/step1/organisation-step.component.html, src/app/space/forge-wizard/import-pages/step2/repositories-step.component.html, src/app/space/forge-wizard/import-pages/step3/pipeline-step.component.html, src/app/space/forge-wizard/import-pages/step4/build-config-step.component.html, src/app/space/forge-wizard/import-pages/step5/review-step.component.html, src/app/space/forge-wizard/import-wizard.component.ts, src/app/space/forge-wizard/quickstart-pages/step2/project-info-step.component.html, src/app/space/forge-wizard/quickstart-pages/step3/pipeline-quickstart-step.component.html, src/app/space/forge-wizard/quickstart-wizard.component.less, src/app/space/forge-wizard/quickstart-wizard.component.ts
fixes https://github.com/openshiftio/openshift.io/issues/1138
=> fix(wizard-css): Encapsulation.Noe for wizard components

src/app/layout/header/header.component.html, src/app/layout/header/header.component.less, src/app/profile/overview/overview.component.html, src/app/profile/spaces/spaces.component.html, src/app/profile/update/update.component.html, src/app/space/settings/collaborators/collaborators.component.html, src/assets/stylesheets/shared/_icons.less
Update the user icon the be circular. This is the new default styling for all user images, and is set by the class `icon-user`.
Closes https://github.com/fabric8-ui/fabric8-ux/issues/726
=> fix(icons): Update user icon to be circular

src/app/layout/header/header.component.html
fix the header to properly show the user menu with icon style update
**OLD**
**NEW**
=> fix(gettingstarted): fix getting started header

src/app/space/forge-wizard/components/single-input/single-input.component.html, src/app/space/forge-wizard/forge-wizard.module.ts, src/app/space/forge-wizard/import-wizard.component.spec.ts, src/app/space/forge-wizard/quickstart-pages/step2/project-info-step.component.ts, src/app/space/forge-wizard/quickstart-pages/step2/project-name-validation.pipe.spec.ts, src/app/space/forge-wizard/quickstart-pages/step2/project-name-validation.pipe.ts
Fixes https://github.com/openshiftio/openshift.io/issues/1156 and https://github.com/openshiftio/openshift.io/issues/1157 and https://github.com/openshiftio/openshift.io/issues/1210
=> fix(forge-wizard): project name validation to match forge backend

src/app/space/forge-wizard/components/forge-exception/forge-exception.component.html, src/app/space/forge-wizard/quickstart-pages/step1/choose-quickstart.component.spec.ts, src/app/space/forge-wizard/quickstart-pages/step2/project-info-step.component.spec.ts, src/app/space/forge-wizard/quickstart-pages/step2/project-info-step.component.ts, src/app/space/forge-wizard/quickstart-pages/step3/pipeline-quickstart-step.component.spec.ts
fixes https://github.com/openshiftio/openshift.io/issues/1158
=> fix(wizard): client side validation for java package groupid

src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.html, src/app/home/home.component.html, src/app/home/work-item-widget/work-item-widget.component.html, src/assets/stylesheets/shared/_cards.less, src/assets/stylesheets/shared/_overrides.less
Update the List Styles in Cards to have alternating row colors, per visual design.
Closes https://github.com/fabric8-ui/fabric8-ux/issues/737
=> fix(cards): Update List Styles in Cards

src/app/home/home.component.ts
Update the Learn More link on the Dashboard to point to the Features page.
requires https://github.com/openshiftio/openshift.io/pull/1361
related to https://github.com/fabric8-ui/fabric8-ux/issues/745
fixes https://github.com/openshiftio/openshift.io/issues/1333
=> fix(link): Update Learn More link on Dashboard

src/app/space/create/apps/apps.component.html, src/app/space/create/apps/apps.component.spec.ts, src/app/space/create/apps/apps.module.ts, src/app/space/create/apps/components/deployment-card/deployment-card.component.spec.ts, src/app/space/create/apps/components/resource-card.component.html, src/app/space/create/apps/components/resource-card.component.spec.ts, src/app/space/create/apps/components/resource-card.component.ts, src/app/space/create/apps/services/apps.service.ts
fixes https://github.com/openshiftio/openshift.io/issues/1373
=> refactor(deployments): Use component properties instead of static values

src/app/space/create/codebases/codebases-toolbar/codebases-toolbar.component.html, src/app/space/create/codebases/codebases-toolbar/codebases-toolbar.component.less, src/app/space/create/codebases/codebases-toolbar/codebases-toolbar.component.ts
Fix tooltip alignment in the Codebases toolbar; add text to provide more spacing and meet future design specs.
fixes: https://github.com/openshiftio/openshift.io/issues/1179
=> fix(tooltip): Fix tooltip alignment in toolbar

src/app/space/create/apps/components/resource-card.component.ts
fixes openshiftio/openshift.io#1412
=> fix(deployments): resource-card unsubscribes on destroy

src/app/space/create/deployments/components/deployment-card/deployment-card.component.html, src/app/space/create/deployments/deployments.module.ts
fixes https://github.com/openshiftio/openshift.io/issues/1452
Note that this depends on https://github.com/fabric8-ui/fabric8-ui/pull/2252
=> style(deployments): Add tooltip to checkmark in deployment card

config/webpack.dev.js, src/app/space/create/codebases/codebases-delete/codebase-delete-dialog.component.html, src/app/space/create/codebases/codebases-delete/codebase-delete-dialog.component.less, src/app/space/create/codebases/codebases-delete/codebase-delete-dialog.component.ts, src/app/space/create/codebases/codebases-delete/codebase-delete-dialog.module.ts, src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.component.html, src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.component.less, src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.component.spec.ts, src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.component.ts, src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.module.ts, src/app/space/create/codebases/codebases-item/codebases-item.component.html, src/app/space/create/codebases/codebases-item/codebases-item.component.ts, src/app/space/create/codebases/codebases.component.html, src/app/space/create/codebases/codebases.component.ts, src/app/space/create/codebases/codebases.module.ts, src/app/space/create/codebases/services/codebases.service.spec.ts, src/app/space/create/codebases/services/codebases.service.ts
feat(codebases): add ability to remove codebase from the list
The kabob menu contains Remove item, clicking on which - displays the confirm dialog for codebase
removal. After success deletion - the codebase list is updated
Closes openshiftio/openshift.io#192
=> Add ability to remove codebase

src/app/space/create/codebases/codebases-item/codebases-item.component.ts, src/app/space/create/codebases/codebases.component.ts, src/app/space/create/codebases/services/che.ts
https://github.com/openshiftio/openshift.io/issues/1476
Tested locally by applying migration scripts to free-int:
=> openshift.io #1476: Adding notifications about workspaces migration to Multi-Tenant che server

src/a-runtime-console/kubernetes/components/pipeline-status/pipeline-status.component.less, src/a-runtime-console/kubernetes/components/resource-header/resource.header.component.less, src/a-runtime-console/kubernetes/ui/pipeline/build-stage-view/build-stage-view.component.less, src/a-runtime-console/kubernetes/ui/pipeline/full-history/full-history.pipeline.component.less, src/a-runtime-console/kubernetes/ui/pipeline/history/history.pipeline.component.less, src/a-runtime-console/kubernetes/ui/pipeline/list/list.pipeline.component.less
Remove hard coded browser prefixes in favor of autoprefixer. Autoprefixer to be added as part of a separate PR.
=> fix(prefixes): remove hard coded browser prefixes

src/app/space/create/deployments/deployments-donut/deployments-donut.component.spec.ts
closes https://github.com/openshiftio/openshift.io/issues/1679
=> fix(deployments): fix mock service in donut unit test

src/app/space/create/deployments/deployments.component.spec.ts, src/testing/mock.ts
closes https://github.com/openshiftio/openshift.io/issues/1644
I have a use-case in mind here already (DeploymentsComponent spec), but I'm unsure of how best to demo that. Should I include a follow-up commit on this branch/PR to do that small refactoring?
=> feat(test): add createMock test util

src/app/profile/overview/overview.component.html, src/app/profile/overview/overview.component.ts, src/app/shared/context.service.ts
This is part of preparing the profile for github linking/unlinking
=> fix(profile): hide profile when not viewing own

src/app/space/create/deployments/deployments.component.spec.ts
Refactor DeploymentsComponent spec to use TestContext. This is cleaner with less repeat boilerplate, but more importantly, hopefully will eliminate an intermittent test failure as seen here: https://jenkins.cd.test.fabric8.io/job/fabric8-ui/job/fabric8-ui/job/PR-2305/4/display/redirect (due to better test component set up performed by the TestContext).
=> Use test-context for DeploymentsComponent spec

environments/openshift-free-int-cluster.sh, src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.component.ts, src/app/space/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.ts
This change is in the context of trying to resolve the issues related to having tests run automatically on each PR - https://github.com/fabric8-ui/fabric8-ui/pull/1873
=> fix(test): updated references for prod-preview from free-int to free-stg

src/app/space/forge-wizard/service/forge-config.ts
This reverts commit c89997183a6bb39f455d92c506548b354b897733 (merged from #2309).
=> Revert "context no longer contains 'forge'"

src/app/space/create/deployments/apps/deployment-card.component.spec.ts, src/app/space/create/deployments/deployments-donut/deployments-donut.component.html, src/app/space/create/deployments/deployments-donut/deployments-donut.component.spec.ts, src/app/space/create/deployments/deployments-donut/deployments-donut.component.ts, src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts, src/app/space/create/deployments/services/deployments.service.ts
Addresses part of https://github.com/openshiftio/openshift.io/issues/1622
After this, updating to use the API will only be a change in `deployments.service.ts` to make a HTTP request.
=> refactor(deployments): update pod scaling to use deployments service

src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.html, src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.ts
This addresses https://github.com/openshiftio/openshift.io/issues/1713
=> fix(deployments): fix deployments donut loading when pods data is falsy

src/app/space/create/deployments/apps/deployment-card.component.html, src/app/space/create/deployments/apps/deployment-card.component.ts
see https://github.com/openshiftio/openshift.io/issues/1712
=> Deployment card graph label upper bounds should be dynamic

src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.less, src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.spec.ts, src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.ts, src/app/space/create/deployments/deployments-donut/deployments-donut.component.html, src/app/space/create/deployments/deployments-donut/deployments-donut.component.less, src/app/space/create/deployments/deployments-donut/deployments-donut.component.spec.ts, src/app/space/create/deployments/deployments-donut/deployments-donut.component.ts
This addresses https://github.com/openshiftio/openshift.io/issues/1534
=> feat(deployments): add legend to donut charts

config/webpack.prod.js, package.json, tslint.json
This will update the TS linter but not turn it on. The build will still pass with failing lint errors/warning.
fixes #1352
=> Update linter rules

src/app/space/analyze/analyze-overview/analyze-overview.component.html, src/app/space/analyze/analyze-overview/analyze-overview.component.ts
fixes https://github.com/openshiftio/openshift.io/issues/868
=> fix(analyze-overview): Require user to be logged in to add to space

src/app/profile/overview/connected-accounts/connected-accounts.component.html, src/app/profile/overview/connected-accounts/connected-accounts.component.spec.ts, src/app/profile/overview/connected-accounts/connected-accounts.component.ts, src/app/shared/account/provider.service.ts
Also deleted a bunch of old code
=> fix(openshift): add openshift connection refresh

src/a-runtime-console/kubernetes/ui/pipeline/input-action-dialog/input-action-dialog.component.ts
fix for issue https://github.com/openshiftio/openshift.io/issues/1771
=> (fix 1771) added url prefix

src/app/profile/overview/connected-accounts/connected-accounts.component.html, src/app/profile/overview/connected-accounts/connected-accounts.component.spec.ts, src/app/profile/overview/connected-accounts/connected-accounts.component.ts, src/app/shared/account/provider.service.ts
Completes https://github.com/fabric8-ui/fabric8-ux/issues/792
=> fix(status): add github status from new auth api

src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.less, src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.ts
fixes https://github.com/openshiftio/openshift.io/issues/1779
=> fix(deployments): do not underline Resource Usage title on hover

src/app/space/create/deployments/apps/deployment-card.component.html, src/app/space/create/deployments/apps/deployment-card.component.spec.ts, src/app/space/create/deployments/apps/deployment-card.component.ts, src/app/space/create/deployments/services/deployments.service.spec.ts, src/app/space/create/deployments/services/deployments.service.ts
hide app cards when app is not deployed in a given environment
fixes https://github.com/openshiftio/openshift.io/issues/1749
=> feat(deployments): hide undeployed app cards

src/app/profile/update/update-routing.module.ts, src/app/profile/update/update.module.ts, src/app/shared/owner-guard.service.spec.ts, src/app/shared/owner-guard.service.ts
fixes https://github.com/openshiftio/openshift.io/issues/871
=> fix(profile): Update redirection if not logged in or different user

src/app/profile/update/update.component.html
I've added an 80 char limit for the user's name and company. The URL, Bio, and email are 255 chars.
Fixes https://github.com/openshiftio/openshift.io/issues/1605
=> Add character limits to the update profile page

src/app/profile/update/update.component.html, src/app/profile/update/update.component.less, src/app/profile/update/update.component.ts
fixes https://github.com/openshiftio/openshift.io/issues/1566
=> feat(profile): navigate home on successful tenant update

lint/src/app/profile/update/update.component.ts.xml, src/app/space/create/deployments/apps/deployment-details.component.spec.ts, src/app/space/create/deployments/apps/deployment-details.component.ts
fixes https://github.com/openshiftio/openshift.io/issues/1750
=> fix(deployments) limit sparkline data to fix unbounded data

src/app/space/create/deployments/deployments.component.ts
=> fix(deployments): unsubscribe deployments subscriptions on destroy

src/app/profile/update/update.component.html
We will need to enable email updates since we now fully support email verification on the backend side.
=> Enable email update

src/app/space/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.spec.ts, src/app/space/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.ts
fixes openshiftio/openshift.io#1457
=> fix(codebases): open workspace in separate browser window avoiding popup blocker messages

src/app/space/create/deployments/apps/deployment-card.component.spec.ts
This patch introduces testContext and initContext to our deployment cards tests.
=> enhancement(deployments): addtest context to deployment card tests

src/app/home/home.component.ts, src/app/layout/header/header.component.ts
Fixes https://github.com/openshiftio/openshift.io/issues/1868
=> fix(urlmatch): make sure not to do exact match on _home

.stylelintrc, src/a-runtime-console/kubernetes/components/pipeline-status/pipeline-status.component.less, src/a-runtime-console/kubernetes/components/resource-header/resource.header.component.less, src/a-runtime-console/kubernetes/ui/app/list/list.app.component.less, src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.less, src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.less, src/assets/stylesheets/shared/_animations.less, src/assets/stylesheets/shared/_cards.less, src/assets/stylesheets/shared/_layout.less, src/assets/stylesheets/shared/_mixins.less, src/assets/stylesheets/shared/_overrides.less, src/assets/stylesheets/shared/_utilities.less
Update stylelint rules and fix files that do not match the new rules.
=> fix(stylelint): Update stylelint rules

src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html
fixes https://github.com/openshiftio/openshift.io/issues/1480
The link above has a description of why the choice to do this was done. I am still open for other options however if there are better ways.
=> fix(analyze-overview): redirect add codebases button to codebases page

src/app/layout/header/header.component.less
fixes https://github.com/openshiftio/openshift.io/issues/1875
=> fix(header): remove extra red borders from header

src/app/home/home.component.less
fixes https://github.com/openshiftio/openshift.io/issues/1876
=> fix(home): remove extra margins, causing horizontal scroll

src/app/profile/update/update.component.html
Fixes https://github.com/openshiftio/openshift.io/issues/1978
=> fix(typo): update text on feature page

src/app/profile/update/update.component.ts
fixes https://github.com/openshiftio/openshift.io/issues/1961
=> clean(feature-flag): remove unused  user consent enum

src/app/space/create/deployments/services/deployments.service.ts
fixes https://github.com/openshiftio/openshift.io/issues/1878
=> fix(deployments): change service polling rate to match OSO

src/app/layout/header/header.component.less
Incorrect color, currently in production:
Updated to matching & correct color:
=> fix(navbar): fix incorrect navbar color

src/app/space/create/deployments/services/deployments.service.spec.ts
Fixes a lint issue in the file. Also makes the import follow the format of other imports in the file.
=> fix(deployments): fix linting in deployments service spec

src/app/space/create/deployments/services/deployments.service.ts
fixes https://github.com/openshiftio/openshift.io/issues/2098
=> fix(deployments): handle empty object responses for timeseries data

src/app/space/create/deployments/services/deployments.service.ts
fixes https://github.com/openshiftio/openshift.io/issues/2037
=> fix(deployments): mitigate duplicate timeseries stat emissions

src/app/space/forge-wizard/quickstart-pages/step2/project-info-step.component.spec.ts, src/app/space/forge-wizard/quickstart-pages/step2/project-info-step.component.ts
Fixes: https://github.com/openshiftio/openshift.io/issues/1807
=> fix(bug): allows single character groupId in application wizard flow

openshift/fabric8-ui.app.yaml, openshift/fabric8-ui.config.yaml
=> fix(build): set the env var references in the config.yaml 

src/app/profile/update/update.component.html, src/app/profile/update/update.component.ts
Add a button for resetting a user's password from their profile.
related to https://github.com/fabric8-ui/fabric8-ux/issues/801
**Note:** This is only the HTML/CSS for adding the password reset button. This does not include the linkage to activate this functionality.
=> fix(password): Add password reset button

src/app/app.module.ts
Part of openshiftio/openshift.io#2025
=> fix(feature-flag): add missing provider to app.module

src/app/space/create/deployments/services/deployments.service.spec.ts, src/app/space/create/deployments/services/deployments.service.ts
log HTTP errors encountered in DeploymentsService. Also, propagate error
rather than emitting an empty result, so that consumers can be made
aware and add their own specific handling of error cases.
fixes https://github.com/openshiftio/openshift.io/issues/2158
Not sure if we want to use NotificationsService here, but at least Logger should be used IMO.
=> feat(deployments): add DeploymentsService logging

src/app/space/create/deployments/services/deployments.service.spec.ts
This adds some basic tests for `DeploymentsService:getPods`
=> fix(deployments): add tests for getPods deployments service

src/app/space/create/deployments/deployments.component.spec.ts, src/app/space/create/deployments/services/deployments.service.ts
Addresses https://github.com/openshiftio/openshift.io/issues/2020
=> fix(deployments): unsubscribe deployments service subscriptions

cico_run_tests.sh
Modify our build script to use a cached build container when possible
=> Fix(build): Improve PR build time by caching the build container when possible

src/app/space/create/deployments/apps/deployment-details.component.html, src/app/space/create/deployments/apps/deployment-details.component.spec.ts, src/app/space/create/deployments/apps/deployment-details.component.ts
fixes https://github.com/openshiftio/openshift.io/issues/2115
=> feat(deployments): hide card details when deployment has 0 pods

src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/app/feature-flag/banner/feature-banner.component.ts, src/app/feature-flag/service/feature-acknowledgement.service.spec.ts, src/app/feature-flag/service/feature-acknowledgement.service.ts, src/app/getting-started/services/getting-started.service.ts
Makes choice about experimental features persistent
Fixes: https://github.com/openshiftio/openshift.io/issues/1557
=> fix(feature-banner): make choice about experimental features persistent

package.json, src/app/shared/exception.handler.ts
=> fix(exceptions): only log exceptions for prod and preview and fix user

openshift/fabric8-ui.app.yaml
This change relies on:
https://github.com/openshiftio/saas-openshiftio/pull/612
https://github.com/fabric8io/fabric8-pipeline-library/pull/379
=> set up env var for feature toggle

src/app/space/settings/areas/create-area-dialog/create-area-dialog.component.ts
This addresses https://github.com/openshiftio/openshift.io/issues/2198 by removing the unused variable, as well as the unused lifecycle functions.
=> fix(areas): remove unused variable and lifecycle functions

src/app/space/create/deployments/services/deployments.service.spec.ts
refactor doMockHttpTest to accept a params object, supporting a new feature allowing doMockHttpTest
to test both plain event emission tests as well as error emission tests, and refactor all applicable
tests to suit
=> test(deployments): refactor DeploymentsService test helper

src/app/space/create/codebases/services/workspaces.service.ts
Should be merged together with https://github.com/fabric8-services/fabric8-wit/pull/1893
=> openshift.io 1439: Changing endpoint for obtaining workspaces per codebase due to update in wit

config/webpack.prod.js
=> update sourcemap to hidden so that we have them in prod but only for errors

src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.html, src/app/dashboard-widgets/environment-widget/environment-widget.component.html, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.html, src/app/dashboard-widgets/recent-pipelines-widget/recent-pipelines-widget.component.html, src/app/home/home.component.html, src/app/home/work-item-widget/work-item-widget.component.html, src/app/space/create/codebases/codebases.component.ts, src/assets/stylesheets/shared/_cards.less
Remove all Empty State icons from the empty Card states
related to https://github.com/fabric8-ui/fabric8-ux/issues/849
=> fix(emptystate): Remove Empty State icons

src/app/feature-flag/service/feature-acknowledgement.service.ts
Fixes https://github.com/openshiftio/openshift.io/issues/2265
=> fix(feature-acknowledgement): deal with anonymous user

src/app/space/create/deployments/apps/deployment-details.component.spec.ts, src/app/space/create/deployments/apps/deployment-details.component.ts
Allow 15 minute data preload request to complete before subscribing for
per-minute data polling updates
fixes https://github.com/openshiftio/openshift.io/issues/2267
The fix here uses an Observable that fires a completion event after the initial stats response is received, and only subscribing for the polling updates strictly after that completion event occurs. This guarantees the ordering so that the 15 minute preload data is received and processed before a polling update response can be received. The tests take advantage of this as well, using a plain Subject rather than a BehaviorSubject so that the event emission can be controlled and the polling updates stalled for the purposes of the preloading tests.
=> fix(deployments): wait for preload request completion

src/app/space/create/deployments/apps/deployment-details.component.spec.ts, src/app/space/create/deployments/apps/deployment-details.component.ts
fixes https://github.com/openshiftio/openshift.io/issues/2204
=> fix(deployments): do not display fractional bytes

src/app/space/create/codebases/services/workspaces.service.ts
replaces https://github.com/fabric8-ui/fabric8-ui/pull/2534
=> fix(workspaces): add support for old workspaces URL

src/app/dashboard-widgets/environment-widget/environment-widget.component.html
it needs to point to Deployments
=> fix(deployments): update the dashboard widget for Environments 

src/app/space/create/deployments/apps/deployment-card.component.html, src/app/space/create/deployments/apps/deployment-card.component.ts, src/app/space/create/deployments/deployments-donut/deployments-donut.component.html
This addresses https://github.com/openshiftio/openshift.io/issues/2309
Thoughts on the solution?
=> fix(deployments): use preventDefault instead of stopPropagation to handle clicking of items on deployment cards

src/app/space/wizard/space-wizard.component.spec.ts
This PR addresses [issue #923](https://github.com/openshiftio/openshift.io/issues/923)[0], and more specifically, addresses the sub-task of unit tests for the space-wizard module.
=> test(space-wizard): add unit tests for space-wizard.component

src/app/space/add-app-overlay/add-app-overlay.component.html, src/app/space/add-space-overlay/add-space-overlay.component.html, src/app/space/add-space-overlay/add-space-overlay.component.less
Update the new overlay content and designs to take into account changing designs.
related to https://github.com/fabric8-ui/fabric8-ux/issues/911
=> fix(overlays): update overlay content and designs

src/app/space/create/deployments/apps/deployments-apps.component.html, src/app/space/create/deployments/apps/deployments-apps.component.less, src/app/space/create/deployments/apps/deployments-apps.component.ts, src/app/space/create/deployments/deployments.module.ts, src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.html, src/app/space/create/deployments/resource-usage/loading-utilization-bar.component.html, src/app/space/create/deployments/resource-usage/loading-utilization-bar.component.ts, src/app/space/create/deployments/resource-usage/resource-card.component.html, src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts, src/app/space/create/deployments/resource-usage/resource-card.component.ts
These patches introduce a loading display for the deployment page, as described by the design mock [here](https://redhat.invisionapp.com/share/YSDL0KRKW#/screens/273548936). 
Screenshot (to see this, I had to apply a set timeout to the call to updateResources in deployments.component.ts) 
Solves : https://github.com/openshiftio/openshift.io/issues/1865
=> Deployments loading

src/app/space/create/pipelines/pipelines.component.spec.ts, src/app/space/create/pipelines/pipelines.component.ts
fixes https://github.com/openshiftio/openshift.io/issues/2421
=> fix(pipelines): use "text" filtering rather than "select"

src/app/dashboard-widgets/environment-widget/environment-widget.component.ts, src/app/feature-flag.mapping.ts, src/app/feature-flag/feature-flag.module.ts, src/app/feature-flag/feature-loader/feature-loader.component.spec.ts, src/app/feature-flag/feature-loader/feature-loader.component.ts, src/app/feature-flag/service/feature-acknowledgement.service.spec.ts, src/app/feature-flag/service/feature-acknowledgement.service.ts, src/app/feature-flag/service/feature-toggles.service.spec.ts, src/app/feature-flag/service/feature-toggles.service.ts, src/app/space/analyze/analyze-overview/analyze-overview.component.html, src/app/space/analyze/analyze-overview/analyze-overview.module.ts
Fixes https://github.com/openshiftio/openshift.io/issues/2363
Documentation on how to use dynamic load in wiki: https://github.com/fabric8-ui/fabric8-ui/wiki/fabric8-toggles#my-feature-is-a-component-i-want-to-dynamically-load
=> feat(feature-flag): dynamic load of components

package.json
fixing issue https://github.com/openshiftio/openshift.io/issues/2531
=> chore bump version of ngx-forge

src/app/profile/my-spaces/my-spaces.component.spec.ts
This PR addresses [issue #923](https://github.com/openshiftio/openshift.io/issues/923)[0], and more specifically, addresses the sub-task of unit tests for the my-spaces component. The spec file covers all of the public functions, and majority of the branches and lines of code.
=> test(my-spaces): add unit tests for the my-spaces component

src/app/space/create/deployments/apps/deployment-card.component.spec.ts, src/app/space/create/deployments/apps/deployment-card.component.ts
The OK tooltip is sometimes 'Everyting is OK' and sometimes 'Everyting
is OK.'. This causes problems in E2E tests.
=> fix(tooltip) Fixed typo in tooltip.

src/app/space/create/deployments/services/deployment-status.service.spec.ts, src/app/space/create/deployments/services/deployment-status.service.ts
https://github.com/openshiftio/openshift.io/issues/2542
The fix applied here is to have the DeploymentStatusService also account for the Pods belonging to a deployment when determining its resource usage/quota status. If the deployment has 0 pods then the status for CPU and Memory usages are defined to be OK. The previous behaviour erroneously compared 0 usage to 0 quota and determined that there was a problem since the usage had reached the quota.
=> Deployments: "0 used / 0 quota" should not cause a resource usage quota error after scaling down to 0 pods

src/app/profile/cleanup/cleanup.component.spec.ts
This short PR addresses errors that were being displayed when running the cleanup component unit tests. The cause of these errors are with the `component.contextSubscription` not being mocked, so when `ngOnDestroy()` is called it is trying to unsubscribe from an undefined object (related StackOverflow discussion [here](https://stackoverflow.com/questions/43350115/testing-angular-component-with-unsubscribe-error-during-cleanup-of-component/43471130) [0]). 
This fix creates a spy object for `component.contextSubscription` that spies on the unsubscribe function, which will not cause errors when `ngOnDestroy()` is called.
Before:
After:
[0] https://stackoverflow.com/questions/43350115/testing-angular-component-with-unsubscribe-error-during-cleanup-of-component/43471130
=> fix(cleanup): fix errors being logged by the cleanup component unit tests

src/app/space/create/codebases/codebases-item-heading/codebases-item-heading.component.ts
rh-che issue https://github.com/redhat-developer/rh-che/issues/448
Updating message to be suitable for che 5 -> che 6 workspace migration
=> fix(codebases): updating message for workspace migration

src/app/space/create/deployments/apps/delete-deployment-modal.component.html, src/app/space/create/deployments/apps/delete-deployment-modal.component.ts, src/app/space/create/deployments/apps/deployment-card-container.component.ts, src/app/space/create/deployments/apps/deployment-card.component.html, src/app/space/create/deployments/apps/deployment-card.component.less, src/app/space/create/deployments/apps/deployment-card.component.spec.ts, src/app/space/create/deployments/apps/deployment-card.component.ts, src/app/space/create/deployments/apps/deployment-details.component.spec.ts, src/app/space/create/deployments/apps/deployments-apps.component.html, src/app/space/create/deployments/apps/deployments-apps.component.ts, src/app/space/create/deployments/deployments.module.ts, src/app/space/create/deployments/services/deployments.service.ts
These patches connect our front end to the backend's new deletion API. I'll provide screenshots as soon as I can, I'm waiting on a few builds to finish so that I can have deployments to delete. 
Solves: https://github.com/openshiftio/openshift.io/issues/2474
=> Deployment delete

src/app/space/create/deployments/services/deployments.service.spec.ts, src/app/space/create/deployments/services/deployments.service.ts
(re-try of https://github.com/fabric8-ui/fabric8-ui/pull/2651)
Cancel future queries for timeseries data after the deployment is observed to have disappeared (ie.
via deletion).
fixes https://github.com/openshiftio/openshift.io/issues/2663
Stop timeseries requests from being made for deleted deployments by establishing a happens-before relationship between applications requests (which indicate which deployments exist) and timeseries stats requests, and checking for deployment existence before each stats request.
=> fix(deployments): cancel timeseries queries after deletion

src/app/space/create/deployments/apps/deployment-card.component.spec.ts, src/app/space/create/deployments/apps/deployment-card.component.ts, src/app/space/create/deployments/apps/deployment-details.component.spec.ts, src/app/space/create/deployments/apps/deployment-details.component.ts, src/app/space/create/deployments/deployments-donut/deployments-donut.component.spec.ts, src/app/space/create/deployments/deployments-donut/deployments-donut.component.ts, src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts, src/app/space/create/deployments/services/deployment-status.service.spec.ts, src/app/space/create/deployments/services/deployment-status.service.ts, src/app/space/create/deployments/services/deployments.service.spec.ts, src/app/space/create/deployments/services/deployments.service.ts
=> refactor(deployments): reorder params to be space, env, app

src/app/layout/error/error.component.html, src/app/layout/error/error.component.less
=> fix(404): Update 404 update

src/app/dashboard-widgets/environment-widget/environment-widget.component.ts, src/app/space/create/deployments/apps/deployment-card-container.component.spec.ts, src/app/space/create/deployments/apps/deployment-card-container.component.ts, src/app/space/create/deployments/apps/deployment-card.component.html, src/app/space/create/deployments/apps/deployment-card.component.spec.ts, src/app/space/create/deployments/apps/deployment-card.component.ts, src/app/space/create/deployments/apps/deployment-details.component.spec.ts, src/app/space/create/deployments/apps/deployment-details.component.ts, src/app/space/create/deployments/apps/deployments-apps.component.spec.ts, src/app/space/create/deployments/apps/deployments-apps.component.ts, src/app/space/create/deployments/deployments-donut/deployments-donut.component.spec.ts, src/app/space/create/deployments/deployments-donut/deployments-donut.component.ts, src/app/space/create/deployments/deployments.component.spec.ts, src/app/space/create/deployments/deployments.component.ts, src/app/space/create/deployments/models/environment.ts, src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.spec.ts, src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.ts, src/app/space/create/deployments/resource-usage/resource-card.component.html, src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts, src/app/space/create/deployments/resource-usage/resource-card.component.ts, src/app/space/create/deployments/services/deployments.service.spec.ts, src/app/space/create/deployments/services/deployments.service.ts
fixes https://github.com/openshiftio/openshift.io/issues/2585
=> refactor(deployments): convert environment object to a string

Dockerfile.deploy
Related to fabric8-ui/fabric8-ui-openshift-nginx#17
=> Update base nginx v to include asset cache control

src/app/space/create/deployments/apps/deployment-card.component.spec.ts, src/app/space/create/deployments/apps/deployment-card.component.ts, src/app/space/create/deployments/apps/deployment-details.component.spec.ts, src/app/space/create/deployments/apps/deployment-status-icon.component.ts, src/app/space/create/deployments/apps/deployments-apps.component.ts, src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.spec.ts, src/app/space/create/deployments/deployments-donut/deployments-donut.component.ts, src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts, src/app/space/create/deployments/services/deployment-status.service.ts, src/app/space/create/deployments/services/deployments.service.ts
fixes https://github.com/openshiftio/openshift.io/issues/2753
=> refactor(deployments): cleanup: removed unused imports

.gitignore, package.json, src/app/space/app-launcher/services/app-launcher-dependency-check.service.ts, src/app/space/app-launcher/services/app-launcher-gitprovider.service.spec.ts, src/app/space/app-launcher/services/app-launcher-gitprovider.service.ts, src/app/space/app-launcher/services/app-launcher-mission-runtime.service.ts, src/app/space/app-launcher/services/app-launcher-project-summary.service.spec.ts, src/app/space/app-launcher/services/app-launcher-project-summary.service.ts
This PR integrates the services as mentioned below for New getting started flow , which is currently an Internal feature in OSIO.
- Functionality added to get gitHub repos for user's Organization or namespace
- Services for summary screen
- Services for progress screen
Associated User-stories : 
https://github.com/openshiftio/openshift.io/issues/2514
https://github.com/openshiftio/openshift.io/issues/2515
https://github.com/openshiftio/openshift.io/issues/2511
InvisionApp : https://redhat.invisionapp.com/share/VGF1RF15J#/screens/286900869
Associated PRs : 
https://github.com/fabric8-launcher/ngx-launcher/pull/103
https://github.com/fabric8-launcher/ngx-launcher/pull/107
https://github.com/fabric8-launcher/ngx-launcher/pull/108
=> fix(launcher): Services for Getting Started - Import Flow

src/app/space/create/deployments/apps/deployments-apps.component.html
fixes https://github.com/openshiftio/openshift.io/issues/2784
=> fix(deployments): fix display of environment labels

src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html, src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.less, src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.ts, src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.module.ts, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.html, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.less, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.ts, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.module.ts, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.html, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.less, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.ts, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.module.ts, src/app/dashboard-widgets/environment-widget/environment-widget.component.html, src/app/dashboard-widgets/environment-widget/environment-widget.component.less, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.html, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.less, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.ts, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.module.ts, src/app/space/analyze/analyze-overview/analyze-overview.component.html, src/app/space/analyze/analyze-overview/analyze-overview.component.less, src/app/space/analyze/analyze-overview/analyze-overview.component.ts, src/app/space/analyze/analyze.component.ts, src/app/space/analyze/analyze.module.ts, src/assets/stylesheets/shared/_cards.less
Update the Space Dashboard to match the latest designs from https://github.com/fabric8-ui/fabric8-ux/issues/925.
This only covers HTML/CSS and is hidden by the Internal Feature Flag as well as the Development Flag.
=> fix(Analyze): Update the Space Dashboard to match new UX

src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.ts, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.ts, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.ts, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.ts, src/app/dashboard-widgets/recent-pipelines-widget/recent-pipelines-widget.component.ts, src/app/home/home.component.ts, src/app/home/work-item-widget/work-item-widget.component.ts, src/app/space/analyze/analyze-overview/analyze-overview.component.ts, src/app/space/analyze/analyze.component.ts
Fixes https://github.com/openshiftio/openshift.io/issues/2813
@mindreeper2420 since we use the component now those boolean are not needed any more
=> clean-up(new-dashbard): remove unused observable causing x2 http calls

package.json, src/app/space/app-launcher/services/app-launcher-project-summary.service.ts
- This version upgrade handles some bug fixes
- Updated jsdoc comments
=> fix(version): Updated ngx-forge to 0.0.63-development

package.json, src/app/space/app-launcher/services/app-launcher-gitprovider.service.ts, src/app/space/app-launcher/services/app-launcher-project-summary.service.ts
adds the check for data and bumps ngx-forge version to 0.0.64-development
=> fix(launcher): adds checks for data and bumps ngx-forge version

src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.html, src/app/home/work-item-widget/work-item-widget.component.html
- fixes issue https://github.com/openshiftio/openshift.io/issues/2826
The detail page URLs for work-items were changed a while ago. This PR is to fix the navigation of work item from both home page and space page.
=> fix(workitem): work item detail URL is updated

src/app/space/app-launcher/services/app-launcher-dependency-check.service.ts
- updates default values for artifact, group_id, version
fixes below issues
- https://github.com/openshiftio/openshift.io/issues/2833
- https://github.com/openshiftio/openshift.io/issues/2837
=> fix(launcher): updates default values for artifact, group_id, version

package.json
This upgrade contains the following changes
1. Set default values for artifactid , groupId and version
2. Updates to the summary screen in the import flow as per UXD
3. Handled inconsistency in selection of mission and runtime after redirecting from github step
4. Updates Runtime and Mission screen as per UXD
=> ngx-forge upgraded to 0.0.66-development

README.md
Update README. Add required versions for node and npm.
=> docs(readme): add node & npm versions

src/a-runtime-console/kubernetes/ui/pipeline/build-stage-view/build-stage-view.component.html, src/a-runtime-console/kubernetes/ui/pipeline/list/list.pipeline.component.html
Added ids should increase E2E tests readability and stability.
fixes openshiftio/openshift.io#2863
=> Added ids to pipelines html pages.

config/webpack.aot.js, config/webpack.prod.js
This is a possible solution to fix the TypeError reported https://github.com/openshiftio/openshift.io/issues/2915
=> fix(bug): remove webpack plugin Dedupe to stop a TyepError

package.json
fix(version): update fabric8-planner to 0.43.11
=> fix(version): update fabric8-planner to 0.43.11

package.json, src/app/space/app-launcher/create-app/create-app.component.html, src/app/space/app-launcher/import-app/import-app.component.html, src/app/space/app-launcher/services/app-launcher-gitprovider.service.ts, src/app/space/app-launcher/services/app-launcher-project-summary.service.ts
fixes issues with launcher and version upgrade for ngx-forge
- Dropdown from runtimes screen has to be changed for OSIO flow (https://github.com/openshiftio/openshift.io/issues/2937)
- Editing the app name does not reflect in the subsequent screens in Import flow
(https://github.com/openshiftio/openshift.io/issues/2916)
- In GitHub Provider View Location dropdown should show User's ID as the default
(https://github.com/openshiftio/openshift.io/issues/2942)
=> fix(launcher): fixes issues with launcher and version upgrade ngx-forge 

config/webpack.common.js, config/webpack.dev.js, src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.less, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.less, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.less, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.less, src/app/home/home.component.less, src/app/space/add-app-overlay/add-app-overlay.component.less, src/app/space/add-space-overlay/add-space-overlay.component.less, src/app/space/create/deployments/apps/deployment-card.component.less, src/app/space/create/deployments/apps/deployment-details.component.less
- Set the build and local development environments to fail when there are stylelint errors.
- Fix errors so build passes
=> fix(stylelint): fail prod and dev build on stylelint errors

src/app/space/create/deployments/services/deployments.service.spec.ts
fixes https://github.com/openshiftio/openshift.io/issues/2818
=> feat(deployments): tests added for deleting deployment

src/app/feature-flag/notification-footer/feature-footer.component.spec.ts, src/app/feature-flag/notification-footer/feature-footer.component.ts
fixes https://github.com/openshiftio/openshift.io/issues/2400  for error cases
=> test(feature-flag): add error check

package.json
Handles the following issues and features
openshiftio/openshift.io#2936
openshiftio/openshift.io#3007
openshiftio/openshift.io#3008
=> fix(version): updates ngx-forge to 0.0.74-development

src/app/feature-flag/notification-footer/feature-footer.component.html
Fixes https://github.com/openshiftio/openshift.io/issues/3039
=> fix(html): html bug fixed

package.json
-  updates ngx-forge to 0.0.75-development
Tracks : 
https://github.com/openshiftio/openshift.io/issues/3022
=> fix(launcher): updates ngx-forge to 0.0.75-development

src/app/feature-flag/notification-footer/feature-footer.component.spec.ts, src/app/feature-flag/notification-footer/feature-footer.component.ts
fixes https://github.com/openshiftio/openshift.io/issues/3089
=> fix(feature-flag): better check for empty featureflag icon

src/app/app.component.html
fixes https://github.com/openshiftio/openshift.io/issues/3100
=> fix(codebases): enable backaction outlet in routing

package.json, src/app/space/app-launcher/services/app-launcher-project-progress.service.spec.ts, src/app/space/app-launcher/services/app-launcher-project-progress.service.ts, src/app/space/app-launcher/services/app-launcher-project-summary.service.ts
- Fixes this issue https://github.com/openshiftio/openshift.io/issues/3045
- This PR has these changes https://github.com/fabric8-launcher/ngx-launcher/pull/164
=> fix(launcher): Bugs fixed

src/app/feature-flag/notification-footer/feature-footer.component.html, src/app/feature-flag/notification-footer/feature-footer.component.spec.ts, src/app/feature-flag/notification-footer/feature-footer.component.ts
fixes https://github.com/openshiftio/openshift.io/issues/3051
=> fix(feature-flag): tooltip doesn't display feature(s)

src/app/space/create/deployments/apps/deployment-details.component.html, src/app/space/create/deployments/apps/deployment-details.component.ts, src/app/space/create/deployments/apps/deployment-graph-label.component.html, src/app/space/create/deployments/apps/deployment-graph-label.component.spec.ts, src/app/space/create/deployments/apps/deployment-graph-label.component.ts
fixes openshiftio/openshift.io/issues/2714
Is a copy of https://github.com/fabric8-ui/fabric8-ui/pull/2729 with latest review comments addressed.
I will close the other PR when this is merged.
=> fix(deployments): show reasonable graph label defaults

src/app/space/app-launcher/services/app-launcher-project-summary.service.ts
- updates key names for launch and import call
Associated PR : https://github.com/fabric8-launcher/launcher-backend/pull/321
=> fix(launcher): updates key names for launch and import call

src/app/dashboard-widgets/environment-widget/application-overview.service.spec.ts, src/app/dashboard-widgets/environment-widget/application-overview.service.ts, src/app/dashboard-widgets/environment-widget/environment-widget.component.html
fixes https://github.com/openshiftio/openshift.io/issues/3173
=> fix(environment-widget): disable links when deployment has 0 pods

src/app/shared/login.service.ts
The error and context services are unused. This PR removes them to keep the code clean.
=> fix(login-service): remove unused imports

src/app/app-routing.module.ts, src/app/feature-flag/service/feature-toggles.service.spec.ts, src/app/feature-flag/service/feature-toggles.service.ts
fixes https://github.com/openshiftio/openshift.io/issues/2626
=> refactor(feature-flag): implement cache for component feature flags

package.json
Fixes: https://github.com/openshiftio/openshift.io/issues/2963
=> fix(version): update fabric8-stack-analysis-ui to 0.11.3

src/a-runtime-console/kubernetes/model/pipelinestage.model.ts
handles routes not appearing for stage/prod in pipelines screen for new launcher flow
Tracks : 
- https://github.com/openshiftio/openshift.io/issues/3003
- https://github.com/openshiftio/openshift.io/issues/2920
=> fix(pipelines): handles routes not appearing for stage/prod

src/app/space/settings/collaborators/collaborators.component.spec.ts, src/app/space/settings/collaborators/collaborators.component.ts
fix https://github.com/openshiftio/openshift.io/issues/3293
=> fix(collaborators): sort collaborators

package.json
fixes https://github.com/openshiftio/openshift.io/issues/1001
=> fix(version): update ngx-fabric8-wit to 6.20.3

src/app/feature-flag/notification-footer/feature-footer.component.spec.ts
tests related to https://github.com/openshiftio/openshift.io/issues/3332
=> test(feature-footer): should always display flask icon

package.json
Contains the following changes
- https://github.com/fabric8-launcher/ngx-launcher/pull/189
- https://github.com/fabric8-launcher/ngx-launcher/pull/190
=> fix(version): update ngx-forge to 0.0.82

.gitignore, package-lock.json
This is needed for the Analytics to search and valid the libraries in this epic https://github.com/openshiftio/openshift.io/issues/2774
This is also useful to the developers of this project as it locks down the libs so that each install gets the same versions for the whole node tree.
=> fix(build): add package-lock

src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html, src/app/space/create/codebases/codebases-toolbar/codebases-toolbar.component.html, src/app/space/create/codebases/codebases-toolbar/codebases-toolbar.component.ts, src/app/space/create/codebases/codebases.component.html, src/app/space/create/codebases/codebases.component.spec.ts, src/app/space/create/codebases/codebases.component.ts, src/app/space/create/codebases/codebases.module.ts
updates legacy import codebase flow with new launcher flow
Tracks : 
- https://github.com/openshiftio/openshift.io/issues/3363
=> feat(launcher): updates legacy import codebase with new launcher flow

src/app/profile/overview/work-items/work-items.component.html
This PR fixes this issue:
https://github.com/openshiftio/openshift.io/issues/2826
=> fix(workItem): use workitem number instead of workItem id for detail page

src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.component.spec.ts, src/app/space/create/codebases/codebases-item-actions/codebases-item-actions.component.ts, src/app/space/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.spec.ts, src/app/space/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.ts, src/app/space/create/codebases/codebases.component.ts, src/app/space/create/codebases/services/che.ts
WIP
fixes https://github.com/openshiftio/openshift.io/issues/3426
@ibuziuk I'm not sure how to test full capacity, each time i asked for status i get `clusterFull: false`
```
curl https://api.prod-preview.openshift.io/api/codebases/che/state -H "Authorization: Bearer $TOKEN"
{"clusterFull":false,"multiTenant":true,"running":true}
```
could you test with full capacity reached?
=> feat(che): check che capacity status before creating workspace

package.json, src/app/space/add-app-overlay/add-app-overlay.component.html, src/app/space/add-app-overlay/add-app-overlay.component.spec.ts, src/app/space/add-app-overlay/add-app-overlay.component.ts, src/app/space/forge-wizard/components/flow-selector/flow-selector.component.html
Fixes:
https://github.com/openshiftio/openshift.io/issues/3411
https://github.com/openshiftio/openshift.io/issues/3418
Tracks: https://github.com/openshiftio/openshift.io/issues/3453
Removes New launcher link as the flow is not useful now.
Updates ngx-forge to 0.0.88 version
=> fix(case): make the application name to always be lowercase

src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.ts, src/app/dashboard-widgets/applications-widget/applications-list-item/applications-list-item.component.html, src/app/dashboard-widgets/applications-widget/applications-list-item/applications-list-item.component.spec.ts, src/app/dashboard-widgets/applications-widget/applications-list-item/applications-list-item.module.ts
Tracks: openshiftio/openshift.io#3380
=> fix(ux): removes stack report from applications in dashboard.

src/app/space/settings/areas/areas-toolbar/areas-toolbar.component.html, src/app/space/settings/areas/areas-toolbar/areas-toolbar.component.less
OSIO Issue: https://github.com/openshiftio/openshift.io/issues/3475
=> fix(toolbar): fix padding issue in toolbar

src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.ts, src/app/home/work-item-widget/work-item-widget.component.ts, src/app/profile/overview/work-items/work-items.component.ts, src/app/shared/workitem-utils.spec.ts, src/app/shared/workitem-utils.ts
- This is not the ideal way of doing it.
- The backend request should be modified in future for this filter but this will require meta state concept and we don't have that currently.
- see openshiftio/openshift.io#3473
=> fix(workitems): filter out closed, removed or done work items

src/a-runtime-console/kubernetes/ui/pipeline/input-action-dialog/input-action-dialog.component.spec.ts, src/a-runtime-console/kubernetes/ui/pipeline/input-action-dialog/input-action-dialog.component.ts, src/app/dashboard-widgets/applications-widget/applications-list-item/applications-list-item.component.ts
Fix for https://github.com/openshiftio/openshift.io/issues/3356
=> fix(jenkins-status): checks for Jenkins status before promoting

package-lock.json, package.json, src/app/profile/settings/feature-opt-in/feature-opt-in.component.html, src/app/profile/settings/feature-opt-in/feature-opt-in.component.less, src/app/profile/settings/feature-opt-in/feature-opt-in.component.spec.ts, src/app/profile/settings/feature-opt-in/feature-opt-in.component.ts
fixes https://github.com/openshiftio/openshift.io/issues/3427
@dlabrecq now we're missing the option to have a radio-button list in the config of the component. atm the component is not compliant with https://redhat.invisionapp.com/share/KAF97RBGB#/screens/276638410 bc the radio button is "after" the border line of the expandable icon.
cc @mceledonia
=> fix(opt-in): better usage of pfng-list

src/app/space/analyze/analyze-overview/analyze-overview.component.spec.ts
Fix space dashboard unit test by adding missing feature flag provider.
=> Fix space dashboard unit test

src/app/profile/update/update.component.html, src/app/profile/update/update.component.spec.ts, src/app/profile/update/update.component.ts
Fixes - https://github.com/openshiftio/openshift.io/issues/3309.
- Handles maximum chars limit for profile bio input field and limits the update to 255 chars.
- Handles the issue with right click paste of text in the input and limits the chars.
- Adds a test.
=> fix(profile): handle over max char limit for bio.

src/app/space/create/pipelines/pipelines.component.html, src/app/space/create/pipelines/pipelines.component.less, src/app/space/create/pipelines/pipelines.component.spec.ts, src/app/space/create/pipelines/pipelines.component.ts, src/app/space/create/pipelines/pipelines.module.ts
fixes launcher flow in pipelines view with feature flag
Tracks : 
https://github.com/openshiftio/openshift.io/issues/3501
=> fix(launcher) : fixes launcher flow in pipelines view with feature flag

src/app/space/create/deployments/apps/deployment-card-container.component.html, src/app/space/create/deployments/apps/deployment-card-container.component.less, src/app/space/create/deployments/apps/deployment-card-container.component.spec.ts, src/app/space/create/deployments/apps/deployment-card-container.component.ts, src/app/space/create/deployments/apps/deployment-card.component.ts
See https://github.com/openshiftio/openshift.io/issues/3125
=> Expand entire row of Deployment cards on click

package-lock.json, package.json, src/app/space/add-app-overlay/add-app-overlay.component.html, src/app/space/add-app-overlay/add-app-overlay.component.spec.ts, src/app/space/add-app-overlay/add-app-overlay.component.ts, src/app/space/add-app-overlay/add-app-overlay.module.ts, src/app/space/app-launcher/services/app-launcher-dependency-check.service.spec.ts, src/app/space/app-launcher/services/app-launcher-dependency-check.service.ts
- This PR fix will not allow a user to enter a existing application name in the current space.
- Upgrade ngx-forge to 0.1.6 which also has the updated for the getting started screens
Addresses :- https://github.com/openshiftio/openshift.io/issues/3399
=> fix(launcher): Don't allow a user to enter the existing application name

src/a-runtime-console/kubernetes/ui/pipeline/build-stage-view/build-stage-view.component.html, src/a-runtime-console/kubernetes/ui/pipeline/build-stage-view/build-stage-view.component.less, src/a-runtime-console/kubernetes/ui/pipeline/build-stage-view/build-stage-view.spec.ts
- provide info to the user until stages start
- adds specs
Tracks: 
https://github.com/openshiftio/openshift.io/issues/945
=> fix(pipelines): provide info to user until stages starts, adds specs

src/app/space/add-app-overlay/add-app-overlay.component.html, src/app/space/add-app-overlay/add-app-overlay.component.spec.ts, src/app/space/add-app-overlay/add-app-overlay.component.ts, src/app/space/app-launcher/services/app-launcher-dependency-check.service.spec.ts, src/app/space/app-launcher/services/app-launcher-dependency-check.service.ts
- Don't populate the application name by default
- Let the user enter it
- Disable the `continue` button by default.
- Includes tests
**Addresses** https://github.com/openshiftio/openshift.io/issues/3607
=> fix(launcher): Disable continue button on load

src/app/profile/spaces/spaces.component.html
Prevent form submission when Enter key is pressed while the search input has focus.
fixes https://github.com/openshiftio/openshift.io/issues/2743
=> fix(spaces): do not refresh page on Enter

src/app/space/add-app-overlay/add-app-overlay.component.html, src/app/space/add-app-overlay/add-app-overlay.component.spec.ts, src/app/space/add-app-overlay/add-app-overlay.component.ts
Addresses:- https://github.com/openshiftio/openshift.io/issues/3639
=> fix(launcher): removed flags to make the application create screen work

src/app/space/create/deployments/apps/deployment-details.component.less, src/app/space/create/deployments/apps/deployment-graph-label.component.less, src/app/space/create/deployments/apps/deployments-apps.component.less, src/app/space/create/deployments/deployments.component.less, src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.less, src/app/space/create/deployments/resource-usage/resource-card.component.less, src/app/space/create/deployments/resource-usage/resource-card.component.ts
Move style classes to component .less files and combine duplicates
=> style(deployments): clean up stylesheets

src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html, src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.spec.ts, src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.ts, src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.module.ts, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.html, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.component.ts, src/app/dashboard-widgets/analytical-report-widget/analytical-report-widget.module.ts, src/app/dashboard-widgets/applications-widget/applications-widget.component.html, src/app/dashboard-widgets/applications-widget/applications-widget.component.spec.ts, src/app/dashboard-widgets/applications-widget/applications-widget.component.ts, src/app/dashboard-widgets/applications-widget/applications-widget.module.ts, src/app/dashboard-widgets/environment-widget/environment-widget.component.html, src/app/dashboard-widgets/environment-widget/environment-widget.module.ts, src/app/dashboard-widgets/loading-widget/loading-widget.component.spec.ts, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.html, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.spec.ts, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.ts, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.module.ts, src/app/dashboard-widgets/work-item-widget/work-item-widget.component.html, src/app/dashboard-widgets/work-item-widget/work-item-widget.component.spec.ts, src/app/dashboard-widgets/work-item-widget/work-item-widget.component.ts, src/app/dashboard-widgets/work-item-widget/work-item-widget.module.ts
Added loading behavior to the widgets of the space dashboard.
Fixes: https://github.com/openshiftio/openshift.io/issues/3157
Screenshot 1: Experimental features
Screenhost 2: Production-only features
=> Space dashboard: Added loading behavior to widgets

src/app/space/create/deployments/services/deployments.service.spec.ts, src/app/space/create/deployments/services/deployments.service.ts
This addresses https://github.com/openshiftio/openshift.io/issues/2713
The error messages for http specific errors are made more user friendly. Tests are added to verify all paths that http error handling is involved, but technically not all paths that eventually lead to the http error handling.
Thoughts? I think there is a lot of room for different implementation forms and different error messages. Any suggestions are welcomed and very much appreciated!
=> fix(deployments): update error messages to be more user friendly

.gitignore
as suggested in https://github.com/fabric8-ui/fabric8-ui/pull/2944#discussion_r192416227
=> fix(gitignore): add generated lint folder

config/webpack.common.js, config/webpack.dev.js, package.json, src/app/shared/api-locator.service.ts, src/app/space/app-launcher/app-launcher.component.spec.ts, src/app/space/app-launcher/app-launcher.module.ts, src/app/space/app-launcher/create-app/create-app.component.html, src/app/space/app-launcher/create-app/create-app.module.ts, src/app/space/app-launcher/services/app-launcher-dependency-editor.service.ts, src/app/space/app-launcher/services/app-launcher-project-summary.service.ts, src/app/space/app-launcher/shared/analytics-url.service.ts, src/app/space/app-launcher/shared/mock-helper.service.ts, tsconfig-aot.json, tsconfig.json
- Dependency editor as an internal feature.
- Dependency editor step is added after mission and runtime step.
- Summary screen is edited for showing additional dependencies.
Associated issue - https://github.com/openshiftio/openshift.io/issues/3515
=> Introduces Dependency Editor as a new feature

src/app/space/app-launcher/app-launcher.component.spec.ts, src/app/space/app-launcher/app-launcher.module.ts
- gitHub authorization for launcher flow
Tracks : https://github.com/openshiftio/openshift.io/issues/3743
=> fix(launcher): gitHub authorization for launcher flow

package-lock.json, package.json
This is a library that we need for the planner, specifically on ngrx/store.
=> fix(ngrx): added entity library for data normalization

package-lock.json, package.json
Updates version of ngx-forge
- fixes selection of runtime and mission step (https://github.com/fabric8-launcher/ngx-launcher/pull/269/files)
=> fix(launcher): fixes selection of runtime and mission step

package.json
=> fix(launcher): fixes version

src/app/shared/api-locator.service.ts, src/app/shared/config/fabric8-ui-config.ts, src/app/space/app-launcher/app-launcher.component.spec.ts, src/app/space/app-launcher/app-launcher.module.ts, src/app/space/app-launcher/shared/analytics-url.service.ts
Changes the API locator service, fabric8-ui.config to handle environment variables
=> fix(env): adds changes in the api-locator.service, fabric8-ui.config to address env related changes for fabric8-analytics-dependency-editor

package-lock.json, package.json
- Has the latest version of fabric8-analytics-dependency-editor.
=> fix(version): updates ngx-forge to 0.2.31

openshift/fabric8-ui.app.yaml
updates env in the template for build
Tracks : 
https://github.com/openshiftio/openshift.io/issues/3356#issuecomment-396562994
=> feat(pipelines): updates env in template for build

src/app/space/create/deployments/apps/deployment-card-container.component.spec.ts, src/app/space/create/deployments/apps/deployment-card.component.spec.ts, src/app/space/create/deployments/apps/deployment-details.component.spec.ts, src/app/space/create/deployments/apps/deployments-apps.component.spec.ts, src/app/space/create/deployments/deployments-donut/deployments-donut.component.spec.ts, src/app/space/create/deployments/deployments-toolbar/deployments-toolbar.component.spec.ts, src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.spec.ts, src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts
These commits just do some test cleanup in the Deployments area, so the tests are easier to read and maintain. Cleanup for services' tests are not included since some of those will be a bit more extensive.
=> Test cleanup

package-lock.json, package.json, src/app/app.module.ts, src/app/dashboard-widgets/work-item-widget/work-item-barchart/work-item-barchart-config.ts, src/app/dashboard-widgets/work-item-widget/work-item-barchart/work-item-barchart.module.ts, src/app/space/create/codebases/codebases-item-heading/codebases-item-heading.module.ts, src/app/space/create/codebases/workspaces-notification/workspaces-notification.module.ts, src/app/space/create/deployments/apps/deployment-card.component.spec.ts, src/app/space/create/deployments/apps/deployment-details.component.html, src/app/space/create/deployments/apps/deployment-details.component.spec.ts, src/app/space/create/deployments/apps/deployment-details.component.ts, src/app/space/create/deployments/deployments-linechart/deployments-linechart-config.ts, src/app/space/create/deployments/deployments.module.ts, src/app/space/settings/areas/areas.module.ts
Removes deprecated and unused patternfly-ng module imports.
Resolves https://github.com/openshiftio/openshift.io/issues/2704
=> patternfly-ng: remove deprecations

package-lock.json, package.json
The planner version has been bumped up as a feature was introduced. Rest were bug fixes.
=> fix(version): update fabric8-planner to 0.50.3

package-lock.json, package.json, src/app/space/app-launcher/services/app-launcher-dependency-check.service.spec.ts, src/app/space/app-launcher/services/app-launcher-dependency-check.service.ts, src/app/space/app-launcher/services/app-launcher-project-summary.service.spec.ts, src/app/space/app-launcher/services/app-launcher-project-summary.service.ts
this should be used in together with https://github.com/fabric8-launcher/ngx-launcher/pull/277
=> fix: pass retry step to the backend

package-lock.json, package.json
- releases ngx-forge with fixed versioning of patterfly-ng
Tracks : 
https://github.com/openshiftio/openshift.io/issues/3833
=> fix(launcher): releases ngx-forge with fixed versioning of patterfly-ng

package-lock.json, package.json
update the package-lock to with a new one to try and get a clean build
=> fix(package): update ngx-login-client to 1.4.3

package-lock.json, package.json, src/app/app.module.ts, src/app/environment.ts, src/app/shared/account/provider.service.spec.ts, src/app/shared/analytics.service.ts, src/app/space/add-app-overlay/add-app-overlay.component.ts, src/app/space/app-launcher/create-app/create-app.component.ts, src/app/space/app-launcher/import-app/import-app.component.ts
User Story :- https://github.com/openshiftio/openshift.io/issues/3241
=> fix(telemetry): Add telemetry for App Launcher

src/app/shared/jenkins.service.ts
- removes trailing slash
Tracks: https://github.com/openshiftio/openshift.io/issues/3865
=> fix(pipelines): removes trailing slash

package-lock.json, package.json, src/app/space/app-launcher/create-app/create-app.module.ts, src/app/space/app-launcher/services/app-launcher-dependency-editor.service.spec.ts, src/app/space/app-launcher/services/app-launcher-dependency-editor.service.ts, src/app/space/app-launcher/services/app-launcher-mission-runtime.service.ts, src/app/space/app-launcher/services/app-launcher-project-summary.service.ts
Adds blank booster support for each runtime.
Tracks : 
- https://github.com/openshiftio/openshift.io/issues/3244
Depends on : 
- https://github.com/fabric8-analytics/fabric8-analytics-dependency-editor/pull/105
=> feat(launcher): adds blank booster support

package-lock.json, package.json
Update fabric8-planner to 0.50.22
=> fix(version): update fabric8-planner to 0.50.22

src/app/space/create/codebases/codebases-item-heading/codebases-item-heading.component.html, src/app/space/create/codebases/codebases-item-heading/codebases-item-heading.component.less, src/app/space/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.less, src/app/space/create/codebases/codebases-item/codebases-item.component.html, src/app/space/create/codebases/codebases-item/codebases-item.component.spec.ts, src/app/space/create/codebases/codebases-item/codebases-item.component.ts, src/app/space/create/codebases/codebases-item/codebases-item.module.ts, src/app/space/create/codebases/services/codebases.service.spec.ts, src/app/space/create/codebases/services/codebases.service.ts
- adds security alert subscription 
Invision : https://redhat.invisionapp.com/share/VPKMQPFMF8U#/screens/302332662
Tracks : 
- https://github.com/openshiftio/openshift.io/issues/3823
Changes can be merged once other pieces related to notification service is in place
=> feat(codebases): adds security alert subscription

src/app/profile/overview/work-items/work-items.component.html
Fixes https://github.com/openshiftio/openshift.io/issues/3868
Fixes https://github.com/fabric8-services/fabric8-auth/issues/537
- Using username of the current space owner instead of current logged in user.
=> fix(profile):  404 error while opening My Work Items from Profile page 

src/app/app-routing.module.ts, src/app/space/create/codebases/codebases-item-heading/codebases-item-heading.component.html, src/app/space/create/codebases/codebases-item-heading/codebases-item-heading.component.less, src/app/space/create/codebases/codebases-item-heading/codebases-item-heading.component.spec.ts, src/app/space/create/codebases/codebases-item-heading/codebases-item-heading.component.ts, src/app/space/create/codebases/codebases-item/codebases-item.component.html, src/app/space/create/codebases/codebases-item/codebases-item.component.less, src/app/space/create/codebases/codebases-item/codebases-item.component.ts, src/app/space/create/codebases/codebases.component.html, src/app/space/create/codebases/codebases.component.less, src/app/space/create/codebases/codebases.component.spec.ts, src/app/space/create/create-routing.module.ts
- adds security alert notification under toggle feature
- Adds routing for feature flag for `/create ` to show feature-flag icon
=> fix(codebases): adds security alert under toggle feature

package-lock.json, package.json
to fix https://openshift.io/openshiftio/Openshift_io/plan/detail/158
=> fix(feature-flag): update to latest version

package-lock.json, package.json
This updates ngx-fabric8-wit dependency to the latest version.
=> fix(package): update ngx-fabric8-wit to 6.21.0

src/app/home/home.component.html, src/app/home/home.component.ts, src/app/home/home.module.ts, src/app/home/recent-spaces-widget/recent-spaces-widget.component.html, src/app/home/recent-spaces-widget/recent-spaces-widget.component.spec.ts, src/app/home/recent-spaces-widget/recent-spaces-widget.component.ts, src/app/home/recent-spaces-widget/recent-spaces-widget.module.ts, src/assets/stylesheets/shared/_cards.less
This PR includes several refactoring commits, a test addition commit, and one commit that should address a simple recent bug report [0].
[0] https://github.com/openshiftio/openshift.io/issues/4003
=> Recent spaces widget

src/app/home/home.component.ts, src/app/home/home.module.ts
This is includes cleanup of unused imports, unused variables, subscriptions and initialization.
=> fix(home): clean up unused code

src/app/shared/analytics.service.ts
- puts a check for dom access as phantom js was crashing
=> fix(launcher): puts a check for dom access as phantom js was crashing

src/app/layout/error/error.module.ts
related to https://openshift.io/openshiftio/Openshift_io/plan/detail/348
=> fix(error): remove unused HttpModule dependency

src/app/space/add-app-overlay/add-app-overlay.component.spec.ts, src/app/space/add-app-overlay/add-app-overlay.component.ts, src/app/space/add-space-overlay/add-space-overlay.component.ts, src/app/space/analyze/analyze-overview/analyze-overview.component.ts, src/app/space/app-launcher/create-app/create-app.component.ts, src/app/space/app-launcher/import-app/import-app.component.ts, src/app/space/create/codebases/codebases.component.ts, src/app/space/create/deployments/apps/deployments-apps.component.ts, src/app/space/create/pipelines/pipelines.component.ts
- updated the event names in telemetry use case to match with the woopra standards
- added a spec for the code change.
=> fix(telemetry): improvements in event names

package-lock.json, package.json, src/app/layout/header/menus.service.spec.ts, src/app/layout/header/menus.service.ts
Story - https://openshift.io/openshiftio/Openshift_io/plan/detail/38
Task - https://openshift.io/openshiftio/Openshift_io/plan/detail/358
For custom-query support story this PR adds query tab in planner sub-menu
=> feat(query-tab): add query-tab in planner sub-menu

src/app/space/plan/plan.module.ts
related to https://openshift.io/openshiftio/Openshift_io/plan/detail/348
=> fix(plan): remove unused HttpModule dependency

package-lock.json, package.json
Update ngx-launcher version to 1.0.12.
Tracks - https://github.com/openshiftio/openshift.io/issues/4110 and https://github.com/openshiftio/openshift.io/issues/3959
=> fix(launcher): update ngx-launcher to 1.0.12

package-lock.json, package.json
- This version has the changes to support new events response
=> fix(version): update fabric8-planner to 0.53.2

package-lock.json, package.json
This version contains these fixes.
1. openshiftio/openshift.io#3443
2. Create app flow of this issue https://github.com/openshiftio/openshift.io/issues/4140
3. openshiftio/openshift.io#3927
4. https://github.com/fabric8-launcher/ngx-launcher/issues/349 and https://github.com/openshiftio/openshift.io/issues/3997
=> fix(launcher): update ngx-launcher to 1.0.16

src/app/base/config.store.ts, src/app/dashboard-widgets/create-work-item-widget/create-work-item-widget.component.spec.ts, src/app/dashboard-widgets/pipelines-widget/pipelines-widget.component.spec.ts, src/app/dashboard-widgets/recent-workspaces-widget/recent-workspaces-widget.component.spec.ts, src/app/home/work-item-widget/work-item-widget.component.spec.ts, src/app/landing-page/landing-page.module.ts, src/app/space/add-app-overlay/add-app-overlay.component.spec.ts, src/app/space/app-launcher/app-launcher.component.spec.ts, src/app/space/app-launcher/app-launcher.module.ts, src/app/space/app-launcher/create-app/create-app.module.ts, src/app/space/app-launcher/import-app/import-app.module.ts
=> cleanup(http): remove unused http references and update to httpclient where needed

src/app/getting-started/services/getting-started.service.ts
Add type annotations in GettingStartedService
This follows from a comment here: https://github.com/fabric8-ui/fabric8-ui/pull/3221#issuecomment-411470253
=> style(getting-started): add type annotations

src/app/shared/account/provider.service.spec.ts, src/app/shared/account/provider.service.ts
Fixes https://github.com/openshiftio/openshift.io/issues/4268
Fixes https://github.com/fabric8-services/fabric8-auth/issues/633
=> fix(auth): add auth header in provider service

src/app/profile/overview/spaces/overview-spaces.component.spec.ts
This fixes unit tests that were broken after an incorrect rebase from #3298
Sorry about that;
=> fix(profile): fix overview spaces unit tests

package-lock.json, package.json
- In this version all planner is updated with new rxjs pipe
- Now planner is rxjs 6 ready
=> fix(ngrx): upgrade planner version to 0.55.7

package-lock.json, package.json
- fixed the interceptor issue in planner
- fixes openshiftio/openshift.io#4298
=> fix(version): update fabric8-planner to 0.55.9

src/app/app.module.ts, src/app/shared/interceptors/cache.interceptor.spec.ts, src/app/shared/interceptors/cache.interceptor.ts, src/app/shared/interceptors/index.ts, src/app/shared/interceptors/request-id.interceptor.spec.ts, src/app/shared/interceptors/request-id.interceptor.ts, src/app/shared/request-cache.service.ts
- Adds an interceptor to cache GET requests.
- Adds an interceptor to add `X-Request-Id` header for `WIT` and `AUTH` URLs.
=> feat(interceptors): add interceptors to replicate Fabric8UIHttpService

src/app/space/add-app-overlay/add-app-overlay.component.html, src/app/space/add-app-overlay/add-app-overlay.component.spec.ts, src/app/space/add-app-overlay/add-app-overlay.component.ts
Issue - https://github.com/openshiftio/openshift.io/issues/4018
=> fix(add-app-overlay): close overlay on navigation end

src/app/space/create/deployments/apps/deployments-apps.component.html, src/app/space/create/deployments/apps/deployments-apps.component.spec.ts, src/app/space/create/deployments/apps/deployments-apps.component.ts
This addresses https://github.com/openshiftio/openshift.io/issues/4317
A test is added to verify the changes.
=> fix(deployments): fix filtering of deployment cards

src/app/space/create/pipelines/pipelines.component.spec.ts, src/app/space/create/pipelines/pipelines.component.ts
Issue - https://openshift.io/openshiftio/Openshift_io/plan/detail/462
This is PR will add queryParams to URL when any filter is applied in pipeline page.
=> feat(pipeline): update the url on filter change

src/app/space/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.html, src/app/space/create/codebases/codebases-item-workspaces/codebases-item-workspaces.component.less
Correct responsive behaviour of workspace selection dropdown component
fixes https://github.com/openshiftio/openshift.io/issues/4336
=> fix(codebases-widget): fix dropdown responsive design

src/app/dashboard-widgets/work-item-widget/work-item-widget.component.ts
Fixes https://github.com/openshiftio/openshift.io/issues/4057
=> fix(work-item-widget): work-item-widget displaying bar chart now

src/app/home/work-item-widget/work-item-widget.component.spec.ts, src/app/home/work-item-widget/work-item-widget.component.ts
Fixes https://github.com/openshiftio/openshift.io/issues/4348
- This comment explains the issue - https://github.com/openshiftio/openshift.io/issues/4348#issuecomment-424018724
- Use already present `loggedInUser` to get `user.id` so no need to subscribe to `userService.getUser()`
=> fix(work-item-widget): fix logout bug

src/app/profile/settings/connected-accounts/connected-accounts.component.ts, src/app/profile/settings/connected-accounts/connected-accounts.spec.ts, src/app/profile/settings/feature-opt-in/feature-opt-in.component.spec.ts, src/app/profile/settings/feature-opt-in/feature-opt-in.component.ts, src/app/profile/settings/notifications/notifications.component.spec.ts, src/app/profile/settings/notifications/notifications.component.ts, src/app/profile/settings/notifications/toggle-bar.component.ts, src/app/profile/settings/resources/resources.component.ts, src/app/profile/settings/services/resource.service.spec.ts, src/app/profile/settings/services/resource.service.ts, src/app/profile/settings/settings.component.ts
General code style cleanup and improvements. Mostly cosmetic, with some improvements to Subscription handling
=> style(settings): code cleanup

src/app/space/create/deployments/apps/delete-deployment-modal.component.spec.ts, src/app/space/create/deployments/apps/deployment-card-container.component.spec.ts, src/app/space/create/deployments/apps/deployment-card-container.component.ts, src/app/space/create/deployments/apps/deployment-card.component.spec.ts, src/app/space/create/deployments/apps/deployment-card.component.ts, src/app/space/create/deployments/apps/deployment-details.component.spec.ts, src/app/space/create/deployments/apps/deployment-details.component.ts, src/app/space/create/deployments/apps/deployment-graph-label.component.spec.ts, src/app/space/create/deployments/apps/deployment-graph-label.component.ts, src/app/space/create/deployments/apps/deployments-apps.component.spec.ts, src/app/space/create/deployments/apps/deployments-apps.component.ts, src/app/space/create/deployments/deployments-donut/deployments-donut-chart/deployments-donut-chart.component.spec.ts, src/app/space/create/deployments/deployments-donut/deployments-donut.component.spec.ts, src/app/space/create/deployments/deployments-donut/deployments-donut.component.ts, src/app/space/create/deployments/deployments-toolbar/deployments-toolbar.component.spec.ts, src/app/space/create/deployments/deployments-toolbar/deployments-toolbar.component.ts, src/app/space/create/deployments/models/memory-unit.spec.ts, src/app/space/create/deployments/models/scaled-memory-stat.spec.ts, src/app/space/create/deployments/models/scaled-net-stat.spec.ts, src/app/space/create/deployments/resource-usage/deployments-resource-usage.component.spec.ts, src/app/space/create/deployments/resource-usage/resource-card.component.spec.ts, src/app/space/create/deployments/resource-usage/resource-card.component.ts, src/app/space/create/deployments/resource-usage/utilization-bar.component.spec.ts, src/app/space/create/deployments/services/deployment-api.service.ts, src/app/space/create/deployments/services/deployment-status.service.spec.ts, src/app/space/create/deployments/services/deployments.service.spec.ts, src/app/space/create/deployments/services/deployments.service.ts
Add type annotations, use const where appropriate, do not leave
subscriptions dangling in tests, and other code quality improvements.
=> style(deployments): code cleanup

package.json
set up the build to release now that the version of semantic-release has been updated
=> fix(build): set up the build to release

package-lock.json, package.json
- updates recommender to 1.0.2
Tracks : 
- https://github.com/openshiftio/openshift.io/issues/4363
- update ngx-fabric8-wit version
=> fix(recommender): updates recommender to 1.0.2

config/webpack.dev.js
=> fix(build): switch to 'eval-source-map' for dev as it is faster on reload then 'source-map'

package-lock.json, package.json
updates version of launcher to 2.0.8
Tracks:
- https://github.com/openshiftio/openshift.io/issues/4380
=> fix(launcher): updates version of launcher to 2.0.8

src/app/layout/header/header.component.html
Fixes https://github.com/openshiftio/openshift.io/issues/4327
- Moves chat with us from user menu to help dropdown
=> fix(header): move chat with us to help section

src/app/space/create/codebases/codebases.component.less
Fixes https://github.com/openshiftio/openshift.io/issues/4328
=> fix(codebases): change font weight for codebase title

src/app/home/home.component.html
- Revert changes which caused e2e tests to fail.
=> fix(home): bring back feature flagged old dashboard

package-lock.json, package.json
=> fix(version): Planner version upgraded to 0.56.0

src/a-runtime-console/kubernetes/ui/pipeline/input-action-dialog/input-action-dialog.component.ts
Fixes https://github.com/openshiftio/openshift.io/issues/4453
=> fix(pipeline-call): adds OSIO X-App header

src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.html, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.less, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.spec.ts, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.component.ts, src/app/dashboard-widgets/edit-space-description-widget/edit-space-description-widget.module.ts, src/app/space/analyze/analyze-overview/analyze-overview.module.ts, src/app/space/settings/collaborators/add-collaborators-dialog/add-collaborators-dialog.component.ts
Planner Story - https://openshift.io/openshiftio/Openshift_io/plan/detail/846
Invision Link - https://redhat.invisionapp.com/share/MVOBQ1ZRXHZ#/screens/322783163
- Adds modal for adding collaborators directly from analyze page.
=> feat(analyze): add modal for adding collaborators to analyze page

package-lock.json, package.json, src/app/profile/my-spaces/my-spaces-item-heading/my-spaces-item-heading.component.html, src/app/profile/my-spaces/my-spaces-item-heading/my-spaces-item-heading.component.less, src/app/profile/my-spaces/my-spaces-item-heading/my-spaces-item-heading.component.ts, src/app/profile/my-spaces/my-spaces-item/my-spaces-item.component.html, src/app/profile/my-spaces/my-spaces-item/my-spaces-item.component.less, src/app/profile/my-spaces/my-spaces-item/my-spaces-item.component.spec.ts, src/app/profile/my-spaces/my-spaces-item/my-spaces-item.component.ts, src/app/profile/my-spaces/my-spaces-item/my-spaces-item.service.spec.ts, src/app/profile/my-spaces/my-spaces-item/my-spaces-item.service.ts, src/app/profile/my-spaces/my-spaces.component.html, src/app/profile/my-spaces/my-spaces.component.less
related to https://openshift.io/openshiftio/Openshift_io/plan/detail/845
Current state of restyling:
Collaborators and Work Items counts are currently hardcoded to 0.
=> Format My Spaces list as table

talamer/packages/eslint-plugin-osio/package.json, talamer/packages/stylelint-config-osio/package.json
Upversion `merge` package to latest due to vulnerability check.
=> fix(merge): upversion the merge package due to vulnerability

package-lock.json, package.json
This description was generated using this script:
```sh
#!/bin/bash
set -e
GHORG=${GHORG:-fabric8-ui}
GHREPO=${GHREPO:-fabric8-planner}
cat <<EOF
This description was generated using this script:
\`\`\`sh
`cat $0`
\`\`\`
Invoked as:
`echo GHORG=${GHORG} GHREPO=${GHREPO} $(basename $0) ${@:1}`
EOF
git log \
--pretty="%n**Commit:** https://github.com/${GHORG}/${GHREPO}/commit/%H%n**Author:** %an (%ae)%n**Date:** %aI%n%n%s%n%n%b%n%n----%n" \
${@:1} \
| sed -E "s/([\s|\(| ])#([0-9]+)/\1${GHORG}\/${GHREPO}#\2/g"
```
Invoked as:
GHORG=fabric8-ui GHREPO=fabric8-planner osio-pull.sh v0.57.0..v0.57.3
**Commit:** https://github.com/fabric8-ui/fabric8-planner/commit/8cc7af777cf5820526037765ad3eabd86a01cd27
**Author:** Ibrahim Jarif (jarifibrahim@gmail.com)
**Date:** 2018-11-02T16:30:54+05:30 …
=> fix(version): update fabric8-planner to 0.57.3

src/app/profile/my-spaces/my-spaces-item-actions/my-spaces-item-actions.component.ts
Related to https://github.com/openshiftio/openshift.io/issues/4191
Simply change the casing of the action label.
=> fix(casing): fix spacing accoridng to UX guidance

src/app/layout/header/header.component.html, src/app/layout/header/header.component.less
fix(branding): Update Help link to "About CodeReady Toolchain" - [OSIO-1119](https://openshift.io/openshiftio/Openshift_io/plan/detail/1119)
Reference: https://github.com/openshiftio/openshift.io/issues/4364
=> fix(rebranding): Update Help link to "About CodeReady Toolchain"

src/app/home/empty-state/empty-state.component.html
fix(rebranding): Update home page's empty state to use CodeReady Toolchain - [OSIO-1120](https://openshift.io/openshiftio/Openshift_io/plan/detail/1120)
=> fix(rebranding): Update home page's empty state to use CodeReady Toolchain

src/app/space/add-space-overlay/add-space-overlay.component.html, src/app/space/add-space-overlay/add-space-overlay.component.ts
Issue: https://github.com/openshiftio/openshift.io/issues/4612#issuecomment-444420374
=> fix(add-space-overlay): clear form after submit and fix submit issue

src/app/space/add-space-overlay/add-space-overlay.component.html, src/app/space/add-space-overlay/add-space-overlay.component.spec.ts, src/app/space/add-space-overlay/add-space-overlay.component.ts, src/app/space/add-space-overlay/osio-data-structure-mocks.ts
Created new tests and added small refactoring and bug fixes
- space name and space description are now mapped to string properties
on component, not to Space object.
- Cancel button has explicit type="button" so that it does not submit
form
- spaceFrom was added to component to enable validation testing
- condition that tests if user is logged in was changed from using AND
operator to using OR operator
- created new help class for creating test mocks
=> fix(add-space-overlay) Refactoring + new tests

src/app/profile/my-spaces/my-spaces.component.spec.ts, src/app/profile/my-spaces/my-spaces.component.ts
Fixes https://github.com/openshiftio/openshift.io/issues/4581
=> fix(spaces): fix save pin bug

package-lock.json, package.json
This upgrade fixes the CSS issue of mission and runtime selection screen on prod-preview.
Before:
After:
=> fix(ngx-launcher): upgrade ngx-launcher to 3.4.8

packages/fabric8-ui/src/app/profile/update/update.component.html, packages/fabric8-ui/src/app/profile/update/update.component.spec.ts, packages/fabric8-ui/src/app/profile/update/update.component.ts
Fixes https://github.com/openshiftio/openshift.io/issues/3709
- Removes the `blockInputAtMaxLimit` flag so that there is no auto truncation of characters if over max limit.
- Using `onOverCharsMaxLimit` validates the bio input. If the input is over char limit then the profile update is disabled.
- The PR contains changes related to formatting because of prettier changes on save.
Screenshots -
=> fix(profile): disable profile update if bio char count increases max limit

packages/fabric8-ui/src/app/space/app-launcher/services/app-launcher-mission-runtime.service.spec.ts, packages/fabric8-ui/src/app/space/app-launcher/services/app-launcher-mission-runtime.service.ts
Story: https://openshift.io/openshiftio/Openshift_io/plan/detail/1255
=> fix(mission-runtime.service): add feature flag for nodejs booster

packages/fabric8-ui/src/app/dashboard-widgets/add-codebase-widget/add-codebase-widget.component.html, packages/fabric8-ui/src/app/dashboard-widgets/work-item-widget/work-item-widget.component.html
Fixes https://github.com/openshiftio/openshift.io/issues/4649
=> fix(dashboard): add hyperlinks to work item and codebase widgets

packages/fabric8-ui/src/app/space/add-app-overlay/add-app-overlay.component.html
issue - https://github.com/openshiftio/openshift.io/issues/4707
=> fix(add-app-overlay): update the error message

packages/fabric8-ui/src/app/shared/request-cache.service.ts
Still seeing lots of duplicate requests. Increasing the cache timeout fixes this issue.
=> fix(cache): increase cache TTL to 5000

packages/fabric8-ui/src/app/home/home.component.spec.ts, packages/fabric8-ui/src/app/home/home.component.ts
Fixes the loading state error in home component
=> fix(loading_state): change user fetching to observable in home component

packages/fabric8-ui/src/app/space/app-launcher/services/app-launcher-gitprovider.service.spec.ts, packages/fabric8-ui/src/app/space/app-launcher/services/app-launcher-gitprovider.service.ts
Fix - https://github.com/openshiftio/openshift.io/issues/4711
=> fix(detector): remove extra / from build tool detector url

packages/planner/src/app/components_ngrx/iterations-modal/iterations-modal.component.ts
Issue: https://github.com/openshiftio/openshift.io/issues/3703
- Added date for iteration on startAt 00:00:00Z and endAt 23:59:59Z
=> fix(Iteration): Iteration show active on the last and first day of month

packages/fabric8-ui/src/app/space/app-launcher/services/app-launcher-mission-runtime.service.spec.ts, packages/fabric8-ui/src/app/space/app-launcher/services/app-launcher-mission-runtime.service.ts
Story - https://openshift.io/openshiftio/Openshift_io/plan/detail/1335
=> fix(mission-runtime): add feature flag for golang booster

package-lock.json, packages/fabric8-ui/package.json
updates version of ngx-fabric8-wit
Tracks : https://github.com/openshiftio/openshift.io/issues/4741
=> fix(recommender): updates version of ngx-fabric8-wit

package.json
related changes in fabric8-test repository https://github.com/fabric8io/fabric8-test/pull/1260
=> chore(scripts): temporary npm scripts removed

packages/fabric8-ui/src/app/space/create/codebases/codebases.component.ts, packages/planner/src/app/components_ngrx/planner-board/planner-board.component.ts, packages/planner/src/app/components_ngrx/planner-list/planner-list.component.ts
fixes: https://github.com/openshiftio/openshift.io/issues/4733
- Added update for subscribing of space id
- Changed subscription on change of route
Code:
Backlog:
Board:
=> fix(navigation): page content does not refresh in new navigation

package-lock.json, packages/fabric8-ui/package.json, packages/fabric8-ui/src/app/space/app-launcher/create-app/create-app.component.ts, packages/fabric8-ui/src/app/space/app-launcher/import-app/import-app.component.spec.ts, packages/fabric8-ui/src/app/space/app-launcher/import-app/import-app.component.ts
fix - https://github.com/openshiftio/openshift.io/issues/4569
fix - https://github.com/openshiftio/openshift.io/issues/4539
=> fix(launcher): upgrade ngx-launcher to 3.4.23
